// GENERATED by scratchpad/id52/gen_id52_table.py from PASS3-SHEET.md.
// Every offset was MEASURED by diffing two real .icf saves; none is
// inferred from another radio's driver. Do not hand-edit; regenerate.
//
// `P` in a trailing comment marks an address predicted from the manual's
// menu order and consistent with the observed value, but never moved by a
// pass of its own -- a weaker grade of evidence than the rest.
pub(crate) const ID52_SETTINGS_FIELDS: &[SF] = &[
    SF { key: "auto-power-off", byte: 0x03C9AC, kind: SK::Enum { width: 1, labels: &[(0, "Off"), (1, "30"), (2, "60"), (3, "90"), (4, "120")] } },  // Auto Power Off
    SF { key: "auto-repeater", byte: 0x03C9AE, kind: SK::Enum { width: 1, labels: &[(0, "Off"), (1, "Dup"), (2, "Dup+Tone")] } },  // Auto Repeater
    SF { key: "ptt-lock", byte: 0x03C9AF, kind: SK::Bool },  // PTT Lock
    SF { key: "busy-channel-lockout", byte: 0x03C9B0, kind: SK::Bool },  // Busy Channel Lockout
    SF { key: "time-out-timer", byte: 0x03C9B1, kind: SK::Enum { width: 1, labels: &[(0, "Off"), (1, "1"), (2, "3"), (3, "5"), (4, "10"), (5, "15"), (6, "30")] } },  // Time-Out Timer
    SF { key: "active-band", byte: 0x03C9B2, kind: SK::Enum { width: 1, labels: &[(0, "Single"), (1, "All"), (2, "Ham")] } },  // Active Band
    SF { key: "power-save", byte: 0x03C9B3, kind: SK::Enum { width: 1, labels: &[(0, "Off"), (1, "Short"), (2, "Middle"), (3, "Long")] } },  // Power Save
    SF { key: "monitor", byte: 0x03C9B5, kind: SK::Enum { width: 1, labels: &[(0, "Push"), (1, "Hold")] } },  // Monitor
    SF { key: "dial-speedup", byte: 0x03C9B6, kind: SK::Bool },  // Dial Speedup
    SF { key: "key-lock", byte: 0x03C9B8, kind: SK::Enum { width: 1, labels: &[(0, "Normal"), (1, "No SQL"), (2, "No VOL"), (3, "All")] } },  // Key Lock
    SF { key: "tone-burst", byte: 0x03C9B9, kind: SK::Bool },  // Tone Burst
    SF { key: "mic-gain-internal", byte: 0x03C9BA, kind: SK::Enum { width: 1, labels: &[(0, "1"), (1, "2"), (2, "3"), (3, "4")] } },  // Mic Gain Internal
    SF { key: "mic-gain-external", byte: 0x03C9BB, kind: SK::Enum { width: 1, labels: &[(0, "1"), (1, "2"), (2, "3"), (3, "4")] } },  // Mic Gain External
    SF { key: "vox-enable", byte: 0x03C9BC, kind: SK::Bool },  // VOX Enable
    SF { key: "vox-level", byte: 0x03C9BD, kind: SK::Uint { width: 1 } },  // VOX Level
    SF { key: "vox-delay", byte: 0x03C9BE, kind: SK::Uint { width: 1 } },  // VOX Delay
    SF { key: "vox-time-out-timer", byte: 0x03C9BF, kind: SK::Enum { width: 1, labels: &[(0, "Off"), (1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5"), (6, "10"), (7, "15 min")] } },  // VOX Time Out Timer
    SF { key: "ci-v-address", byte: 0x03C9C0, kind: SK::Uint { width: 1 } },  // CI-V Address
    SF { key: "ci-v-baudrate", byte: 0x03C9C1, kind: SK::Enum { width: 1, labels: &[(0, "300"), (1, "1200"), (2, "4800"), (3, "9600"), (4, "19200"), (5, "Auto")] } },  // CI-V Baudrate
    SF { key: "ci-v-transceive", byte: 0x03C9C2, kind: SK::Bool },  // CI-V Transceive
    SF { key: "vox-head-set", byte: 0x03C9C4, kind: SK::Enum { width: 1, labels: &[(0, "HS-95"), (1, "Other")] } },  // VOX Head Set
    SF { key: "auto-reply", byte: 0x03C9C5, kind: SK::Enum { width: 1, labels: &[(0, "Off"), (1, "On"), (2, "Voice"), (3, "Position")] } },  // Auto Reply
    SF { key: "dv-data-tx", byte: 0x03C9C6, kind: SK::Enum { width: 1, labels: &[(0, "PTT"), (1, "Auto")] } },  // DV Data Tx
    SF { key: "digital-monitor", byte: 0x03C9C7, kind: SK::Enum { width: 1, labels: &[(0, "Auto"), (1, "Digital"), (2, "Analog")] } },  // Digital Monitor
    SF { key: "digital-repeater-set", byte: 0x03C9C8, kind: SK::Bool },  // Digital Repeater Set
    SF { key: "gps-tx-mode", byte: 0x03C9CB, kind: SK::Enum { width: 1, labels: &[(0, "OFF"), (1, "D-PRS"), (2, "NMEA")] } },  // GPS TX Mode
    SF { key: "gps-sentence-gga", byte: 0x03C9CD, kind: SK::Bool },  // GPS Sentence GGA
    SF { key: "gps-sentence-gll", byte: 0x03C9CE, kind: SK::Bool },  // GPS Sentence GLL
    SF { key: "gps-auto-tx-timer", byte: 0x03C9D2, kind: SK::Enum { width: 1, labels: &[(0, "OFF"), (1, "5s"), (2, "10s"), (3, "30s"), (4, "1m"), (5, "3m"), (6, "5m"), (7, "10m"), (8, "30m")] } },  // GPS Auto TX Timer
    SF { key: "dv-auto-detect", byte: 0x03C9D3, kind: SK::Bool },  // DV Auto Detect
    SF { key: "rx-record-rpt", byte: 0x03C9D4, kind: SK::Enum { width: 1, labels: &[(0, "All"), (1, "Latest Only")] } },  // Rx Record (RPT)
    SF { key: "scan-pause-timer-a", byte: 0x03C9D5, kind: SK::Enum { width: 1, labels: &[(0, "2 sec"), (1, "4 sec"), (2, "6 sec"), (3, "8 sec"), (4, "10 sec"), (5, "12 sec"), (6, "14 sec"), (7, "16 sec"), (8, "18 sec"), (9, "20 sec"), (10, "Hold")] } },  // Scan Band A Pause Timer
    SF { key: "scan-pause-timer-b", byte: 0x03C9D6, kind: SK::Enum { width: 1, labels: &[(0, "2 sec"), (1, "4 sec"), (2, "6 sec"), (3, "8 sec"), (4, "10 sec"), (5, "12 sec"), (6, "14 sec"), (7, "16 sec"), (8, "18 sec"), (9, "20 sec"), (10, "Hold")] } },  // Scan Band B Pause Timer
    SF { key: "scan-resume-timer-a", byte: 0x03C9D7, kind: SK::Enum { width: 1, labels: &[(0, "0 sec"), (1, "1 sec"), (2, "2 sec"), (3, "3 sec"), (4, "4 sec"), (5, "5 sec"), (6, "Hold")] } },  // Scan Band A Resume Timer
    SF { key: "scan-resume-timer-b", byte: 0x03C9D8, kind: SK::Enum { width: 1, labels: &[(0, "0 sec"), (1, "1 sec"), (2, "2 sec"), (3, "3 sec"), (4, "4 sec"), (5, "5 sec"), (6, "Hold")] } },  // Scan Band B Resume Timer
    SF { key: "wx-alert-band-a", byte: 0x03C9DA, kind: SK::Bool },  // Wx Alert Band A
    SF { key: "wx-alert-band-b", byte: 0x03C9DB, kind: SK::Bool },  // Wx Alert Band B  // P
    SF { key: "scan-band-a-program-skip", byte: 0x03C9DC, kind: SK::Bool },  // Scan Band A Program Skip
    SF { key: "scan-band-b-program-skip", byte: 0x03C9DD, kind: SK::Bool },  // Scan Band B Program Skip
    SF { key: "dup-check-mr-scan", byte: 0x03C9DE, kind: SK::Bool },  // DUP check MR Scan
    SF { key: "select-group-range", byte: 0x03C9E1, kind: SK::Enum { width: 1, labels: &[(0, "Current Group"), (1, "All Groups")] } },  // Select Group Range
    SF { key: "busy-led", byte: 0x03C9E2, kind: SK::Bool },  // Busy LED
    SF { key: "backlight", byte: 0x03C9E4, kind: SK::Enum { width: 1, labels: &[(0, "Off"), (1, "On"), (2, "Auto"), (3, "Auto(DC IN)")] } },  // Backlight
    SF { key: "voltage-indication", byte: 0x03C9E5, kind: SK::Bool },  // Voltage Indication
    SF { key: "brightness", byte: 0x03C9E6, kind: SK::Enum { width: 1, labels: &[(0, "1"), (1, "2"), (2, "3"), (3, "4"), (4, "5"), (5, "6"), (6, "7"), (7, "8")] } },  // Brightness
    SF { key: "tx-callsign-display", byte: 0x03C9E8, kind: SK::Enum { width: 1, labels: &[(0, "Off"), (1, "Your"), (2, "My")] } },  // TX Callsign Display
    SF { key: "rx-position-display", byte: 0x03C9EA, kind: SK::Enum { width: 1, labels: &[(0, "Off"), (1, "On(Main/Sub)"), (2, "On(Main Only)")] } },  // Rx Position Display
    SF { key: "rx-position-timer", byte: 0x03C9EB, kind: SK::Enum { width: 1, labels: &[(0, "5s"), (1, "10s"), (2, "15s"), (3, "30s"), (4, "Hold")] } },  // Rx Position Timer
    SF { key: "scroll-speed", byte: 0x03C9ED, kind: SK::Enum { width: 1, labels: &[(0, "Slow"), (1, "Fast")] } },  // Scroll Speed
    SF { key: "opening-message", byte: 0x03C9EE, kind: SK::Bool },  // Opening Message
    SF { key: "language-display", byte: 0x03C9EF, kind: SK::Enum { width: 1, labels: &[(0, "English"), (1, "Japanese")] } },  // Language (Display)
    SF { key: "language-system", byte: 0x03C9F0, kind: SK::Enum { width: 1, labels: &[(0, "English"), (1, "Japanese")] } },  // Language (System)
    SF { key: "single-band-display", byte: 0x03C9F1, kind: SK::Enum { width: 1, labels: &[(0, "Date"), (1, "GPS Information")] } },  // Single Band Display
    SF { key: "background-color", byte: 0x03C9F2, kind: SK::Enum { width: 1, labels: &[(1, "White")] } },  // Background Color
    SF { key: "standby-beep", byte: 0x03C9F6, kind: SK::Enum { width: 1, labels: &[(0, "Off"), (1, "On"), (2, "On(to me:High Tone)"), (3, "On(to me:Alarm)")] } },  // Standby Beep
    SF { key: "scope-af-output", byte: 0x03C9F9, kind: SK::Bool },  // Scope AF Output
    SF { key: "emr-af-level", byte: 0x03C9FA, kind: SK::Uint { width: 1 } },  // EMR AF Level
    SF { key: "latitude-longitude", byte: 0x03C9FB, kind: SK::Enum { width: 1, labels: &[(0, "ddd°mm.mm"), (1, "ddd°mm'ss"), (2, "ddd.dddd°")] } },  // Latitude/Longitude
    SF { key: "altitude-distance", byte: 0x03C9FC, kind: SK::Enum { width: 1, labels: &[(0, "m"), (1, "ft/mi")] } },  // Altitude/Distance
    SF { key: "gps-out-usb-port", byte: 0x03C9FD, kind: SK::Bool },  // GPS Out (USB Port)
    SF { key: "sbas", byte: 0x03C9FE, kind: SK::Bool },  // SBAS
    SF { key: "glonass", byte: 0x03C9FF, kind: SK::Bool },  // GLONASS
    SF { key: "power-save-gps", byte: 0x03CA00, kind: SK::Enum { width: 1, labels: &[(0, "OFF"), (1, "1/2/4/8min"), (5, "/2/3/4 Auto")] } },  // Power Save (GPS)
    SF { key: "satellite-information-out", byte: 0x03CA01, kind: SK::Enum { width: 1, labels: &[(0, "GPS/QZSS/GLONASS"), (1, "GPS Only")] } },  // Satellite Information Out
    SF { key: "alarm-area-rx-mem", byte: 0x03CA02, kind: SK::Enum { width: 1, labels: &[(0, "Limited"), (1, "Extended"), (2, "Both")] } },  // Alarm Area (Rx/Mem)
    SF { key: "gps-pos-display-select", byte: 0x03CA03, kind: SK::Enum { width: 1, labels: &[(0, "Latest"), (1, "MAIN"), (2, "SUB")] } },  // GPS Pos Display Select
    SF { key: "compass-direction", byte: 0x03CA04, kind: SK::Enum { width: 1, labels: &[(0, "Heading Up"), (1, "North Up"), (2, "South Up")] } },  // Compass Direction
    SF { key: "gps-select", byte: 0x03CA06, kind: SK::Enum { width: 1, labels: &[(0, "OFF"), (1, "ON"), (2, "<legacy>"), (3, "Manual")] } },  // GPS Select
    SF { key: "gps-time-correct", byte: 0x03CA07, kind: SK::Enum { width: 1, labels: &[(0, "Off"), (1, "Auto")] } },  // GPS Time Correct
    SF { key: "display-type", byte: 0x03CA09, kind: SK::Enum { width: 1, labels: &[(3, "Freq(Large Name)")] } },  // Display Type
    SF { key: "speed", byte: 0x03CA0C, kind: SK::Enum { width: 1, labels: &[(0, "km/h"), (1, "mph"), (2, "knots")] } },  // Speed
    SF { key: "gps-logger", byte: 0x03CA11, kind: SK::Bool },  // GPS Logger
    SF { key: "rx-bass", byte: 0x03CA13, kind: SK::Enum { width: 1, labels: &[(0, "Cut"), (1, "Normal"), (2, "Boost")] } },  // RX Bass  // P
    SF { key: "rx-treble", byte: 0x03CA14, kind: SK::Enum { width: 1, labels: &[(0, "Cut"), (1, "Normal"), (2, "Boost")] } },  // RX Treble  // P
    SF { key: "rx-bass-boost", byte: 0x03CA15, kind: SK::Bool },  // RX Bass Boost
    SF { key: "tx-bass", byte: 0x03CA16, kind: SK::Enum { width: 1, labels: &[(0, "Cut"), (1, "Normal"), (2, "Boost")] } },  // TX Bass  // P
    SF { key: "tx-treble", byte: 0x03CA17, kind: SK::Enum { width: 1, labels: &[(0, "Cut"), (1, "Normal"), (2, "Boost")] } },  // TX Treble  // P
    SF { key: "rx-call-sign-speech", byte: 0x03CA18, kind: SK::Enum { width: 1, labels: &[(0, "OFF"), (1, "ON(Kerchunk)"), (2, "ON(All)")] } },  // RX Call Sign SPEECH
    SF { key: "rx-to-cs-speech", byte: 0x03CA19, kind: SK::Bool },  // RX>CS SPEECH
    SF { key: "dial-speech", byte: 0x03CA1A, kind: SK::Bool },  // DIAL SPEECH
    SF { key: "mode-speech", byte: 0x03CA1B, kind: SK::Bool },  // MODE SPEECH
    SF { key: "speech-language", byte: 0x03CA1C, kind: SK::Enum { width: 1, labels: &[(0, "English"), (1, "Japanese")] } },  // SPEECH Language
    SF { key: "alphabet", byte: 0x03CA1D, kind: SK::Enum { width: 1, labels: &[(0, "Normal"), (1, "Phonetic Code")] } },  // Alphabet
    SF { key: "speech-speed", byte: 0x03CA1E, kind: SK::Enum { width: 1, labels: &[(0, "Slow"), (1, "Fast")] } },  // SPEECH Speed
    SF { key: "speech-level", byte: 0x03CA1F, kind: SK::Uint { width: 1 } },  // SPEECH Level
    SF { key: "record-interval", byte: 0x03CA22, kind: SK::Enum { width: 1, labels: &[(0, "1s"), (1, "5s"), (2, "10s"), (3, "30s"), (4, "1m"), (5, "5m"), (6, "10m")] } },  // Record Interval
    SF { key: "sub-band-mute", byte: 0x03CA23, kind: SK::Enum { width: 1, labels: &[(0, "Off"), (1, "Mute"), (2, "Beep"), (3, "Mute&Beep")] } },  // Sub Band Mute
    SF { key: "scan-band-a-temporary-timer", byte: 0x03CA24, kind: SK::Enum { width: 1, labels: &[(0, "5 minutes"), (4, "While Powered")] } },  // Scan Band A Temporary Timer
    SF { key: "volume-select", byte: 0x03CA26, kind: SK::Enum { width: 1, labels: &[(0, "All"), (1, "BC Radio Separate"), (2, "Separate")] } },  // Volume Select
    SF { key: "qso-log", byte: 0x03CA30, kind: SK::Bool },  // QSO Log
    SF { key: "rx-history-log", byte: 0x03CA31, kind: SK::Bool },  // RX History Log  // P
    SF { key: "csv-separator-qso", byte: 0x03CA32, kind: SK::Enum { width: 1, labels: &[(0, "Sep [,] Dec [.]"), (1, "Sep [;] Dec [.]"), (2, "Sep [;] Dec [,]")] } },  // CSV Separator (QSO)
    SF { key: "csv-date", byte: 0x03CA33, kind: SK::Enum { width: 1, labels: &[(0, "yyyy/mm/dd"), (1, "mm/dd/yyyy"), (2, "dd/mm/yyyy")] } },  // CSV Date
    SF { key: "remote-mic-rx-a", byte: 0x03CA3D, kind: SK::Enum { width: 1, labels: &[(1, "Up"), (2, "Down"), (8, "Monitor (Hold)"), (9, "Call"), (25, "Dup"), (27, "MW"), (28, "Record")] } },  // Remote Mic Rx [A]
    SF { key: "remote-mic-rx-b", byte: 0x03CA3E, kind: SK::Enum { width: 1, labels: &[(1, "Up"), (2, "Down"), (8, "Monitor (Hold)"), (9, "Call"), (25, "Dup"), (27, "MW"), (28, "Record")] } },  // Remote Mic Rx [B]
    SF { key: "remote-mic-rx-up", byte: 0x03CA3F, kind: SK::Enum { width: 1, labels: &[(1, "Up"), (2, "Down"), (8, "Monitor (Hold)"), (9, "Call"), (25, "Dup"), (27, "MW"), (28, "Record")] } },  // Remote Mic Rx [UP]
    SF { key: "remote-mic-rx-down", byte: 0x03CA40, kind: SK::Enum { width: 1, labels: &[(1, "Up"), (2, "Down"), (8, "Monitor (Hold)"), (9, "Call"), (25, "Dup"), (27, "MW"), (28, "Record")] } },  // Remote Mic Rx [DOWN]
    SF { key: "remote-mic-tx-a", byte: 0x03CA44, kind: SK::Enum { width: 1, labels: &[(0, "-----"), (1, "Vol Up"), (2, "Vol Down"), (3, "Voice Tx"), (4, "T-Call")] } },  // Remote Mic Tx [A]
    SF { key: "remote-mic-tx-b", byte: 0x03CA45, kind: SK::Enum { width: 1, labels: &[(0, "-----"), (1, "Vol Up"), (2, "Vol Down"), (3, "Voice Tx"), (4, "T-Call")] } },  // Remote Mic Tx [B]
    SF { key: "remote-mic-tx-up", byte: 0x03CA46, kind: SK::Enum { width: 1, labels: &[(0, "-----"), (1, "Vol Up"), (2, "Vol Down"), (3, "Voice Tx"), (4, "T-Call")] } },  // Remote Mic Tx [UP]
    SF { key: "remote-mic-tx-down", byte: 0x03CA47, kind: SK::Enum { width: 1, labels: &[(0, "-----"), (1, "Vol Up"), (2, "Vol Down"), (3, "Voice Tx"), (4, "T-Call")] } },  // Remote Mic Tx [DOWN]
    SF { key: "heterodyne", byte: 0x03CA4C, kind: SK::Enum { width: 1, labels: &[(0, "Normal"), (1, "Reverse")] } },  // Heterodyne
    SF { key: "charging-power-on", byte: 0x03CA4D, kind: SK::Bool },  // Charging (Power ON)
    SF { key: "usb-power-input", byte: 0x03CA4E, kind: SK::Bool },  // USB Power Input
    SF { key: "tx-delay-ptt", byte: 0x03CA50, kind: SK::Uint { width: 1 } },  // Tx Delay (PTT)
    SF { key: "display-type-rx-history", byte: 0x03CA52, kind: SK::Enum { width: 1, labels: &[(0, "Callsign"), (1, "Name")] } },  // Display Type (Rx History)
    SF { key: "temperature", byte: 0x03CA53, kind: SK::Enum { width: 1, labels: &[(0, "°C"), (1, "°F")] } },  // Temperature
    SF { key: "barometric", byte: 0x03CA54, kind: SK::Enum { width: 1, labels: &[(0, "hPa")] } },  // Barometric
    SF { key: "rainfall", byte: 0x03CA55, kind: SK::Enum { width: 1, labels: &[(0, "mm"), (1, "inch")] } },  // Rainfall
    SF { key: "wind-speed", byte: 0x03CA56, kind: SK::Enum { width: 1, labels: &[(0, "km/h"), (1, "mph"), (2, "knots")] } },  // Wind Speed
    SF { key: "csv-separator", byte: 0x03CA58, kind: SK::Enum { width: 1, labels: &[(0, "Sep [,] Dec [.]"), (1, "Sep [;] Dec [.]"), (2, "Sep [;] Dec [,]")] } },  // CSV Separator
    SF { key: "csv-date-format", byte: 0x03CA59, kind: SK::Enum { width: 1, labels: &[(0, "yyyy/mm/dd"), (1, "mm/dd/yyyy"), (2, "dd/mm/yyyy")] } },  // CSV Date Format
    SF { key: "record-sentence-gga", byte: 0x03CA5A, kind: SK::BoolBit { shift: 6 } },  // Record Sentence GGA
    SF { key: "record-sentence-gsa", byte: 0x03CA5A, kind: SK::BoolBit { shift: 4 } },  // Record Sentence GSA
    SF { key: "record-sentence-rmc", byte: 0x03CA5A, kind: SK::BoolBit { shift: 7 } },  // Record Sentence RMC
    SF { key: "record-sentence-vtg", byte: 0x03CA5A, kind: SK::BoolBit { shift: 5 } },  // Record Sentence VTG
    SF { key: "rx-to-cs-key", byte: 0x03CA5B, kind: SK::Enum { width: 1, labels: &[(0, "Callsign Capture"), (1, "RX>CS List")] } },  // RX>CS Key
    SF { key: "bluetooth-on", byte: 0x03CA5C, kind: SK::Bool },  // Bluetooth ON
    SF { key: "bluetooth-auto-connect", byte: 0x03CA5D, kind: SK::Bool },  // Bluetooth Auto Connect
    SF { key: "headset-af-output", byte: 0x03CA5E, kind: SK::Enum { width: 1, labels: &[(0, "Headset Only"), (1, "Headset & Speaker")] } },  // Headset AF Output
    SF { key: "icom-headset-power-save", byte: 0x03CA5F, kind: SK::Bool },  // Icom Headset Power Save
    SF { key: "icom-headset-one-touch-ptt", byte: 0x03CA60, kind: SK::Bool },  // Icom Headset One-Touch PTT
    SF { key: "icom-headset-ptt-beep", byte: 0x03CA61, kind: SK::Bool },  // Icom Headset PTT Beep
    SF { key: "icom-headset-custom-key-beep", byte: 0x03CA62, kind: SK::Bool },  // Icom Headset Custom Key Beep
    SF { key: "headset-function-select", byte: 0x03CA63, kind: SK::Enum { width: 1, labels: &[(0, "Normal"), (2, "PTT")] } },  // Headset Function Select
    SF { key: "ci-v-transceive-address", byte: 0x03CA64, kind: SK::Uint { width: 1 } },  // CI-V Transceive Address
    SF { key: "headset-rx-priority", byte: 0x03CA65, kind: SK::Enum { width: 1, labels: &[(0, "DV Fast Data"), (2, "Main Band")] } },  // Headset RX Priority
    SF { key: "headset-auto-disconnect", byte: 0x03CA66, kind: SK::Enum { width: 1, labels: &[(0, "Off"), (6, "5 seconds")] } },  // Headset Auto Disconnect
    SF { key: "headset-vox", byte: 0x03CA67, kind: SK::Bool },  // Headset VOX
    SF { key: "headset-vox-level", byte: 0x03CA68, kind: SK::Uint { width: 1 } },  // Headset VOX Level
    SF { key: "headset-vox-delay", byte: 0x03CA69, kind: SK::Uint { width: 1 } },  // Headset VOX Delay
    SF { key: "headset-vox-time-out-timer", byte: 0x03CA6A, kind: SK::Enum { width: 1, labels: &[(0, "Off"), (1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5"), (6, "10"), (7, "15 min")] } },  // Headset VOX Time Out
    SF { key: "usb-serialport", byte: 0x03CA6C, kind: SK::Enum { width: 1, labels: &[(0, "CI-V Echo Off"), (1, "Echo On"), (2, "DV Data")] } },  // USB Serialport
    SF { key: "bluetooth-serialport-function", byte: 0x03CA6D, kind: SK::Enum { width: 1, labels: &[(0, "CI-V Echo Off"), (2, "DV Data")] } },  // Bluetooth Serialport Function
    SF { key: "screen-capture-power-key", byte: 0x03CA7A, kind: SK::Bool },  // Screen Capture [POWER] Key
    SF { key: "screen-capture-filetype", byte: 0x03CA7B, kind: SK::Enum { width: 1, labels: &[(0, "PNG"), (1, "BMP")] } },  // Screen Capture FileType
    SF { key: "lo-call-key", byte: 0x03CA7C, kind: SK::Enum { width: 1, labels: &[(0, "Standard"), (1, "ID-51")] } },  // LO/Call Key
    SF { key: "battery-pack-confirmation", byte: 0x03CA7D, kind: SK::Bool },  // Battery Pack Confirmation
    SF { key: "dim-screen", byte: 0x03CA7E, kind: SK::Bool },  // Dim Screen
    SF { key: "dim-timer", byte: 0x03CA7F, kind: SK::Enum { width: 1, labels: &[(0, "1"), (1, "2"), (2, "5"), (3, "10 min"), (4, "Hold")] } },  // Dim Timer
    SF { key: "brightness-dim", byte: 0x03CA80, kind: SK::Enum { width: 1, labels: &[(0, "1"), (1, "2"), (2, "3"), (3, "4"), (4, "5"), (5, "6"), (6, "7"), (7, "8")] } },  // Brightness (Dim)
    SF { key: "contrast", byte: 0x03CA81, kind: SK::Enum { width: 1, labels: &[(0, "Light"), (1, "Standard"), (2, "Dark")] } },  // Contrast
    SF { key: "scope-waterfall-function", byte: 0x03CA83, kind: SK::Bool },  // Scope Waterfall Function
    SF { key: "scope-waterfall-speed", byte: 0x03CA84, kind: SK::Enum { width: 1, labels: &[(0, "Slow"), (1, "Fast")] } },  // Scope Waterfall Speed
    SF { key: "scope-displayed-steps", byte: 0x03CA87, kind: SK::Enum { width: 1, labels: &[(0, "±15"), (1, "±20")] } },  // Scope Displayed Steps
    SF { key: "vhf-tx-power", byte: 0x03CA91, kind: SK::Enum { width: 1, labels: &[(4, "High")] } },  // VHF Tx Power
    SF { key: "uhf-tx-power", byte: 0x03CA92, kind: SK::Enum { width: 1, labels: &[(1, "LO1"), (4, "High")] } },  // UHF Tx Power
    SF { key: "squelch-a", byte: 0x03CA99, kind: SK::Enum { width: 1, labels: &[(0, "Open"), (1, "Auto"), (2, "1"), (3, "2"), (4, "3"), (5, "4"), (6, "5"), (7, "6"), (8, "7"), (9, "8"), (10, "9")] } },  // Squelch A
    SF { key: "squelch-b", byte: 0x03CA9A, kind: SK::Enum { width: 1, labels: &[(0, "Open"), (1, "Auto"), (2, "1"), (3, "2"), (4, "3"), (5, "4"), (6, "5"), (7, "6"), (8, "7"), (9, "8"), (10, "9")] } },  // Squelch B
    SF { key: "att-band-a", byte: 0x03CAA3, kind: SK::BoolBit { shift: 7 } },  // ATT (Band A)
    SF { key: "att-fm-radio", byte: 0x03CAA3, kind: SK::BoolBit { shift: 6 } },  // ATT (FM Radio)
    SF { key: "alarm-select", byte: 0x03CAAD, kind: SK::Enum { width: 1, labels: &[(0, "OFF"), (1, "RX"), (2, "Group"), (3, "Memory")] } },  // Alarm Select
    SF { key: "alarm-area-group", byte: 0x03CAB1, kind: SK::Uint { width: 2 } },  // Alarm Area (Group)
    SF { key: "utc-offset-minutes", byte: 0x03CAB3, kind: SK::Int { width: 2 } },  // UTC Offset
    SF { key: "wx-channel-a", byte: 0x03E932, kind: SK::Uint { width: 1 } },  // Wx channel A / B
    SF { key: "wx-channel-b", byte: 0x03E933, kind: SK::Uint { width: 1 } },  // Wx channel A / B
    SF { key: "fix-air", byte: 0x03E990, kind: SK::Uint { width: 4 } },  // FIX Air
    SF { key: "fix-vhf", byte: 0x03E995, kind: SK::Uint { width: 4 } },  // FIX VHF
    SF { key: "fix-vhf2", byte: 0x03E99A, kind: SK::Uint { width: 4 } },  // FIX VHF2
    SF { key: "fix-uhf", byte: 0x03E99F, kind: SK::Uint { width: 4 } },  // FIX UHF
];
