//! TH-D75 menu settings: decode from, and apply to, a `.d75` body.
//!
//! Offsets in the generated table are **body** offsets — the file offset minus
//! the 0x100 header — so every function here takes the body slice, not the
//! whole file. That matches how the addresses were measured: `pass.py` reports
//! `body 0x1003` for file byte 0x1103.
//!
//! The field table and the profile form's schema are both generated by
//! `scratchpad/thd75/gen_thd75_table.py` from one measurement sheet, so the
//! decoder and the form cannot drift apart. The tests at the bottom assert that
//! they still agree; do not hand-edit either output.

use serde_json::{Map, Value};

/// One setting: where it lives in the body, and how it is encoded.
pub(crate) struct SF {
    pub key: &'static str,
    /// Offset into the `.d75` **body** (file offset minus 0x100).
    pub byte: u32,
    pub kind: SK,
}

pub(crate) enum SK {
    /// Unsigned integer in one byte. Every measured numeric on this radio holds
    /// its value **raw** — seconds, knots, mph, character counts — with no
    /// scaling, which is why there is no width or endianness to choose here.
    Uint { width: u8 },
    /// Whole 1-byte flag, off = 0 and on = 1.
    Bool,
    /// A single bit inside a shared byte, read-modify-written so the other bits
    /// survive. This radio has **seven** such bytes — LED Control, the two
    /// equalizer groups, the GPS and DV sentence sets, APRS Lock and the APRS
    /// packet filter — and not one of them was predictable from the UI layout.
    BoolBit { shift: u8 },
    /// Enumerated whole-value mapped to a label.
    Enum {
        width: u8,
        labels: &'static [(u32, &'static str)],
    },
    /// Fixed-length ASCII, **NUL-padded**. Not space-padded: a short TH-D75
    /// callsign is followed by zero bytes.
    Text { len: u32 },
}

include!("thd75_settings_table.rs");

fn read_uint(body: &[u8], at: usize, width: u8) -> u32 {
    let mut v: u32 = 0;
    for i in 0..width as usize {
        v = (v << 8) | body[at + i] as u32;
    }
    v
}

/// Map a raw value to its label, or hand back the raw number.
///
/// ⚠ Falling back to the number rather than a label is deliberate and load
/// bearing for the PF keys: all five write into one 56-value function enum of
/// which **six codes belong to functions no PF key can be assigned**. A radio
/// could legitimately hold one, and normalising it to the first label would
/// silently reassign the operator's key on the next write.
fn label_for(labels: &[(u32, &str)], raw: u32) -> Value {
    match labels.iter().find(|(v, _)| *v == raw) {
        Some((_, l)) => Value::String((*l).to_string()),
        None => Value::String(raw.to_string()),
    }
}

fn decode_field(body: &[u8], f: &SF) -> Value {
    let at = f.byte as usize;
    match &f.kind {
        SK::Uint { width } => Value::from(read_uint(body, at, *width)),
        SK::Bool => Value::Bool(body[at] != 0),
        SK::BoolBit { shift } => Value::Bool((body[at] >> shift) & 1 == 1),
        SK::Enum { width, labels } => label_for(labels, read_uint(body, at, *width)),
        SK::Text { len } => {
            let end = (at + *len as usize).min(body.len());
            let raw = &body[at..end];
            let cut = raw.iter().position(|&b| b == 0).unwrap_or(raw.len());
            Value::String(String::from_utf8_lossy(&raw[..cut]).trim_end().to_string())
        }
    }
}

/// Last body byte a field touches, exclusive — keeps a short body from
/// panicking a decode.
fn field_end(f: &SF) -> usize {
    let at = f.byte as usize;
    at + match &f.kind {
        SK::Uint { width } | SK::Enum { width, .. } => *width as usize,
        SK::Bool | SK::BoolBit { .. } => 1,
        SK::Text { len } => *len as usize,
    }
}

/// Decode every known setting out of a `.d75` body, shaped like the profile
/// form. An enum value the table does not know comes back as its raw number
/// rather than a wrong label.
pub(crate) fn decode_settings(body: &[u8]) -> Value {
    let mut out = Map::new();
    for f in THD75_SETTINGS_FIELDS {
        if field_end(f) > body.len() {
            continue;
        }
        out.insert(f.key.to_string(), decode_field(body, f));
    }
    Value::Object(out)
}

/// Write a profile's settings into a `.d75` body, returning how many fields
/// were applied.
///
/// Keys the table does not know, and values of the wrong shape, are **skipped**
/// rather than guessed at: a profile saved against an older schema must not
/// corrupt an image that is about to be written to a real radio.
pub(crate) fn apply_settings(body: &mut [u8], settings: &Map<String, Value>) -> usize {
    let mut written = 0;
    for f in THD75_SETTINGS_FIELDS {
        let Some(v) = settings.get(f.key) else {
            continue;
        };
        if field_end(f) > body.len() {
            continue;
        }
        let at = f.byte as usize;
        let ok = match (&f.kind, v) {
            (SK::Bool, Value::Bool(b)) => {
                body[at] = u8::from(*b);
                true
            }
            // Read-modify-write: the neighbouring bits are other settings.
            (SK::BoolBit { shift }, Value::Bool(b)) => {
                let mask = 1u8 << shift;
                body[at] = (body[at] & !mask) | if *b { mask } else { 0 };
                true
            }
            (SK::Uint { width }, v) => match v.as_u64() {
                Some(n) => write_uint(body, at, *width, n),
                None => false,
            },
            (SK::Enum { width, labels }, Value::String(s)) => {
                // The label is the normal case; a bare number is accepted so a
                // code with no label (see `label_for`) survives a round trip.
                let raw = labels
                    .iter()
                    .find(|(_, l)| l == s)
                    .map(|(v, _)| *v as u64)
                    .or_else(|| s.parse::<u64>().ok());
                match raw {
                    Some(n) => write_uint(body, at, *width, n),
                    None => false,
                }
            }
            (SK::Text { len }, Value::String(s)) => {
                let n = *len as usize;
                // NUL-pad to the FULL field width. Writing only the string and
                // leaving the tail alone would splice the previous value's
                // ending on to a shorter new one.
                let bytes = s.as_bytes();
                for i in 0..n {
                    body[at + i] = bytes.get(i).copied().filter(|b| b.is_ascii()).unwrap_or(0);
                }
                true
            }
            _ => false,
        };
        if ok {
            written += 1;
        }
    }
    written
}

fn write_uint(body: &mut [u8], at: usize, width: u8, v: u64) -> bool {
    let w = width as usize;
    if v > (1u64 << (8 * w)) - 1 {
        return false;
    }
    for i in 0..w {
        body[at + i] = (v >> (8 * (w - 1 - i))) as u8;
    }
    true
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The seeded schema and the decode table come out of the same generator,
    /// so every key must appear in both. A field in one and not the other is
    /// either a form control that writes nothing or a setting nobody can reach.
    #[test]
    fn schema_and_table_cover_the_same_keys() {
        let schema: Vec<Value> =
            serde_json::from_str(crate::seed::THD75_SETTINGS_SCHEMA).expect("schema parses");
        let mut in_schema: Vec<&str> = schema
            .iter()
            .filter(|f| f["type"] != "section")
            .map(|f| f["key"].as_str().expect("key is a string"))
            .collect();
        let mut in_table: Vec<&str> = THD75_SETTINGS_FIELDS.iter().map(|f| f.key).collect();
        in_schema.sort_unstable();
        in_table.sort_unstable();
        assert_eq!(in_schema, in_table);
    }

    /// Every select's options must be exactly the table's labels, in order —
    /// otherwise the form offers a choice the encoder cannot write.
    #[test]
    fn schema_options_match_the_tables_enum_labels() {
        let schema: Vec<Value> =
            serde_json::from_str(crate::seed::THD75_SETTINGS_SCHEMA).expect("schema parses");
        for f in THD75_SETTINGS_FIELDS {
            let SK::Enum { labels, .. } = &f.kind else {
                continue;
            };
            let entry = schema
                .iter()
                .find(|e| e["key"] == f.key)
                .unwrap_or_else(|| panic!("{} is missing from the schema", f.key));
            let opts: Vec<&str> = entry["options"]
                .as_array()
                .unwrap_or_else(|| panic!("{} is not a select in the schema", f.key))
                .iter()
                .map(|o| o.as_str().expect("option is a string"))
                .collect();
            let want: Vec<&str> = labels.iter().map(|(_, l)| *l).collect();
            assert_eq!(opts, want, "options drifted for {}", f.key);
        }
    }

    /// No two fields may claim the same byte unless they are bits of it. A
    /// plain overlap means one setting silently overwrites another.
    #[test]
    fn no_two_whole_byte_fields_share_a_byte() {
        let mut claimed: Vec<(usize, &str)> = Vec::new();
        for f in THD75_SETTINGS_FIELDS {
            if matches!(f.kind, SK::BoolBit { .. }) {
                continue;
            }
            for b in f.byte as usize..field_end(f) {
                if let Some((_, other)) = claimed.iter().find(|(x, _)| *x == b) {
                    panic!("{:#07x}: {} overlaps {}", b, f.key, other);
                }
                claimed.push((b, f.key));
            }
        }
    }

    /// Bits sharing a byte must be distinct, and must not collide with a whole
    /// byte field. The packet filter packs seven settings into 0x1366.
    #[test]
    fn bitfields_do_not_collide() {
        let mut seen: Vec<(u32, u8, &str)> = Vec::new();
        for f in THD75_SETTINGS_FIELDS {
            let SK::BoolBit { shift } = f.kind else {
                continue;
            };
            if let Some((_, _, other)) = seen.iter().find(|(b, s, _)| *b == f.byte && *s == shift) {
                panic!("{:#07x} bit {}: {} collides with {}", f.byte, shift, f.key, other);
            }
            seen.push((f.byte, shift, f.key));
        }
    }

    /// A bool round-trips, and a bit written into a shared byte leaves its
    /// neighbours alone — the property the packet filter depends on.
    #[test]
    fn applying_a_bit_preserves_the_rest_of_its_byte() {
        let mut body = vec![0u8; 0x2000];
        body[0x1366] = 0b0111_1111; // all seven packet filters on
        let mut m = Map::new();
        m.insert("packet-filter-type-digi".into(), Value::Bool(false));
        assert_eq!(apply_settings(&mut body, &m), 1);
        assert_eq!(body[0x1366], 0b0111_1101, "only bit 1 should have cleared");
    }

    /// A shorter string must not leave the tail of the previous one behind.
    #[test]
    fn text_is_nul_padded_to_the_full_field() {
        let mut body = vec![0u8; 0x2000];
        let mut m = Map::new();
        m.insert("aprs-my-callsign".into(), Value::String("N0CALL-15".into()));
        assert_eq!(apply_settings(&mut body, &m), 1);
        assert_eq!(&body[0x1200..0x1209], b"N0CALL-15");

        m.insert("aprs-my-callsign".into(), Value::String("WW8L".into()));
        apply_settings(&mut body, &m);
        assert_eq!(&body[0x1200..0x1209], b"WW8L\0\0\0\0\0");
    }

    /// An enum code with no label survives a decode/apply round trip. The PF
    /// keys have six such codes.
    #[test]
    fn an_unlabelled_enum_code_round_trips() {
        let mut body = vec![0u8; 0x2000];
        body[0x107c] = 43; // a function no PF key combo offers
        let decoded = decode_settings(&body);
        let v = decoded["pf1-key-mic"].clone();
        assert_eq!(v, Value::String("43".into()));

        let mut m = Map::new();
        m.insert("pf1-key-mic".into(), v);
        assert_eq!(apply_settings(&mut body, &m), 1);
        assert_eq!(body[0x107c], 43, "the unknown code must not be normalised");
    }

    /// An enum must label its whole range, not just its ends.
    ///
    /// The generator writes a measured range as `First=0 … Last=N` and lets the
    /// manual supply the middle. Until s108 that form was ALSO matched by the
    /// parser for fully-spelled-out enums, which returned just the two
    /// endpoints -- so Time-out Timer shipped 2 options instead of 11, and ten
    /// fields in all lost their middles. Nothing failed: the table compiled,
    /// the schema agreed with it, and the form simply could not express most of
    /// each range.
    ///
    /// A hole is the signature, so this looks for holes. The generator is not
    /// in this repo (it lives in a gitignored scratchpad), which is exactly why
    /// the guard has to be here.
    #[test]
    fn enum_labels_cover_their_whole_range() {
        // The codes that are deliberately not contiguous, each measured:
        //   digital-auto-reply stores Off as 0xff, not as an index
        //   the five PF keys share one 56-value function enum, and six of its
        //   codes belong to functions no key can be assigned
        let sentinels = ["digital-auto-reply"];
        let pf = |k: &str| k.starts_with("pf") && k.contains("-key");

        for f in THD75_SETTINGS_FIELDS {
            let SK::Enum { labels, .. } = &f.kind else {
                continue;
            };
            if sentinels.contains(&f.key) || pf(f.key) {
                continue;
            }
            let mut codes: Vec<u32> = labels.iter().map(|(v, _)| *v).collect();
            codes.sort_unstable();
            let (lo, hi) = (codes[0], *codes.last().unwrap());
            assert_eq!(
                codes.len() as u32,
                hi - lo + 1,
                "{}: codes {lo}..={hi} but only {} labels -- an enum with a hole                  in it cannot express the values the radio actually stores",
                f.key,
                codes.len()
            );
        }
    }
}
