//! TH-D75 menu settings: decode from, and apply to, a `.d75` body.
//!
//! Offsets in the generated table are **body** offsets — the file offset minus
//! the 0x100 header — so every function here takes the body slice, not the
//! whole file. That matches how the addresses were measured: `pass.py` reports
//! `body 0x1003` for file byte 0x1103.
//!
//! The field table and the profile form's schema are both generated by
//! `scratchpad/thd75/gen_thd75_table.py` from one measurement sheet, so the
//! decoder and the form cannot drift apart. The tests at the bottom assert that
//! they still agree; do not hand-edit either output.

use serde_json::{Map, Value};

/// One setting: where it lives in the body, and how it is encoded.
pub(crate) struct SF {
    pub key: &'static str,
    /// Offset into the `.d75` **body** (file offset minus 0x100).
    pub byte: u32,
    pub kind: SK,
}

pub(crate) enum SK {
    /// Unsigned integer in one byte. Every measured numeric on this radio holds
    /// its value **raw** — seconds, knots, mph, character counts — with no
    /// scaling, which is why there is no width or endianness to choose here.
    Uint { width: u8 },
    /// Whole 1-byte flag, off = 0 and on = 1.
    Bool,
    /// A single bit inside a shared byte, read-modify-written so the other bits
    /// survive. This radio has **seven** such bytes — LED Control, the two
    /// equalizer groups, the GPS and DV sentence sets, APRS Lock and the APRS
    /// packet filter — and not one of them was predictable from the UI layout.
    BoolBit { shift: u8 },
    /// Enumerated whole-value mapped to a label.
    Enum {
        width: u8,
        labels: &'static [(u32, &'static str)],
    },
    /// Fixed-length ASCII, **NUL-padded**. Not space-padded: a short TH-D75
    /// callsign is followed by zero bytes.
    Text { len: u32 },
    /// Unsigned integer stored **little-endian**. The whole rest of this radio
    /// is big-endian or single-byte; the one exception measured so far is the
    /// beacon objects' latitude and longitude fraction, where `12°34.5600'`
    /// stores 5600 as `e0 15`. Kept as its own kind rather than a flag on
    /// `Uint` so that a row cannot pick the wrong endianness by omission.
    UintLe { width: u8 },
}

include!("thd75_settings_table.rs");

fn read_uint_le(body: &[u8], at: usize, width: u8) -> u32 {
    let mut v: u32 = 0;
    for i in (0..width as usize).rev() {
        v = (v << 8) | body[at + i] as u32;
    }
    v
}

fn read_uint(body: &[u8], at: usize, width: u8) -> u32 {
    let mut v: u32 = 0;
    for i in 0..width as usize {
        v = (v << 8) | body[at + i] as u32;
    }
    v
}

/// Map a raw value to its label, or hand back the raw number.
///
/// ⚠ Falling back to the number rather than a label is deliberate and load
/// bearing for the PF keys: all five write into one 56-value function enum of
/// which **six codes belong to functions no PF key can be assigned**. A radio
/// could legitimately hold one, and normalising it to the first label would
/// silently reassign the operator's key on the next write.
fn label_for(labels: &[(u32, &str)], raw: u32) -> Value {
    match labels.iter().find(|(v, _)| *v == raw) {
        Some((_, l)) => Value::String((*l).to_string()),
        None => Value::String(raw.to_string()),
    }
}

fn decode_field(body: &[u8], f: &SF) -> Value {
    let at = f.byte as usize;
    match &f.kind {
        SK::Uint { width } => Value::from(read_uint(body, at, *width)),
        SK::UintLe { width } => Value::from(read_uint_le(body, at, *width)),
        SK::Bool => Value::Bool(body[at] != 0),
        SK::BoolBit { shift } => Value::Bool((body[at] >> shift) & 1 == 1),
        SK::Enum { width, labels } => label_for(labels, read_uint(body, at, *width)),
        SK::Text { len } => {
            let end = (at + *len as usize).min(body.len());
            let raw = &body[at..end];
            // ⚠ 0xff terminates as surely as NUL. A record in one of the APRS
            // grids that the operator has never filled in is 0xff all through,
            // and cutting only at NUL rendered all 42 bytes of it as mojibake
            // in the form. No text field here is anything but 7-bit ASCII, so
            // neither byte can be part of a real value.
            let cut = raw
                .iter()
                .position(|&b| b == 0 || b == 0xff)
                .unwrap_or(raw.len());
            Value::String(String::from_utf8_lossy(&raw[..cut]).trim_end().to_string())
        }
    }
}

/// Last body byte a field touches, exclusive — keeps a short body from
/// panicking a decode.
fn field_end(f: &SF) -> usize {
    let at = f.byte as usize;
    at + match &f.kind {
        SK::Uint { width } | SK::UintLe { width } | SK::Enum { width, .. } => *width as usize,
        SK::Bool | SK::BoolBit { .. } => 1,
        SK::Text { len } => *len as usize,
    }
}

/// Decode every known setting out of a `.d75` body, shaped like the profile
/// form. An enum value the table does not know comes back as its raw number
/// rather than a wrong label.
pub(crate) fn decode_settings(body: &[u8]) -> Value {
    let mut out = Map::new();
    for f in THD75_SETTINGS_FIELDS {
        if field_end(f) > body.len() {
            continue;
        }
        out.insert(f.key.to_string(), decode_field(body, f));
    }
    Value::Object(out)
}

/// Write a profile's settings into a `.d75` body, returning how many fields
/// were applied.
///
/// Keys the table does not know, and values of the wrong shape, are **skipped**
/// rather than guessed at: a profile saved against an older schema must not
/// corrupt an image that is about to be written to a real radio.
pub(crate) fn apply_settings(body: &mut [u8], settings: &Map<String, Value>) -> usize {
    let mut written = 0;
    for f in THD75_SETTINGS_FIELDS {
        let Some(v) = settings.get(f.key) else {
            continue;
        };
        if field_end(f) > body.len() {
            continue;
        }
        let at = f.byte as usize;
        let ok = match (&f.kind, v) {
            (SK::Bool, Value::Bool(b)) => {
                body[at] = u8::from(*b);
                true
            }
            // Read-modify-write: the neighbouring bits are other settings.
            (SK::BoolBit { shift }, Value::Bool(b)) => {
                let mask = 1u8 << shift;
                body[at] = (body[at] & !mask) | if *b { mask } else { 0 };
                true
            }
            (SK::Uint { width }, v) => match v.as_u64() {
                Some(n) => write_uint(body, at, *width, n),
                None => false,
            },
            (SK::UintLe { width }, v) => match v.as_u64() {
                Some(n) => write_uint_le(body, at, *width, n),
                None => false,
            },
            (SK::Enum { width, labels }, Value::String(s)) => {
                // The label is the normal case; a bare number is accepted so a
                // code with no label (see `label_for`) survives a round trip.
                let raw = labels
                    .iter()
                    .find(|(_, l)| l == s)
                    .map(|(v, _)| *v as u64)
                    .or_else(|| s.parse::<u64>().ok());
                match raw {
                    Some(n) => write_uint(body, at, *width, n),
                    None => false,
                }
            }
            (SK::Text { len }, Value::String(s)) => {
                let n = *len as usize;
                // Writing an empty value over a field that ALREADY reads as
                // empty would change only its padding, which is a change the
                // operator did not ask for -- the same reason a card radio's
                // form seeds blank rather than with defaults. Untouched rows
                // in the APRS grids are 0xff, sometimes 0xff then NUL, so
                // testing the decoded value rather than the byte pattern is
                // what actually covers them. Clearing a field that holds real
                // text still NUL-fills, because it does not read as empty.
                let already_empty = body[at..at + n]
                    .iter()
                    .take_while(|&&b| b != 0 && b != 0xff)
                    .next()
                    .is_none();
                if s.is_empty() && already_empty {
                    true
                } else {
                    // NUL-pad to the FULL field width. Writing only the string
                    // and leaving the tail alone would splice the previous
                    // value's ending on to a shorter new one.
                    let bytes = s.as_bytes();
                    for i in 0..n {
                        body[at + i] =
                            bytes.get(i).copied().filter(|b| b.is_ascii()).unwrap_or(0);
                    }
                    true
                }
            }
            _ => false,
        };
        if ok {
            written += 1;
        }
    }
    written
}

fn write_uint_le(body: &mut [u8], at: usize, width: u8, v: u64) -> bool {
    let w = width as usize;
    if v > (1u64 << (8 * w)) - 1 {
        return false;
    }
    for i in 0..w {
        body[at + i] = (v >> (8 * i)) as u8;
    }
    true
}

fn write_uint(body: &mut [u8], at: usize, width: u8, v: u64) -> bool {
    let w = width as usize;
    if v > (1u64 << (8 * w)) - 1 {
        return false;
    }
    for i in 0..w {
        body[at + i] = (v >> (8 * (w - 1 - i))) as u8;
    }
    true
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The seeded schema and the decode table come out of the same generator,
    /// so every key must appear in both. A field in one and not the other is
    /// either a form control that writes nothing or a setting nobody can reach.
    #[test]
    fn schema_and_table_cover_the_same_keys() {
        let schema: Vec<Value> =
            serde_json::from_str(crate::seed::THD75_SETTINGS_SCHEMA).expect("schema parses");
        let mut in_schema: Vec<&str> = schema
            .iter()
            .filter(|f| f["type"] != "section")
            .map(|f| f["key"].as_str().expect("key is a string"))
            .collect();
        let mut in_table: Vec<&str> = THD75_SETTINGS_FIELDS.iter().map(|f| f.key).collect();
        in_schema.sort_unstable();
        in_table.sort_unstable();
        assert_eq!(in_schema, in_table);
    }

    /// Every select's options must be exactly the table's labels, in order —
    /// otherwise the form offers a choice the encoder cannot write.
    #[test]
    fn schema_options_match_the_tables_enum_labels() {
        let schema: Vec<Value> =
            serde_json::from_str(crate::seed::THD75_SETTINGS_SCHEMA).expect("schema parses");
        for f in THD75_SETTINGS_FIELDS {
            let SK::Enum { labels, .. } = &f.kind else {
                continue;
            };
            let entry = schema
                .iter()
                .find(|e| e["key"] == f.key)
                .unwrap_or_else(|| panic!("{} is missing from the schema", f.key));
            let opts: Vec<&str> = entry["options"]
                .as_array()
                .unwrap_or_else(|| panic!("{} is not a select in the schema", f.key))
                .iter()
                .map(|o| o.as_str().expect("option is a string"))
                .collect();
            let want: Vec<&str> = labels.iter().map(|(_, l)| *l).collect();
            assert_eq!(opts, want, "options drifted for {}", f.key);
        }
    }

    /// No two fields may claim the same byte unless they are bits of it. A
    /// plain overlap means one setting silently overwrites another.
    #[test]
    fn no_two_whole_byte_fields_share_a_byte() {
        let mut claimed: Vec<(usize, &str)> = Vec::new();
        for f in THD75_SETTINGS_FIELDS {
            if matches!(f.kind, SK::BoolBit { .. }) {
                continue;
            }
            for b in f.byte as usize..field_end(f) {
                if let Some((_, other)) = claimed.iter().find(|(x, _)| *x == b) {
                    panic!("{:#07x}: {} overlaps {}", b, f.key, other);
                }
                claimed.push((b, f.key));
            }
        }
    }

    /// Bits sharing a byte must be distinct, and must not collide with a whole
    /// byte field. The packet filter packs seven settings into 0x1366.
    #[test]
    fn bitfields_do_not_collide() {
        let mut seen: Vec<(u32, u8, &str)> = Vec::new();
        for f in THD75_SETTINGS_FIELDS {
            let SK::BoolBit { shift } = f.kind else {
                continue;
            };
            if let Some((_, _, other)) = seen.iter().find(|(b, s, _)| *b == f.byte && *s == shift) {
                panic!("{:#07x} bit {}: {} collides with {}", f.byte, shift, f.key, other);
            }
            seen.push((f.byte, shift, f.key));
        }
    }

    /// A bool round-trips, and a bit written into a shared byte leaves its
    /// neighbours alone — the property the packet filter depends on.
    #[test]
    fn applying_a_bit_preserves_the_rest_of_its_byte() {
        let mut body = vec![0u8; 0x2000];
        body[0x1366] = 0b0111_1111; // all seven packet filters on
        let mut m = Map::new();
        m.insert("packet-filter-type-digi".into(), Value::Bool(false));
        assert_eq!(apply_settings(&mut body, &m), 1);
        assert_eq!(body[0x1366], 0b0111_1101, "only bit 1 should have cleared");
    }

    /// A shorter string must not leave the tail of the previous one behind.
    #[test]
    fn text_is_nul_padded_to_the_full_field() {
        let mut body = vec![0u8; 0x2000];
        let mut m = Map::new();
        m.insert("aprs-my-callsign".into(), Value::String("N0CALL-15".into()));
        assert_eq!(apply_settings(&mut body, &m), 1);
        assert_eq!(&body[0x1200..0x1209], b"N0CALL-15");

        m.insert("aprs-my-callsign".into(), Value::String("WW8L".into()));
        apply_settings(&mut body, &m);
        assert_eq!(&body[0x1200..0x1209], b"WW8L\0\0\0\0\0");
    }

    /// An enum code with no label survives a decode/apply round trip. The PF
    /// keys have six such codes.
    #[test]
    fn an_unlabelled_enum_code_round_trips() {
        let mut body = vec![0u8; 0x2000];
        body[0x107c] = 43; // a function no PF key combo offers
        let decoded = decode_settings(&body);
        let v = decoded["pf1-key-mic"].clone();
        assert_eq!(v, Value::String("43".into()));

        let mut m = Map::new();
        m.insert("pf1-key-mic".into(), v);
        assert_eq!(apply_settings(&mut body, &m), 1);
        assert_eq!(body[0x107c], 43, "the unknown code must not be normalised");
    }

    /// An enum must label its whole range, not just its ends.
    ///
    /// The generator writes a measured range as `First=0 … Last=N` and lets the
    /// manual supply the middle. Until s108 that form was ALSO matched by the
    /// parser for fully-spelled-out enums, which returned just the two
    /// endpoints -- so Time-out Timer shipped 2 options instead of 11, and ten
    /// fields in all lost their middles. Nothing failed: the table compiled,
    /// the schema agreed with it, and the form simply could not express most of
    /// each range.
    ///
    /// A hole is the signature, so this looks for holes. The generator is not
    /// in this repo (it lives in a gitignored scratchpad), which is exactly why
    /// the guard has to be here.
    #[test]
    fn enum_labels_cover_their_whole_range() {
        // The codes that are deliberately not contiguous, each measured:
        //   digital-auto-reply stores Off as 0xff, not as an index
        //   the five PF keys share one 56-value function enum, and six of its
        //   codes belong to functions no key can be assigned
        let sentinels = ["digital-auto-reply"];
        let pf = |k: &str| k.starts_with("pf") && k.contains("-key");

        for f in THD75_SETTINGS_FIELDS {
            let SK::Enum { labels, .. } = &f.kind else {
                continue;
            };
            if sentinels.contains(&f.key) || pf(f.key) {
                continue;
            }
            let mut codes: Vec<u32> = labels.iter().map(|(v, _)| *v).collect();
            codes.sort_unstable();
            let (lo, hi) = (codes[0], *codes.last().unwrap());
            assert_eq!(
                codes.len() as u32,
                hi - lo + 1,
                "{}: codes {lo}..={hi} but only {} labels -- an enum with a hole                  in it cannot express the values the radio actually stores",
                f.key,
                codes.len()
            );
        }
    }

    /// The beacon object's position, byte for byte, as it was measured.
    ///
    /// `12°34.5600' N` came back from the radio as `0c 22 e0 15` — degrees,
    /// minutes, then the fraction in units of 1/10000 minute stored
    /// **little-endian**, which is the only little-endian value found on this
    /// radio. The hemisphere bits share one byte and were pinned with a mixed
    /// N+W / S+E pair, then confirmed by predicting 0x0c for N+E before
    /// running it. `scratchpad/` is gitignored, so this test is where that
    /// measurement lives.
    #[test]
    fn a_beacon_objects_position_encodes_the_way_the_radio_stores_it() {
        let mut body = vec![0u8; 0x2000];
        let mut s = Map::new();
        s.insert("beacon-object-1-latitude-degrees".into(), Value::from(12));
        s.insert("beacon-object-1-latitude-minutes".into(), Value::from(34));
        s.insert(
            "beacon-object-1-latitude-1-10000-minutes".into(),
            Value::from(5600),
        );
        s.insert("beacon-object-1-latitude-north".into(), Value::Bool(true));
        s.insert("beacon-object-1-longitude-east".into(), Value::Bool(true));
        apply_settings(&mut body, &s);

        assert_eq!(&body[0x1900..0x1904], &[0x0c, 0x22, 0xe0, 0x15]);
        assert_eq!(body[0x1908], 0x0c, "N+E sets bit 3 and bit 2");

        let back = decode_settings(&body);
        assert_eq!(back["beacon-object-1-latitude-1-10000-minutes"], 5600);
        assert_eq!(back["beacon-object-1-latitude-north"], Value::Bool(true));
    }

    /// A grid's rows must land on their own stride, and the row a "Sel" column
    /// appears to tick is stored as ONE index outside the array — checking a
    /// second row moves the choice rather than setting a second flag.
    #[test]
    fn a_grids_rows_are_strided_and_its_selector_is_a_single_index() {
        let mut body = vec![0u8; 0x2000];
        let mut s = Map::new();
        s.insert("status-text-1".into(), Value::from("FIRST"));
        s.insert("status-text-5".into(), Value::from("LAST"));
        s.insert("selected-status-text".into(), Value::from("Status Text 3"));
        apply_settings(&mut body, &s);

        assert_eq!(&body[0x1230..0x1235], b"FIRST");
        assert_eq!(&body[0x1230 + 4 * 0x30..0x1230 + 4 * 0x30 + 4], b"LAST");
        assert_eq!(body[0x122f], 2, "the selector holds an index, not a bitmap");
    }

    /// No enum label may itself be a RANGE. Beep Volume shipped as
    /// `(0, "Vol Link"), (1, "Level 1-7")` — two labels standing in for eight
    /// values, so picking the second wrote 1 and the operator could not reach
    /// Levels 2-7 at all.
    ///
    /// `enum_labels_cover_their_whole_range` cannot see this one: 0 and 1 are
    /// perfectly contiguous. The tell is in the label text, where "1-7" is a
    /// span the sheet wrote and the generator took for a name.
    #[test]
    fn no_enum_label_is_secretly_a_range() {
        // A label may legitimately contain a hyphen ("Economic Low", "1-Way",
        // "Off (AF)"), so this looks only for digit-hyphen-digit, which is how
        // every range in the measurement sheet is written.
        let looks_like_a_range = |l: &str| {
            let b = l.as_bytes();
            // "Level 1-7"
            b.windows(3)
                .any(|w| w[0].is_ascii_digit() && w[1] == b'-' && w[2].is_ascii_digit())
                // "400 - 800", "Off/ 1-Digit - 4-Digit". No option name in this
                // table contains a spaced hyphen; the sheet writes its ranges
                // that way.
                || l.contains(" - ")
        };
        // The guard has to fire on the label it was written for, and stay
        // quiet on the hyphens that are part of a real option name.
        assert!(looks_like_a_range("Level 1-7"), "the shipped bug");
        assert!(looks_like_a_range("Off/ 1-Digit - 4-Digit"));
        assert!(looks_like_a_range("400 - 800"));
        for ok in ["Economic Low", "1-Way", "Off (AF)", "Level 1", "1750 Hz"] {
            assert!(!looks_like_a_range(ok), "false positive on {ok:?}");
        }

        for f in THD75_SETTINGS_FIELDS {
            let SK::Enum { labels, .. } = &f.kind else {
                continue;
            };
            for (v, l) in *labels {
                assert!(
                    !looks_like_a_range(l),
                    "{}: code {v} is labelled {l:?}, which is a RANGE, not one \
                     option — the values between its ends are unreachable",
                    f.key
                );
            }
        }
    }

    /// An untouched row in one of the APRS grids is 0xff all through, not NUL.
    /// It must read as empty, and staying empty must not rewrite it.
    #[test]
    fn an_untouched_grid_row_reads_empty_and_is_left_alone() {
        let mut body = vec![0u8; 0x2000];
        body[0x1500..0x1520].fill(0xff); // user phrase 1, never filled in

        let v = decode_settings(&body);
        assert_eq!(v["user-phrase-1"], "", "0xff is padding, not a character");

        let mut s = Map::new();
        s.insert("user-phrase-1".into(), Value::from(""));
        apply_settings(&mut body, &s);
        assert!(
            body[0x1500..0x1520].iter().all(|&b| b == 0xff),
            "an empty value must not NUL-fill a row the operator never touched"
        );

        // ★ A row can also be 0xff for part of its length and NUL for the
        // rest -- Status Text 5 on the real card is exactly that. It reads as
        // empty, so it must be left alone too. Testing the byte pattern for
        // "all 0xff" missed this and rewrote 16 bytes.
        body[0x1540..0x1550].fill(0xff);
        body[0x1550..0x1560].fill(0);
        let before = body[0x1540..0x1560].to_vec();
        let mut s = Map::new();
        s.insert("user-phrase-3".into(), Value::from(""));
        apply_settings(&mut body, &s);
        assert_eq!(&body[0x1540..0x1560], &before[..], "mixed padding rewritten");

        // Clearing a row that DOES hold text still works.
        let mut s = Map::new();
        s.insert("user-phrase-2".into(), Value::from("HELLO"));
        apply_settings(&mut body, &s);
        s.insert("user-phrase-2".into(), Value::from(""));
        apply_settings(&mut body, &s);
        assert!(body[0x1520..0x1540].iter().all(|&b| b == 0));
    }

    // ============================================================
    // Synthetic no-op guards (#88) — no capture needed, so these run in CI
    // ============================================================

    /// A body filled with a pattern that has no long `0x00`/`0xff` runs.
    ///
    /// That makes it a HARSHER background than a real capture for the failure
    /// these tests exist to catch: a field that writes outside the extent it
    /// declares. On a real `.d75` most spare bytes are 0x00 or 0xff, so a stray
    /// write of 0 or 0xff lands invisibly. Here every byte is distinct from its
    /// neighbours, so any stray write shows up.
    fn patterned_body() -> Vec<u8> {
        let len = THD75_SETTINGS_FIELDS
            .iter()
            .map(field_end)
            .max()
            .expect("the table is not empty")
            + 64;
        (0..len).map(|i| (i.wrapping_mul(31) ^ 0xA5) as u8).collect()
    }

    /// [`patterned_body`] with an encoder-produced value in every field, so the
    /// field extents hold values this writer can actually emit while every byte
    /// no field claims still carries the pattern.
    fn normalised_body() -> Vec<u8> {
        let mut body = patterned_body();
        for (n, f) in THD75_SETTINGS_FIELDS.iter().enumerate() {
            if let Some((apply, _)) = probe_value(&body, f, n) {
                let mut one = Map::new();
                one.insert(f.key.to_string(), apply);
                apply_settings(&mut body, &one);
            }
        }
        body
    }

    /// A deterministic, in-range value for one field, and what decoding it back
    /// must give. The two differ for an enum whose option list maps two labels
    /// to the same raw value: `label_for` hands back the FIRST such label, so
    /// that — not the label we asked for — is the correct expectation.
    fn probe_value(body: &[u8], f: &SF, n: usize) -> Option<(Value, Value)> {
        Some(match &f.kind {
            SK::Bool | SK::BoolBit { .. } => {
                // Flip whatever is there, so the encoder is always exercised.
                let cur = decode_field(body, f).as_bool().unwrap_or(false);
                let v = Value::Bool(!cur);
                (v.clone(), v)
            }
            SK::Uint { width } | SK::UintLe { width } => {
                let max = (1u64 << (8 * *width as u64)) - 1;
                let v = Value::from((n as u64).wrapping_mul(2_654_435_761) % (max + 1));
                (v.clone(), v)
            }
            SK::Enum { labels, .. } => {
                if labels.is_empty() {
                    return None;
                }
                let (raw, label) = labels[n % labels.len()];
                (Value::from(label), label_for(labels, raw))
            }
            SK::Text { len } => {
                if *len == 0 {
                    return None;
                }
                // ASCII, no trailing space (the decoder trims those), shorter
                // than the field so the padding tail is exercised too.
                let take = (*len as usize).min(5);
                let s: String = (0..take)
                    .map(|i| (b'A' + ((n + i) % 26) as u8) as char)
                    .collect();
                let v = Value::from(s);
                (v.clone(), v)
            }
        })
    }

    /// ⚠ FINDING, not a property worth keeping: on this radio a save the
    /// operator did not make is NOT always inert. Two concrete cases, both
    /// reproduced here:
    ///
    ///   * a `Bool` byte holding anything but 0 or 1 decodes as `true` and is
    ///     rewritten as 0x01;
    ///   * a `Text` field holding real characters followed by an `0xff` tail
    ///     decodes with the tail cut off and is rewritten NUL-padded to the full
    ///     width. The driver's own decoder comment says untouched APRS rows are
    ///     "0xff, sometimes 0xff then NUL", so a partly-filled row is the
    ///     natural in-between — and `already_empty` only covers the fully-empty
    ///     case.
    ///
    /// The ID-52 does not have this: its `apply_settings` skips any field whose
    /// stored bytes already decode to the incoming value, so the operator's own
    /// encoding survives. Adding the same short-circuit here would fix both
    /// cases at once.
    ///
    /// Whether a real `.d75` ever holds either byte pattern is a question only a
    /// capture answers, which is why this pins the behaviour rather than
    /// asserting the fix. **If you are reading this because you added the
    /// short-circuit: delete this test** and assert the ID-52's property
    /// instead (`a_no_op_save_leaves_non_canonical_bytes_alone`).
    #[test]
    fn a_no_op_save_still_rewrites_two_kinds_of_non_canonical_byte() {
        let mut body = normalised_body();

        let text = THD75_SETTINGS_FIELDS
            .iter()
            .find(|f| matches!(f.kind, SK::Text { len } if len >= 4))
            .expect("a text field");
        let SK::Text { len } = text.kind else {
            unreachable!()
        };
        let at = text.byte as usize;
        body[at] = b'W';
        body[at + 1] = b'8';
        for b in body[at + 2..at + len as usize].iter_mut() {
            *b = 0xff;
        }

        let flag = THD75_SETTINGS_FIELDS
            .iter()
            .find(|f| matches!(f.kind, SK::Bool))
            .expect("a bool field");
        body[flag.byte as usize] = 0x5A;

        let before = body.clone();
        let decoded = decode_settings(&body);
        apply_settings(&mut body, &decoded.as_object().expect("an object").clone());

        assert_eq!(
            body[flag.byte as usize], 0x01,
            "{}: a non-0/1 flag byte is normalised on a save nobody asked for",
            flag.key
        );
        assert!(
            body[at + 2..at + len as usize].iter().all(|&b| b == 0),
            "{}: the 0xff tail is NUL-filled on a save nobody asked for",
            text.key
        );

        // And nothing ELSE moves — the two cases above are the whole of it, so
        // a third one appearing is a regression this test will catch.
        let moved: Vec<usize> = (0..before.len())
            .filter(|&i| before[i] != body[i])
            .filter(|&i| i != flag.byte as usize && !(at..at + len as usize).contains(&i))
            .collect();
        assert!(
            moved.is_empty(),
            "a third non-inert case appeared, first at {:#06x} — {}",
            moved[0],
            THD75_SETTINGS_FIELDS
                .iter()
                .find(|f| moved[0] >= f.byte as usize && moved[0] < field_end(f))
                .map_or("<no field claims it>", |f| f.key)
        );
    }

    /// Every field must encode as the exact inverse of its decode, and must
    /// write NOTHING outside the extent `field_end` declares for it.
    ///
    /// The second half is the one that matters and the one a read-back test
    /// cannot see: get a stride or a width wrong and the writer silently
    /// clobbers whatever lives next door, while every test that checks the
    /// bytes the writer got right still passes.
    ///
    /// ⚠ What this does NOT prove: that these encodings match what the RADIO
    /// writes. Only a real capture can say that, which is what the `#[ignore]`d
    /// `a_profile_read_from_a_capture_writes_it_back_unchanged` above is for.
    /// This proves the table is self-consistent and stays in its lane.
    #[test]
    fn every_field_round_trips_and_stays_inside_its_own_extent() {
        let mut body = patterned_body();
        let mut exercised = 0;

        for (n, f) in THD75_SETTINGS_FIELDS.iter().enumerate() {
            let Some((apply, expect)) = probe_value(&body, f, n) else {
                continue;
            };
            let before = body.clone();

            let mut one = Map::new();
            one.insert(f.key.to_string(), apply.clone());
            let written = apply_settings(&mut body, &one);
            assert_eq!(written, 1, "{} was not accepted (sent {apply})", f.key);

            let got = decode_field(&body, f);
            assert_eq!(got, expect, "{} did not survive a round trip", f.key);

            let (lo, hi) = (f.byte as usize, field_end(f));
            for (i, (a, b)) in before.iter().zip(&body).enumerate() {
                assert!(
                    a == b || (lo..hi).contains(&i),
                    "{} claims bytes {lo:#06x}..{hi:#06x} but writing it changed \
                     {i:#06x} ({a:#04x} -> {b:#04x})",
                    f.key
                );
            }
            exercised += 1;
        }

        assert!(exercised > 300, "only {exercised} fields exercised");
    }

    /// Saving a profile you did not edit must move zero bytes.
    ///
    /// This is the whole bargain of a card radio: the app patches the operator's
    /// OWN file, so a save they did not ask for has to be inert. The FT5D
    /// regression that sent a real radio back to its first-boot call-sign prompt
    /// was exactly this — `apply` padding a value nobody edited differently from
    /// the way the radio wrote it.
    ///
    /// Run against a body whose every field has already been through `apply`, so
    /// the values are ones this encoder can actually produce, while every byte
    /// no field claims still carries the pattern.
    #[test]
    fn a_profile_nobody_edited_writes_zero_bytes() {
        let mut body = normalised_body();
        let before = body.clone();
        let decoded = decode_settings(&body);
        let settings = decoded.as_object().expect("an object").clone();
        let applied = apply_settings(&mut body, &settings);
        assert_eq!(
            applied,
            settings.len(),
            "every decoded field should be accepted on the way back"
        );

        let moved: Vec<usize> = (0..before.len()).filter(|&i| before[i] != body[i]).collect();
        assert!(
            moved.is_empty(),
            "{} bytes changed on a no-op save, first at {:#06x} — {}",
            moved.len(),
            moved.first().copied().unwrap_or(0),
            THD75_SETTINGS_FIELDS
                .iter()
                .find(|f| moved[0] >= f.byte as usize && moved[0] < field_end(f))
                .map_or("<no field claims it>", |f| f.key)
        );
    }

    /// Apply a whole saved profile back onto the capture it was read from, and
    /// assert the body comes out BYTE-IDENTICAL.
    ///
    /// This is the write half of the read/write pair, and the only check that
    /// can catch a field whose encoder changes bytes the decoder never looked
    /// at -- padding, spare bits, an untouched grid row. Read-back tests
    /// cannot see it, because both sides agree on the value while the bytes
    /// drift ([[read-path-working-hides-a-dead-write-path]]).
    ///
    ///     THD75_CAPTURE=…/baseline.d75 THD75_PROFILE=…/profile.json \
    ///       cargo test --lib a_profile_read_from_a_capture_writes_it_back -- --ignored
    #[test]
    #[ignore]
    fn a_profile_read_from_a_capture_writes_it_back_unchanged() {
        let file = std::fs::read(std::env::var("THD75_CAPTURE").expect("capture")).unwrap();
        let json = std::fs::read_to_string(std::env::var("THD75_PROFILE").expect("profile")).unwrap();
        let saved: Map<String, Value> = serde_json::from_str(&json).expect("profile parses");

        let mut body = file[0x100..].to_vec();
        let before = body.clone();
        let written = apply_settings(&mut body, &saved);
        println!("{written} fields applied");

        let diff: Vec<usize> = (0..body.len()).filter(|&i| body[i] != before[i]).collect();
        for &i in diff.iter().take(20) {
            let who = THD75_SETTINGS_FIELDS
                .iter()
                .find(|f| i >= f.byte as usize && i < field_end(f))
                .map_or("<no field claims it>", |f| f.key);
            println!("  {:#06x}  {:#04x} -> {:#04x}  {who}", i, before[i], body[i]);
        }
        assert!(diff.is_empty(), "{} bytes changed writing a profile back", diff.len());
    }

    /// Decode a real RT Systems capture and check the four APRS grids against
    /// the distinctive strings that were typed into them on the instrument.
    ///
    /// The layouts are strides rather than one measured address per field, so
    /// a base or stride wrong by one still produces a table that compiles,
    /// passes the overlap guard, and reads plausible-looking bytes out of the
    /// wrong record. Reading a capture whose contents are known is what rules
    /// that out. `scratchpad/` is gitignored, so the capture comes in by env
    /// var and the test is #[ignore]d:
    ///
    ///     THD75_CAPTURE=scratchpad/thd75/rts/rts119.d75 \
    ///       cargo test --lib decodes_a_real_captures_aprs_grids -- --ignored
    #[test]
    #[ignore]
    fn decodes_a_real_captures_aprs_grids() {
        let path = std::env::var("THD75_CAPTURE").expect("THD75_CAPTURE");
        let file = std::fs::read(path).expect("read capture");
        let v = decode_settings(&file[0x100..]);

        // Two rows a full stride apart, and the selector that is one index.
        assert_eq!(v["status-text-1"], "TIMMYS D75");
        assert_eq!(v["status-text-2"], "ZZTEST2");
        assert_eq!(v["status-text-1-tx-rate"], "1/4");
        assert_eq!(v["selected-status-text"], "Status Text 5");
        // An untouched row: 0xff all through, which must read as empty.
        assert_eq!(v["status-text-5"], "");

        // The first and the twentieth phrase, the last one filling its 32
        // bytes exactly.
        assert_eq!(v["user-phrase-1"], "ZZPHRASE1");
        assert_eq!(v["user-phrase-20"], "ABCDEFGHIJKLMNOPQRSTUVWXYZ012345");

        // ★ The Mic-E type is the ASCII character, not the number.
        assert_eq!(v["mice-k-handy-1-type"], "7");
        assert_eq!(v["mice-k-handy-1-name"], "KHANDY");

        // A whole beacon object, every cell of it.
        assert_eq!(v["selected-beacon-object"], "Beacon Object 3");
        assert_eq!(v["beacon-object-1-latitude-degrees"], 12);
        assert_eq!(v["beacon-object-1-latitude-minutes"], 34);
        assert_eq!(v["beacon-object-1-latitude-1-10000-minutes"], 5600);
        assert_eq!(v["beacon-object-1-latitude-north"], Value::Bool(true));
        assert_eq!(v["beacon-object-1-longitude-degrees"], 123);
        assert_eq!(v["beacon-object-1-longitude-minutes"], 45);
        assert_eq!(v["beacon-object-1-longitude-1-10000-minutes"], 6700);
        assert_eq!(v["beacon-object-1-longitude-east"], Value::Bool(true));
        assert_eq!(v["beacon-object-1-name"], "ZOBJ1");
        assert_eq!(v["beacon-object-1-type"], "Killed Object");
        assert_eq!(v["beacon-object-1-method"], "Auto 30 min");
        assert_eq!(v["beacon-object-1-icon-table"], "/");
        assert_eq!(v["beacon-object-1-icon-symbol"], "K");
        assert_eq!(v["beacon-object-1-comment"], "ZCOMMENT1");
    }
}
