// GENERATED by scratchpad/thd75/gen_thd75_table.py from
// scratchpad/thd75/rts/MEASURED.md. Do not hand-edit; regenerate.
//
// Offsets are BODY offsets into the .d75 image (file offset minus 0x100).
// Every one was MEASURED by diffing two real RT Systems saves; none is
// inferred from another radio's driver.
//
// `UNVERIFIED-ORDER` marks a field whose option LABELS came from the
// manual with nothing in the measurement sheet to check their order
// against. The address and the encoding are measured; the order of the
// labels is not. This radio reverses the manual's printed order in at
// least three places, so treat those as provisional.
pub(crate) const THD75_SETTINGS_FIELDS: &[SF] = &[
    SF { key: "a-band-tx-power", byte: 0x00359, kind: SK::Enum { width: 1, labels: &[(0, "High"), (1, "Medium"), (2, "Low"), (3, "Economic Low")] } },  // A Band Tx Power
    SF { key: "b-band-tx-power", byte: 0x00369, kind: SK::Enum { width: 1, labels: &[(0, "High"), (1, "Medium"), (2, "Low"), (3, "Economic Low")] } },  // B Band Tx Power
    SF { key: "beat-shift", byte: 0x01000, kind: SK::Enum { width: 1, labels: &[(0, "Type 1"), (1, "Type 2"), (2, "Type 3"), (3, "Type 4"), (4, "Type 5"), (5, "Type 6"), (6, "Type 7"), (7, "Type 8")] } },  // Beat Shift
    SF { key: "tx-inhibit", byte: 0x01001, kind: SK::Bool },  // Tx Inhibit
    SF { key: "usb-out-select-rts-detect-out-select", byte: 0x01002, kind: SK::Enum { width: 1, labels: &[(0, "Off (AF)"), (1, "IF"), (2, "Detect")] } },  // USB Out Select (RTS: "Detect Out Select")
    SF { key: "time-out-timer", byte: 0x01003, kind: SK::Enum { width: 1, labels: &[(0, "0.5 min"), (10, "10.0 min")] } },  // Time-out Timer
    SF { key: "mw-sw-antenna", byte: 0x01005, kind: SK::Enum { width: 1, labels: &[(0, "Ant Connector"), (1, "Bar Antenna")] } },  // MW/SW Antenna
    SF { key: "mic-sensitivity", byte: 0x01006, kind: SK::Enum { width: 1, labels: &[(0, "High"), (1, "Medium"), (2, "Low")] } },  // Mic Sensitivity
    SF { key: "wx-alert", byte: 0x01007, kind: SK::Bool },  // Wx Alert
    SF { key: "ssb-high-cut", byte: 0x01008, kind: SK::Enum { width: 1, labels: &[(0, "2.2"), (4, "3.0")] } },  // SSB High Cut
    SF { key: "cw-width", byte: 0x01009, kind: SK::Enum { width: 1, labels: &[(0, "0.3"), (4, "2.0")] } },  // CW Width
    SF { key: "am-high-cut", byte: 0x0100a, kind: SK::Enum { width: 1, labels: &[(0, "3.0"), (3, "7.5")] } },  // AM High Cut
    SF { key: "resume", byte: 0x0100c, kind: SK::Enum { width: 1, labels: &[(0, "Time"), (1, "Carrier"), (2, "Seek")] } },  // Resume
    SF { key: "resume-digital", byte: 0x0100d, kind: SK::Enum { width: 1, labels: &[(0, "Time"), (1, "Carrier"), (2, "Seek")] } },  // Resume (Digital)
    SF { key: "time-restart", byte: 0x0100e, kind: SK::Uint { width: 1 } },  // Time Restart
    SF { key: "carrier-restart", byte: 0x0100f, kind: SK::Uint { width: 1 } },  // Carrier Restart
    SF { key: "priority-scan", byte: 0x01011, kind: SK::Bool },  // Priority Scan
    SF { key: "auto-backlight", byte: 0x01012, kind: SK::Bool },  // Auto Backlight
    SF { key: "auto-wx-scan", byte: 0x01013, kind: SK::Enum { width: 1, labels: &[(0, "Off"), (1, "15"), (2, "30"), (3, "60")] } },  // Auto Wx Scan
    SF { key: "auto-repeater-offset", byte: 0x01018, kind: SK::Bool },  // Auto Repeater Offset
    SF { key: "call-key", byte: 0x01019, kind: SK::Enum { width: 1, labels: &[(0, "CALL"), (1, "1750 Hz")] } },  // Call Key
    SF { key: "1750hz-tx-hold", byte: 0x0101a, kind: SK::Bool },  // 1750Hz Tx Hold
    SF { key: "vox-enable", byte: 0x0101b, kind: SK::Bool },  // VOX Enable
    SF { key: "vox-gain", byte: 0x0101c, kind: SK::Uint { width: 1 } },  // VOX Gain
    SF { key: "vox-delay", byte: 0x0101d, kind: SK::Enum { width: 1, labels: &[(0, "250 ms"), (6, "3000 ms")] } },  // VOX Delay
    SF { key: "tx-on-busy", byte: 0x0101e, kind: SK::Bool },  // Tx On Busy
    SF { key: "cw-pitch-frequency", byte: 0x01024, kind: SK::Enum { width: 1, labels: &[(0, "400 Hz"), (6, "1000 Hz")] } },  // CW Pitch Frequency
    SF { key: "cw-reverse", byte: 0x01026, kind: SK::Enum { width: 1, labels: &[(0, "Normal"), (1, "Reverse")] } },  // CW Reverse
    SF { key: "qso-log", byte: 0x01027, kind: SK::Bool },  // QSO Log
    SF { key: "led-control-rx", byte: 0x01028, kind: SK::BoolBit { shift: 0 } },  // LED Control — RX
    SF { key: "led-control-fm-radio", byte: 0x01028, kind: SK::BoolBit { shift: 1 } },  // LED Control — FM Radio
    SF { key: "recall-method", byte: 0x01030, kind: SK::Enum { width: 1, labels: &[(0, "All Bands"), (1, "Current Band")] } },  // Recall Method
    SF { key: "recording-band", byte: 0x01031, kind: SK::Enum { width: 1, labels: &[(0, "A Band"), (1, "B Band")] } },  // Recording Band
    SF { key: "tx-monitor", byte: 0x01032, kind: SK::Bool },  // Tx Monitor
    SF { key: "backlight-control", byte: 0x01060, kind: SK::Enum { width: 1, labels: &[(0, "Manual"), (1, "On"), (2, "Auto"), (3, "Auto (DC-IN)")] } },  // Backlight Control
    SF { key: "backlight-timer", byte: 0x01061, kind: SK::Uint { width: 1 } },  // Backlight Timer
    SF { key: "lcd-brightness", byte: 0x01062, kind: SK::Enum { width: 1, labels: &[(0, "Low"), (1, "Medium"), (2, "High")] } },  // LCD Brightness
    SF { key: "single-band-display", byte: 0x01063, kind: SK::Enum { width: 1, labels: &[(0, "Off"), (1, "GPS (Altitude)"), (2, "GPS (GS)"), (3, "Date")] } },  // Single Band Display
    SF { key: "meter-type", byte: 0x01064, kind: SK::Enum { width: 1, labels: &[(0, "Type 1"), (2, "Type 3")] } },  // Meter Type
    SF { key: "background-color-rts-backlight-color", byte: 0x01065, kind: SK::Enum { width: 1, labels: &[(0, "Black"), (1, "White")] } },  // Background Color (RTS: "Backlight Color")
    SF { key: "info-backlight", byte: 0x01096, kind: SK::Enum { width: 1, labels: &[(0, "Off"), (1, "LCD"), (2, "LCD+Key")] } },  // Info Backlight
    SF { key: "power-on-message", byte: 0x010c0, kind: SK::Text { len: 16 } },  // Power On Message
    SF { key: "digital-auto-reply", byte: 0x01a21, kind: SK::Enum { width: 1, labels: &[(0, "Off"), (1, "Voice Message 1 - Voice Message 4")] } },  // Digital Auto Reply  // UNVERIFIED-ORDER
    SF { key: "balance", byte: 0x01066, kind: SK::Enum { width: 1, labels: &[(4, "index (A:100/B:100"), (9, "Band Only")] } },  // Balance
    SF { key: "equalizer-enables-menu-911-receive-eq", byte: 0x01067, kind: SK::BoolBit { shift: 0 } },  // Equalizer enables (menu 911) — Receive EQ
    SF { key: "equalizer-enables-menu-911-tx-eq-fm", byte: 0x01067, kind: SK::BoolBit { shift: 1 } },  // Equalizer enables (menu 911) — Tx EQ (FM
    SF { key: "equalizer-enables-menu-911-tx-eq-dv", byte: 0x01067, kind: SK::BoolBit { shift: 2 } },  // Equalizer enables (menu 911) — Tx EQ (DV)
    SF { key: "tx-equalizer-level-4-bands-0-4-0-8-1-6-3-2-khz", byte: 0x01068, kind: SK::Enum { width: 1, labels: &[(0, "9"), (9, "0"), (12, "3")] } },  // Tx Equalizer Level, 4 bands (0.4/0.8/1.6/3.2 kHz)
    SF { key: "rx-equalizer-level-5-bands-0-4-0-8-1-6-3-2-6-4-khz", byte: 0x0106c, kind: SK::Enum { width: 1, labels: &[(0, "9"), (9, "0"), (18, "9")] } },  // Rx Equalizer Level, 5 bands (0.4/0.8/1.6/3.2/6.4 kHz)
    SF { key: "beep-a", byte: 0x01071, kind: SK::Bool },  // Beep (A)
    SF { key: "beep-volume", byte: 0x01072, kind: SK::Enum { width: 1, labels: &[(0, "Vol Link"), (1, "Level 1-7")] } },  // Beep Volume
    SF { key: "voice-guidance", byte: 0x01073, kind: SK::Enum { width: 1, labels: &[(0, "Off"), (3, "Auto 2")] } },  // Voice Guidance
    SF { key: "voice-guidance-volume", byte: 0x01074, kind: SK::Enum { width: 1, labels: &[(0, "Level 1"), (6, "Level 7")] } },  // Voice Guidance Volume
    SF { key: "usb-audio-level", byte: 0x01075, kind: SK::Enum { width: 1, labels: &[(0, "Level 1"), (7, "Level 8")] } },  // USB Audio Level
    SF { key: "battery-saver", byte: 0x01076, kind: SK::Enum { width: 1, labels: &[(0, "Off"), (1, "0.2"), (2, "0.4"), (3, "0.6"), (4, "0.8"), (5, "1.0"), (6, "2.0"), (7, "3.0"), (8, "4.0"), (9, "5.0")] } },  // Battery Saver  // UNVERIFIED-ORDER
    SF { key: "auto-power-off", byte: 0x01077, kind: SK::Enum { width: 1, labels: &[(0, "Off"), (1, "15"), (2, "30"), (3, "60")] } },  // Auto Power Off
    SF { key: "bluetooth-enable", byte: 0x01078, kind: SK::Bool },  // Bluetooth Enable
    SF { key: "bluetooth-auto-connect", byte: 0x01079, kind: SK::Bool },  // Bluetooth Auto Connect
    SF { key: "pf1-key", byte: 0x0107a, kind: SK::Enum { width: 1, labels: &[(0, "Recording"), (1, "Voice Msg 1"), (2, "Voice Msg 2"), (3, "Voice Msg 3"), (4, "Voice Msg 4"), (6, "Voice Guidance"), (7, "Battery Level"), (8, "VOX"), (9, "Group Name"), (10, "Balance"), (11, "GPS"), (12, "Track Log"), (13, "Squelch"), (14, "Shift"), (15, "Step"), (16, "Low"), (17, "Key Lock"), (18, "Lockout"), (19, "M>V"), (20, "T.SEL"), (21, "NEW"), (22, "Voice Alert"), (24, "LCD Brightness"), (27, "DTMF CH0"), (28, "Echolink CH0"), (29, "1750Hz Tone"), (30, "M.IN")] } },  // PF1 Key
    SF { key: "pf2-key", byte: 0x0107b, kind: SK::Enum { width: 1, labels: &[(0, "Recording"), (1, "Voice Msg 1"), (2, "Voice Msg 2"), (3, "Voice Msg 3"), (4, "Voice Msg 4"), (6, "Voice Guidance"), (7, "Battery Level"), (8, "VOX"), (9, "Group Name"), (10, "Balance"), (11, "GPS"), (12, "Track Log"), (13, "Squelch"), (14, "Shift"), (15, "Step"), (16, "Low"), (17, "Key Lock"), (18, "Lockout"), (19, "M>V"), (20, "T.SEL"), (21, "NEW"), (22, "Voice Alert"), (24, "LCD Brightness"), (27, "DTMF CH0"), (28, "Echolink CH0"), (29, "1750Hz Tone"), (30, "M.IN")] } },  // PF2 Key
    SF { key: "pf1-key-mic", byte: 0x0107c, kind: SK::Enum { width: 1, labels: &[(0, "Recording"), (1, "Voice Msg 1"), (2, "Voice Msg 2"), (3, "Voice Msg 3"), (4, "Voice Msg 4"), (6, "Voice Guidance"), (7, "Battery Level"), (8, "VOX"), (9, "Group Name"), (10, "Balance"), (11, "GPS"), (12, "Track Log"), (13, "Squelch"), (14, "Shift"), (15, "Step"), (16, "Low"), (17, "Key Lock"), (18, "Lockout"), (19, "M>V"), (20, "T.SEL"), (21, "NEW"), (22, "Voice Alert"), (24, "LCD Brightness"), (27, "DTMF CH0"), (28, "Echolink CH0"), (29, "1750Hz Tone"), (31, "Screen Capture"), (32, "Mode"), (33, "Menu"), (34, "A/B"), (35, "VFO"), (36, "MR"), (37, "Call"), (38, "Message"), (39, "List"), (40, "Beacon"), (41, "REV"), (42, "Tone"), (44, "MHz"), (45, "MARK"), (46, "DUAL"), (47, "APRS"), (48, "OBJ"), (49, "ATT"), (50, "Fine"), (51, "POS"), (52, "BAND"), (53, "MONI"), (54, "Up"), (55, "Down")] } },  // PF1 Key (Mic)
    SF { key: "pf2-key-mic", byte: 0x0107d, kind: SK::Enum { width: 1, labels: &[(0, "Recording"), (1, "Voice Msg 1"), (2, "Voice Msg 2"), (3, "Voice Msg 3"), (4, "Voice Msg 4"), (6, "Voice Guidance"), (7, "Battery Level"), (8, "VOX"), (9, "Group Name"), (10, "Balance"), (11, "GPS"), (12, "Track Log"), (13, "Squelch"), (14, "Shift"), (15, "Step"), (16, "Low"), (17, "Key Lock"), (18, "Lockout"), (19, "M>V"), (20, "T.SEL"), (21, "NEW"), (22, "Voice Alert"), (24, "LCD Brightness"), (27, "DTMF CH0"), (28, "Echolink CH0"), (29, "1750Hz Tone"), (31, "Screen Capture"), (32, "Mode"), (33, "Menu"), (34, "A/B"), (35, "VFO"), (36, "MR"), (37, "Call"), (38, "Message"), (39, "List"), (40, "Beacon"), (41, "REV"), (42, "Tone"), (44, "MHz"), (45, "MARK"), (46, "DUAL"), (47, "APRS"), (48, "OBJ"), (49, "ATT"), (50, "Fine"), (51, "POS"), (52, "BAND"), (53, "MONI"), (54, "Up"), (55, "Down")] } },  // PF2 Key (Mic)
    SF { key: "pf3-key-mic", byte: 0x0107e, kind: SK::Enum { width: 1, labels: &[(0, "Recording"), (1, "Voice Msg 1"), (2, "Voice Msg 2"), (3, "Voice Msg 3"), (4, "Voice Msg 4"), (6, "Voice Guidance"), (7, "Battery Level"), (8, "VOX"), (9, "Group Name"), (10, "Balance"), (11, "GPS"), (12, "Track Log"), (13, "Squelch"), (14, "Shift"), (15, "Step"), (16, "Low"), (17, "Key Lock"), (18, "Lockout"), (19, "M>V"), (20, "T.SEL"), (21, "NEW"), (22, "Voice Alert"), (24, "LCD Brightness"), (27, "DTMF CH0"), (28, "Echolink CH0"), (29, "1750Hz Tone"), (31, "Screen Capture"), (32, "Mode"), (33, "Menu"), (34, "A/B"), (35, "VFO"), (36, "MR"), (37, "Call"), (38, "Message"), (39, "List"), (40, "Beacon"), (41, "REV"), (42, "Tone"), (44, "MHz"), (45, "MARK"), (46, "DUAL"), (47, "APRS"), (48, "OBJ"), (49, "ATT"), (50, "Fine"), (51, "POS"), (52, "BAND"), (53, "MONI"), (54, "Up"), (55, "Down")] } },  // PF3 Key (Mic)
    SF { key: "time-zone", byte: 0x01083, kind: SK::Uint { width: 1 } },  // Time Zone
    SF { key: "keys-lock-type", byte: 0x01084, kind: SK::Enum { width: 1, labels: &[(0, "Off"), (3, "Both Locks")] } },  // Keys Lock Type
    SF { key: "dtmf-keys-lock", byte: 0x01085, kind: SK::Bool },  // DTMF Keys Lock
    SF { key: "mic-keys-lock", byte: 0x01086, kind: SK::Bool },  // Mic Keys Lock
    SF { key: "volume-lock", byte: 0x01087, kind: SK::Bool },  // Volume Lock
    SF { key: "speed-distance", byte: 0x01088, kind: SK::Enum { width: 1, labels: &[(0, "mi/h"), (1, "km/h"), (2, "knots"), (3, "nm")] } },  // Speed, Distance
    SF { key: "altitude-rain", byte: 0x01089, kind: SK::Enum { width: 1, labels: &[(0, "inch"), (1, "mm")] } },  // Altitude, Rain
    SF { key: "temperature", byte: 0x0108a, kind: SK::Enum { width: 1, labels: &[(0, "F"), (1, "C")] } },  // Temperature
    SF { key: "latitude-longitude", byte: 0x0108b, kind: SK::Enum { width: 1, labels: &[(0, "dd mm.mm"), (1, "dd mm ss.s")] } },  // Latitude, Longitude
    SF { key: "grid-square", byte: 0x0108c, kind: SK::Enum { width: 1, labels: &[(0, "Maidenhead"), (1, "SAR"), (2, "SAR")] } },  // Grid Square
    SF { key: "pc-output-gps", byte: 0x0108e, kind: SK::Enum { width: 1, labels: &[(0, "USB"), (1, "Bluetooth")] } },  // PC Output (GPS)
    SF { key: "pc-output-aprs", byte: 0x0108f, kind: SK::Enum { width: 1, labels: &[(0, "USB"), (1, "Bluetooth")] } },  // PC Output (APRS)
    SF { key: "kiss", byte: 0x01090, kind: SK::Enum { width: 1, labels: &[(0, "USB"), (1, "Bluetooth")] } },  // KISS
    SF { key: "dv-dr", byte: 0x01091, kind: SK::Enum { width: 1, labels: &[(0, "USB"), (1, "Bluetooth")] } },  // DV/DR
    SF { key: "language", byte: 0x01092, kind: SK::Enum { width: 1, labels: &[(0, "English"), (1, "Japanese")] } },  // Language
    SF { key: "pc-io-dv-gateway", byte: 0x01093, kind: SK::Enum { width: 1, labels: &[(0, "USB"), (1, "Bluetooth")] } },  // PC IO (DV Gateway)
    SF { key: "charging", byte: 0x01094, kind: SK::Bool },  // Charging
    SF { key: "callsign-readout", byte: 0x01095, kind: SK::Enum { width: 1, labels: &[(0, "Standard"), (2, "Phonetics(Suffix)")] } },  // Callsign Readout
    SF { key: "bluetooth-device-name", byte: 0x010d0, kind: SK::Text { len: 16 } },  // Bluetooth Device Name
    SF { key: "dtmf-speed", byte: 0x0101f, kind: SK::Enum { width: 1, labels: &[(0, "50 ms"), (1, "100 ms"), (2, "150 ms")] } },  // DTMF Speed
    SF { key: "dtmf-tx-hold", byte: 0x01021, kind: SK::Bool },  // DTMF Tx Hold
    SF { key: "fm-radio-mode", byte: 0x01040, kind: SK::Bool },  // FM Radio Mode
    SF { key: "fm-auto-mute-return-time", byte: 0x01041, kind: SK::Uint { width: 1 } },  // FM Auto Mute Return Time
    SF { key: "builtin-gps", byte: 0x01100, kind: SK::Bool },  // Builtin GPS
    SF { key: "position-ambiguity", byte: 0x01101, kind: SK::Enum { width: 1, labels: &[(0, "Off"), (4, "4 Digit")] } },  // Position Ambiguity
    SF { key: "gps-operating-mode", byte: 0x01102, kind: SK::Enum { width: 1, labels: &[(0, "Normal"), (1, "GPS Receiver")] } },  // GPS Operating Mode
    SF { key: "gps-battery-saver", byte: 0x01103, kind: SK::Enum { width: 1, labels: &[(0, "Off"), (5, "Auto")] } },  // GPS Battery Saver
    SF { key: "gps-pc-output", byte: 0x01104, kind: SK::Bool },  // GPS PC Output
    SF { key: "gps-sentence-gga", byte: 0x01105, kind: SK::BoolBit { shift: 0 } },  // GPS Sentence — GGA
    SF { key: "gps-sentence-gll", byte: 0x01105, kind: SK::BoolBit { shift: 1 } },  // GPS Sentence — GLL
    SF { key: "gps-sentence-gsa", byte: 0x01105, kind: SK::BoolBit { shift: 2 } },  // GPS Sentence — GSA
    SF { key: "gps-sentence-gsv", byte: 0x01105, kind: SK::BoolBit { shift: 3 } },  // GPS Sentence — GSV
    SF { key: "gps-sentence-rmc", byte: 0x01105, kind: SK::BoolBit { shift: 4 } },  // GPS Sentence — RMC
    SF { key: "gps-sentence-vtg-the-radio-enforces-max-4-selected", byte: 0x01105, kind: SK::BoolBit { shift: 5 } },  // GPS Sentence — VTG.  the radio enforces max 4 selected
    SF { key: "track-log", byte: 0x01106, kind: SK::Bool },  // Track Log
    SF { key: "track-log-record-method", byte: 0x01108, kind: SK::Enum { width: 1, labels: &[(0, "Time"), (1, "Distance"), (2, "Beacon")] } },  // Track Log Record Method
    SF { key: "track-log-interval", byte: 0x01110, kind: SK::Uint { width: 1 } },  // Track Log Interval
    SF { key: "direct-reply", byte: 0x01a00, kind: SK::Bool },  // Direct Reply
    SF { key: "auto-reply-timing", byte: 0x01a01, kind: SK::Enum { width: 1, labels: &[(0, "Immediate"), (1, "5"), (2, "10"), (3, "20"), (4, "30"), (5, "60")] } },  // Auto Reply Timing  // UNVERIFIED-ORDER
    SF { key: "data-tx-end-timing", byte: 0x01a02, kind: SK::Enum { width: 1, labels: &[(0, "Off"), (1, "0.5"), (2, "1"), (3, "1.5"), (4, "2")] } },  // Data Tx End Timing  // UNVERIFIED-ORDER
    SF { key: "dv-level-rts-id-1285", byte: 0x01a03, kind: SK::Uint { width: 1 } },  // DV Level (RTS id 1285)
    SF { key: "rx-afc", byte: 0x01a04, kind: SK::Bool },  // Rx AFC
    SF { key: "fm-auto-detection-on-dv", byte: 0x01a05, kind: SK::Bool },  // FM Auto Detection on DV
    SF { key: "data-frame-output", byte: 0x01a06, kind: SK::Enum { width: 1, labels: &[(0, "All"), (1, "Related to DSQ"), (2, "DATA Mode")] } },  // Data Frame Output  // UNVERIFIED-ORDER
    SF { key: "gps-information-in-frame", byte: 0x01a0a, kind: SK::Bool },  // GPS Information in Frame
    SF { key: "dv-gps-sentence-gga", byte: 0x01a0b, kind: SK::BoolBit { shift: 0 } },  // DV GPS Sentence — GGA
    SF { key: "dv-gps-sentence-gll", byte: 0x01a0b, kind: SK::BoolBit { shift: 1 } },  // DV GPS Sentence — GLL
    SF { key: "dv-gps-sentence-gsa", byte: 0x01a0b, kind: SK::BoolBit { shift: 2 } },  // DV GPS Sentence — GSA
    SF { key: "dv-gps-sentence-gsv", byte: 0x01a0b, kind: SK::BoolBit { shift: 3 } },  // DV GPS Sentence — GSV
    SF { key: "dv-gps-sentence-rmc", byte: 0x01a0b, kind: SK::BoolBit { shift: 4 } },  // DV GPS Sentence — RMC
    SF { key: "dv-gps-sentence-vtg", byte: 0x01a0b, kind: SK::BoolBit { shift: 5 } },  // DV GPS Sentence — VTG
    SF { key: "dv-gps-sentence-aprs-max-4-selected", byte: 0x01a0b, kind: SK::BoolBit { shift: 6 } },  // DV GPS Sentence — APRS.  max 4 selected
    SF { key: "auto-tx", byte: 0x01a0c, kind: SK::Enum { width: 1, labels: &[(0, "Off"), (1, "0.2"), (2, "0.5"), (3, "1"), (4, "2"), (5, "3"), (6, "5"), (7, "10"), (8, "20"), (9, "30"), (10, "60")] } },  // Auto Tx  // UNVERIFIED-ORDER
    SF { key: "display-method", byte: 0x01a0d, kind: SK::Enum { width: 1, labels: &[(0, "Off"), (1, "All"), (2, "Related to DQS"), (3, "My Station Only")] } },  // Display Method  // UNVERIFIED-ORDER
    SF { key: "single-display-size", byte: 0x01a0e, kind: SK::Enum { width: 1, labels: &[(0, "Half Display"), (1, "Entire Display")] } },  // Single Display Size  // UNVERIFIED-ORDER
    SF { key: "dual-display-size", byte: 0x01a0f, kind: SK::Enum { width: 1, labels: &[(0, "Half Display"), (1, "Entire Display")] } },  // Dual Display Size  // UNVERIFIED-ORDER
    SF { key: "display-hold-time", byte: 0x01a10, kind: SK::Enum { width: 1, labels: &[(0, "0"), (1, "3"), (2, "5"), (3, "10"), (4, "20"), (5, "30"), (6, "60"), (7, "Infinite")] } },  // Display Hold Time  // UNVERIFIED-ORDER
    SF { key: "callsign-announce", byte: 0x01a11, kind: SK::Enum { width: 1, labels: &[(0, "Off"), (1, "Kerchunk"), (2, "Except Kerchunk"), (3, "My Station Only"), (4, "All")] } },  // Callsign Announce  // UNVERIFIED-ORDER
    SF { key: "standby-beep", byte: 0x01a12, kind: SK::Bool },  // Standby Beep
    SF { key: "dv-device-name", byte: 0x01ad0, kind: SK::Text { len: 8 } },  // DV Device Name
    SF { key: "selected-my-callsign", byte: 0x01ca1, kind: SK::Uint { width: 1 } },  // Selected My Callsign
    SF { key: "rpt1", byte: 0x01cf0, kind: SK::Text { len: 8 } },  // RPT1
    SF { key: "rpt2", byte: 0x01cf8, kind: SK::Text { len: 8 } },  // RPT2
    SF { key: "decay-algorithm-moving", byte: 0x0000e, kind: SK::Uint { width: 1 } },  // Decay Algorithm "Moving"
    SF { key: "decay-algorithm-stopped", byte: 0x0000f, kind: SK::Uint { width: 1 } },  // Decay Algorithm "Stopped"
    SF { key: "data-band", byte: 0x0120b, kind: SK::Enum { width: 1, labels: &[(0, "A-Band"), (1, "B-Band")] } },  // Data Band
    SF { key: "data-speed", byte: 0x0120c, kind: SK::Enum { width: 1, labels: &[(0, "1200 bps"), (1, "9600 bps")] } },  // Data Speed
    SF { key: "dcd-sense", byte: 0x0120d, kind: SK::Enum { width: 1, labels: &[(0, "Busy"), (1, "Detect Data"), (2, "Off (Ignore)")] } },  // DCD Sense
    SF { key: "tx-delay", byte: 0x0120f, kind: SK::Enum { width: 1, labels: &[(0, "100 ms"), (1, "150 ms"), (2, "200 ms"), (3, "300 ms"), (4, "400 ms"), (5, "500 ms"), (6, "750 ms"), (7, "1000 ms")] } },  // Tx Delay
    SF { key: "waypoint-format", byte: 0x01213, kind: SK::Enum { width: 1, labels: &[(0, "NMEA"), (2, "KENWOOD")] } },  // Waypoint Format
    SF { key: "waypoint-length", byte: 0x01214, kind: SK::Uint { width: 1 } },  // Waypoint Length
    SF { key: "waypoint-output", byte: 0x01215, kind: SK::Enum { width: 1, labels: &[(0, "All"), (1, "Local"), (2, "Filtered")] } },  // Waypoint Output
    SF { key: "position-comment", byte: 0x01222, kind: SK::Enum { width: 1, labels: &[(0, "Off Duty"), (1, "Enroute"), (2, "In Service"), (3, "Returning"), (4, "Committed"), (5, "Special"), (6, "PRIORITY"), (7, "CUSTOM 0"), (8, "CUSTOM 1"), (9, "CUSTOM 2"), (10, "CUSTOM 3"), (11, "CUSTOM 4"), (12, "CUSTOM 5"), (13, "CUSTOM 6"), (14, "EMERGENCY!")] } },  // Position Comment
    SF { key: "beacon-method", byte: 0x0136a, kind: SK::Enum { width: 1, labels: &[(0, "Manual"), (3, "SmartBeaconing")] } },  // Beacon Method
    SF { key: "beacon-initial-interval", byte: 0x0136b, kind: SK::Enum { width: 1, labels: &[(0, ".2 min"), (1, ".5 min"), (2, "1 min"), (3, "2 min"), (4, "3 min"), (5, "5 min"), (6, "10 min"), (7, "20 min"), (8, "30 min"), (9, "60 min")] } },  // Beacon Initial Interval
    SF { key: "packet-path-type", byte: 0x01375, kind: SK::Enum { width: 1, labels: &[(0, "New-N"), (1, "RELAY")] } },  // Packet Path Type
    SF { key: "wide1-1", byte: 0x01376, kind: SK::Bool },  // WIDE1-1
    SF { key: "total-hops", byte: 0x01377, kind: SK::Enum { width: 1, labels: &[(0, "0"), (1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5"), (6, "6"), (7, "7")] } },  // Total Hops
    SF { key: "aprs-my-callsign", byte: 0x01200, kind: SK::Text { len: 9 } },  // APRS My Callsign
    SF { key: "aprs-lock-frequency", byte: 0x0120a, kind: SK::BoolBit { shift: 0 } },  // APRS Lock — Frequency
    SF { key: "aprs-lock-ptt", byte: 0x0120a, kind: SK::BoolBit { shift: 1 } },  // APRS Lock — PTT
    SF { key: "aprs-lock-aprs-key", byte: 0x0120a, kind: SK::BoolBit { shift: 2 } },  // APRS Lock — APRS Key
    SF { key: "beacon-information-speed", byte: 0x01220, kind: SK::Bool },  // Beacon Information Speed
    SF { key: "beacon-information-altitude", byte: 0x01221, kind: SK::Bool },  // Beacon Information Altitude
    SF { key: "position-limit", byte: 0x01365, kind: SK::Enum { width: 1, labels: &[(0, "value / 10 (Off"), (3, "30"), (6, "60")] } },  // Position Limit
    SF { key: "packet-filter-type-weather", byte: 0x01366, kind: SK::BoolBit { shift: 0 } },  // Packet Filter Type — Weather
    SF { key: "packet-filter-type-digi", byte: 0x01366, kind: SK::BoolBit { shift: 1 } },  // Packet Filter Type — DIGI
    SF { key: "packet-filter-type-mobile", byte: 0x01366, kind: SK::BoolBit { shift: 2 } },  // Packet Filter Type — Mobile
    SF { key: "packet-filter-type-object", byte: 0x01366, kind: SK::BoolBit { shift: 3 } },  // Packet Filter Type — Object
    SF { key: "packet-filter-type-navitra", byte: 0x01366, kind: SK::BoolBit { shift: 4 } },  // Packet Filter Type — NAVITRA
    SF { key: "packet-filter-type-1-way", byte: 0x01366, kind: SK::BoolBit { shift: 5 } },  // Packet Filter Type — 1-Way
    SF { key: "packet-filter-type-others", byte: 0x01366, kind: SK::BoolBit { shift: 6 } },  // Packet Filter Type — Others
    SF { key: "station-icon-table-char", byte: 0x01367, kind: SK::Text { len: 1 } },  // Station Icon, table char
    SF { key: "decay-algorithm-enable", byte: 0x0136c, kind: SK::Bool },  // Decay Algorithm enable
    SF { key: "proportional-pathing-enable", byte: 0x0136d, kind: SK::Bool },  // Proportional Pathing enable
    SF { key: "packet-path-literal", byte: 0x01380, kind: SK::Text { len: 62 } },  // Packet Path, literal
    SF { key: "network", byte: 0x01460, kind: SK::Enum { width: 1, labels: &[(0, "APRS"), (1, "ALTNET")] } },  // Network
    SF { key: "network-altnet-text", byte: 0x01461, kind: SK::Text { len: 6 } },  // Network ALTNET text
    SF { key: "pc-output", byte: 0x01216, kind: SK::Uint { width: 1 } },  // PC Output
    SF { key: "aprs-voice", byte: 0x01219, kind: SK::Bool },  // APRS Voice
    SF { key: "voice-alert", byte: 0x0121a, kind: SK::Enum { width: 1, labels: &[(0, "Off"), (1, "On"), (2, "Rx Only")] } },  // Voice Alert
    SF { key: "voice-alert-ctcss-frequency", byte: 0x0121b, kind: SK::Enum { width: 1, labels: &[(0, "index into the 42-entry CTCSS list (67.0"), (41, "254.1")] } },  // Voice Alert CTCSS Frequency
    SF { key: "qsy-info-in-status", byte: 0x01361, kind: SK::Bool },  // QSY Info. in Status
    SF { key: "tone-narrow", byte: 0x01362, kind: SK::Bool },  // Tone / Narrow
    SF { key: "shift-offset", byte: 0x01363, kind: SK::Bool },  // Shift / Offset
    SF { key: "qsy-limit-distance", byte: 0x01364, kind: SK::Enum { width: 1, labels: &[(0, "distance / 10 (Off"), (1, "10"), (4, "40")] } },  // QSY Limit Distance
    SF { key: "smartbeaconing-low-speed", byte: 0x0136e, kind: SK::Uint { width: 1 } },  // SmartBeaconing Low Speed
    SF { key: "smartbeaconing-high-speed", byte: 0x0136f, kind: SK::Uint { width: 1 } },  // SmartBeaconing High Speed
    SF { key: "slow-rate", byte: 0x01370, kind: SK::Uint { width: 1 } },  // Slow Rate
    SF { key: "fast-rate", byte: 0x01371, kind: SK::Uint { width: 1 } },  // Fast Rate
    SF { key: "turn-angle", byte: 0x01372, kind: SK::Uint { width: 1 } },  // Turn Angle
    SF { key: "turn-slope", byte: 0x01373, kind: SK::Uint { width: 1 } },  // Turn Slope
    SF { key: "turn-time", byte: 0x01374, kind: SK::Uint { width: 1 } },  // Turn Time
    SF { key: "auto-reply", byte: 0x014b0, kind: SK::Bool },  // Auto Reply
    SF { key: "reply-delay-time", byte: 0x014b1, kind: SK::Enum { width: 1, labels: &[(0, "0"), (1, "10 seconds"), (2, "20 seconds"), (3, "30 seconds"), (4, "60 seconds")] } },  // Reply Delay Time
    SF { key: "reply-message-text", byte: 0x014b2, kind: SK::Text { len: 50 } },  // Reply Message Text
    SF { key: "reply-to", byte: 0x014f5, kind: SK::Text { len: 9 } },  // Reply To
    SF { key: "message-group-code", byte: 0x01800, kind: SK::Text { len: 59 } },  // Message Group Code
    SF { key: "bulletin-group-code", byte: 0x0183b, kind: SK::Text { len: 35 } },  // Bulletin Group Code
    SF { key: "rx-beep", byte: 0x0185e, kind: SK::Enum { width: 1, labels: &[(0, "All"), (1, "All New"), (2, "Mine"), (3, "Message Only"), (4, "Off")] } },  // RX Beep
    SF { key: "tx-beep-beacon", byte: 0x0185f, kind: SK::Bool },  // TX Beep (Beacon)
    SF { key: "special-call", byte: 0x01860, kind: SK::Text { len: 9 } },  // Special Call
    SF { key: "display-area", byte: 0x01869, kind: SK::Enum { width: 1, labels: &[(0, "One Line"), (1, "Entire Display"), (2, "Entire Always")] } },  // Display Area
    SF { key: "interrupt-time", byte: 0x0186a, kind: SK::Enum { width: 1, labels: &[(0, "3 sec"), (1, "5"), (2, "10"), (3, "20"), (4, "30"), (5, "60"), (6, "Forever")] } },  // Interrupt Time
    SF { key: "digipeat-my-callsign", byte: 0x0146c, kind: SK::Bool },  // Digipeat (My Callsign)
    SF { key: "uidigipeat", byte: 0x0146e, kind: SK::Bool },  // UIdigipeat
    SF { key: "uidigi-aliases", byte: 0x0146f, kind: SK::Text { len: 39 } },  // UIdigi Aliases
    SF { key: "uitrace", byte: 0x014a0, kind: SK::Bool },  // UItrace
    SF { key: "uitrace-alias", byte: 0x014a1, kind: SK::Text { len: 5 } },  // UItrace Alias
    SF { key: "uiflood", byte: 0x014a6, kind: SK::Bool },  // UIflood
    SF { key: "uiflood-alias", byte: 0x014a7, kind: SK::Text { len: 5 } },  // UIflood Alias
    SF { key: "uiflood-substitution", byte: 0x014ac, kind: SK::Enum { width: 1, labels: &[(0, "First"), (1, "ID"), (2, "NOID")] } },  // UIflood Substitution
];
