//! FT5D non-channel settings ("radio profile"): the field table plus decode and
//! apply against a microSD `BACKUP.dat`.
//!
//! Unlike every other radio here, the FT5D's settings do not travel over a
//! cable. They are read out of the operator's own backup file and written back
//! into it, so this module is pure byte manipulation with no serial I/O — see
//! [`super::sd_image`] for the same arrangement applied to channels.
//!
//! [`FT5D_SETTINGS_FIELDS`] is GENERATED by `scratchpad/ft5d/gen_ft5d_settings.py`
//! from CHIRP's `ft1d.py`: the bitwise struct definitions supply each field's
//! offset and bit position, the `_get_*_settings` methods supply its group,
//! label and option list, and the seed's schema JSON comes out of the *same*
//! parse — so the profile form and this decoder cannot drift.
//!
//! ## What is covered, and what is not
//!
//! 67 settings across 9 groups: Misc, Digital Modes, Group Monitor, Scan, DTMF,
//! and the APRS General/Receive/Transmit/SmartBeacon blocks.
//!
//! Absent by construction are CHIRP's *looped* settings — APRS message groups,
//! beacon status texts, message macros, the three SmartBeacon profiles, the
//! DTMF memories and the Backtrack log. Each of those is an **array** of values
//! built from a `%d`-templated path, and the profile form's schema is a flat
//! key → scalar map that cannot hold one. That is about 39 of CHIRP's 116.
//!
//! ## Confidence
//!
//! The offsets are CHIRP's, shifted by the same −10 that the channel decode
//! proved, and they land correctly on real data: `WW8L` appears at both
//! `0xBEC2` (APRS callsign) and `0xCEC6` (MYCALL) in Tim's dump, and the six
//! independent unit bits packed into `0xBECC` all decode to US units
//! (ft/mile/mph/inch/F) — an alignment error would not produce that.
//!
//! Confirmed on a real FT5D (2026-08-06): a *changed* setting from each of the
//! four address clusters — `0x04xx`, `0xBExx`, `0xC0xx`, `0xCFxx` — wrote to the
//! card, survived a Restore, and read back correctly in the radio's own menus.
//! One probe per cluster is what the risk called for: a bad CHIRP offset would
//! displace a whole block, not a single field. The probes must be values that
//! actually *changed*, because [`apply_settings`] deliberately leaves a matching
//! setting's bytes untouched.

use serde_json::{Map, Value};

/// One decodable setting: where it lives in the SD image and how to read it.
/// Values are shaped like the profile form — booleans, numbers, select labels
/// or text.
pub(crate) struct SF {
    pub key: &'static str,
    /// Byte offset into the microSD image (CHIRP's address − 10).
    pub byte: u32,
    pub kind: SK,
}

/// `shift` is the bit position from the LSB. CHIRP packs bitfields MSB-first
/// within a byte, so a field declared `u8 a:3, b:5` puts `a` at shift 5 and `b`
/// at shift 0; the generator has already done that arithmetic.
pub(crate) enum SK {
    /// Unsigned big-endian integer of `width` bytes.
    Uint { width: u8 },
    /// `bits`-wide unsigned field at `shift`.
    Bits { shift: u8, bits: u8 },
    /// Whole 1-byte flag: any non-zero value is true. Unused by the current
    /// table — every CHIRP boolean happens to be bit-packed — but the generator
    /// emits it for an unpacked one, so it stays part of the vocabulary.
    #[allow(dead_code)]
    Bool,
    /// Single bit at `shift`.
    BoolBit { shift: u8 },
    /// Enumerated whole-byte value mapped to a label.
    Enum {
        width: u8,
        labels: &'static [(u32, &'static str)],
    },
    /// Enumerated bitfield mapped to a label.
    EnumBits {
        shift: u8,
        bits: u8,
        labels: &'static [(u32, &'static str)],
    },
    /// Fixed-length ASCII text, `0xFF`- or NUL-padded.
    Text { len: u32 },
}

include!("ft5d_settings_table.rs");

fn read_uint(image: &[u8], at: usize, width: u8) -> u32 {
    let mut v = 0u32;
    for i in 0..width as usize {
        v = (v << 8) | *image.get(at + i).unwrap_or(&0) as u32;
    }
    v
}

fn label_for(labels: &[(u32, &'static str)], raw: u32) -> Value {
    match labels.iter().find(|(v, _)| *v == raw) {
        Some((_, l)) => Value::String((*l).to_string()),
        // Pass an unrecognised value through as its number rather than
        // mislabelling it: the FT5D has at least one enum (digital popup) whose
        // range runs past the FT3D list CHIRP was written against.
        None => Value::String(raw.to_string()),
    }
}

/// Read one field out of the image, shaped like the profile form.
fn decode_field(image: &[u8], f: &SF) -> Value {
    let at = f.byte as usize;
    match &f.kind {
        SK::Uint { width } => Value::from(read_uint(image, at, *width)),
        SK::Bits { shift, bits } => Value::from((image[at] >> shift) & ((1u8 << bits) - 1)),
        SK::Bool => Value::Bool(image[at] != 0),
        SK::BoolBit { shift } => Value::Bool((image[at] >> shift) & 1 == 1),
        SK::Enum { width, labels } => label_for(labels, read_uint(image, at, *width)),
        SK::EnumBits {
            shift,
            bits,
            labels,
        } => label_for(labels, ((image[at] >> shift) & ((1u8 << bits) - 1)) as u32),
        SK::Text { len } => {
            let end = (at + *len as usize).min(image.len());
            let raw = &image[at..end];
            let cut = raw
                .iter()
                .position(|&b| b == 0xFF || b == 0)
                .unwrap_or(raw.len());
            Value::String(String::from_utf8_lossy(&raw[..cut]).trim_end().to_string())
        }
    }
}

/// Decode every known setting out of a microSD image, shaped like the profile
/// form. Unknown or out-of-range enum values come back as their raw number.
pub(crate) fn decode_settings(image: &[u8]) -> Value {
    let mut out = Map::new();
    for f in FT5D_SETTINGS_FIELDS {
        if (f.byte as usize) >= image.len() {
            continue;
        }
        out.insert(f.key.to_string(), decode_field(image, f));
    }
    Value::Object(out)
}

/// Write a profile's settings into a microSD image, returning how many fields
/// were applied. Keys the table does not know, and values of the wrong shape,
/// are skipped rather than guessed at — a profile saved against an older schema
/// must not corrupt the image.
pub(crate) fn apply_settings(image: &mut [u8], settings: &Map<String, Value>) -> usize {
    let mut written = 0;
    for f in FT5D_SETTINGS_FIELDS {
        let Some(v) = settings.get(f.key) else {
            continue;
        };
        let at = f.byte as usize;
        if at >= image.len() {
            continue;
        }
        // A field whose stored value already matches is left ALONE, not
        // rewritten with the same value. Re-encoding is not byte-neutral —
        // `write_text` pads differently than the radio does — so an unchanged
        // MYCALL still went from "WW8L      " to "WW8L\xff\xff\xff\xff\xff\xff"
        // and the radio came up asking for a callsign. In a writer that patches
        // the operator's own image, "no change" must mean "no bytes touched".
        if decode_field(image, f) == *v {
            written += 1;
            continue;
        }
        let ok = match &f.kind {
            SK::Uint { width } => match v.as_u64() {
                Some(n) => {
                    write_uint(image, at, *width, n as u32);
                    true
                }
                None => false,
            },
            SK::Bits { shift, bits } => match v.as_u64() {
                Some(n) => {
                    write_bits(image, at, *shift, *bits, n as u8);
                    true
                }
                None => false,
            },
            SK::Bool => match v.as_bool() {
                Some(b) => {
                    image[at] = b as u8;
                    true
                }
                None => false,
            },
            SK::BoolBit { shift } => match v.as_bool() {
                Some(b) => {
                    write_bits(image, at, *shift, 1, b as u8);
                    true
                }
                None => false,
            },
            SK::Enum { width, labels } => match raw_for(labels, v) {
                Some(raw) => {
                    write_uint(image, at, *width, raw);
                    true
                }
                None => false,
            },
            SK::EnumBits {
                shift,
                bits,
                labels,
            } => match raw_for(labels, v) {
                Some(raw) => {
                    write_bits(image, at, *shift, *bits, raw as u8);
                    true
                }
                None => false,
            },
            SK::Text { len } => match v.as_str() {
                Some(s) => {
                    write_text(image, at, *len as usize, s);
                    true
                }
                None => false,
            },
        };
        if ok {
            written += 1;
        }
    }
    written
}

/// The stored number behind a form value: a label from the option list, or the
/// passthrough decimal string `decode_settings` emits for unknown values.
fn raw_for(labels: &[(u32, &'static str)], v: &Value) -> Option<u32> {
    if let Some(s) = v.as_str() {
        if let Some((raw, _)) = labels.iter().find(|(_, l)| *l == s) {
            return Some(*raw);
        }
        return s.parse().ok();
    }
    v.as_u64().map(|n| n as u32)
}

fn write_uint(image: &mut [u8], at: usize, width: u8, v: u32) {
    for i in 0..width as usize {
        let shift = 8 * (width as usize - 1 - i);
        image[at + i] = ((v >> shift) & 0xFF) as u8;
    }
}

fn write_bits(image: &mut [u8], at: usize, shift: u8, bits: u8, v: u8) {
    let mask = ((1u16 << bits) - 1) as u8;
    image[at] = (image[at] & !(mask << shift)) | ((v & mask) << shift);
}

/// ASCII, `0xFF`-padded — the padding Yaesu uses for callsigns and the opening
/// message alike.
/// Text fields do not share one padding convention: the radio writes MYCALL
/// space-padded and leaves an unset opening message all-`0xFF`. Imposing either
/// one everywhere rewrites the tail of a field whose text did not change, so the
/// pad byte is taken from whatever is already in the field and only falls back
/// to `0xFF` when the current contents give no answer.
fn pad_byte(image: &[u8], at: usize, len: usize) -> u8 {
    match image[at..at + len].last() {
        Some(&b @ (0x20 | 0x00 | 0xFF)) => b,
        _ => 0xFF,
    }
}

fn write_text(image: &mut [u8], at: usize, len: usize, s: &str) {
    let pad = pad_byte(image, at, len);
    for i in 0..len {
        image[at + i] = pad;
    }
    for (i, ch) in s
        .chars()
        .filter(|c| c.is_ascii_graphic() || *c == ' ')
        .take(len)
        .enumerate()
    {
        image[at + i] = ch as u8;
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Every generated key must be unique — a duplicate would make the profile
    /// form silently drop one field and the writer apply the wrong offset.
    #[test]
    fn field_keys_are_unique() {
        let mut keys: Vec<&str> = FT5D_SETTINGS_FIELDS.iter().map(|f| f.key).collect();
        let before = keys.len();
        keys.sort_unstable();
        keys.dedup();
        assert_eq!(keys.len(), before, "duplicate key in FT5D_SETTINGS_FIELDS");
        assert!(before >= 60, "table looks truncated: {before} fields");
    }

    /// The seeded schema and the decode table are generated together; if they
    /// ever diverge, the form shows fields the writer ignores (or vice versa).
    #[test]
    fn schema_and_table_cover_the_same_keys() {
        let schema: Vec<serde_json::Value> =
            serde_json::from_str(crate::seed::FT5D_SETTINGS_SCHEMA).expect("schema parses");
        let mut in_schema: Vec<String> = schema
            .iter()
            .filter(|f| f["type"] != "section")
            .map(|f| f["key"].as_str().unwrap_or_default().to_string())
            .collect();
        let mut in_table: Vec<String> = FT5D_SETTINGS_FIELDS
            .iter()
            .map(|f| f.key.to_string())
            .collect();
        in_schema.sort();
        in_table.sort();
        assert_eq!(in_schema, in_table);
    }

    /// Round-trip through the shapes the profile form actually produces: a
    /// select label, a bitfield select, a boolean bit, and 0xFF-padded text.
    #[test]
    fn settings_round_trip_through_the_image() {
        let mut img = vec![0u8; 0x20000];
        let mut s = Map::new();
        s.insert("squelch-vfo-a".into(), Value::from(9u32));
        s.insert("mycall-callsign".into(), Value::from("W1AW"));
        s.insert("opening-message-flag".into(), Value::from("Message"));
        s.insert("aprs-aprs-units-temperature-f".into(), Value::from("F"));
        s.insert("beep-settings-beep-select".into(), Value::from("Key"));
        s.insert("aprs-aprs-mute".into(), Value::Bool(true));

        let n = apply_settings(&mut img, &s);
        assert_eq!(n, 6, "every field applied");

        let back = decode_settings(&img);
        assert_eq!(back["squelch-vfo-a"], Value::from("9"));
        assert_eq!(back["mycall-callsign"], Value::from("W1AW"));
        assert_eq!(back["opening-message-flag"], Value::from("Message"));
        assert_eq!(back["aprs-aprs-units-temperature-f"], Value::from("F"));
        assert_eq!(back["beep-settings-beep-select"], Value::from("Key"));
        assert_eq!(back["aprs-aprs-mute"], Value::Bool(true));
    }

    /// The failure that sent a real FT5D back to its first-boot callsign
    /// prompt. The radio stores MYCALL space-padded; the profile held the same
    /// callsign it had just been read from; and applying it rewrote the field
    /// `0xFF`-padded, changing six bytes for a value nobody edited. A setting
    /// that already matches must cost zero bytes.
    #[test]
    fn writing_an_unchanged_setting_touches_no_bytes() {
        const MYCALL: usize = 0xCEC6;
        let mut img = vec![0u8; 0x20000];
        img[MYCALL..MYCALL + 10].copy_from_slice(b"WW8L      ");
        let before = img.clone();

        let mut s = Map::new();
        s.insert("mycall-callsign".into(), Value::from("WW8L"));
        assert_eq!(apply_settings(&mut img, &s), 1, "still counts as applied");
        assert_eq!(img, before, "an unchanged value must not move a single byte");
    }

    /// When the text genuinely does change, the field keeps the padding the
    /// radio itself used rather than being forced to one convention.
    #[test]
    fn changed_text_keeps_the_fields_existing_padding() {
        const MYCALL: usize = 0xCEC6;
        let mut img = vec![0u8; 0x20000];
        img[MYCALL..MYCALL + 10].copy_from_slice(b"WW8L      ");

        let mut s = Map::new();
        s.insert("mycall-callsign".into(), Value::from("W1AW"));
        apply_settings(&mut img, &s);
        assert_eq!(&img[MYCALL..MYCALL + 10], b"W1AW      ", "space-padded");

        // A field the radio leaves 0xFF-filled keeps that instead.
        let mut img = vec![0xFFu8; 0x20000];
        let mut s = Map::new();
        s.insert("opening-message-message-padded-yaesu".into(), Value::from("HI"));
        apply_settings(&mut img, &s);
        assert_eq!(&img[0x478..0x488], b"HI\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff");
    }

    /// A bitfield write must not disturb its neighbours: six unit selectors
    /// share the single byte at 0xBECC, so clobbering it would silently switch
    /// the radio to metric.
    #[test]
    fn bitfield_writes_leave_neighbours_alone() {
        let mut img = vec![0u8; 0x20000];
        img[0xBECC] = 0b1111_1111; // every unit on its second option
        let mut s = Map::new();
        s.insert("aprs-aprs-units-rain-inch".into(), Value::from("mm"));
        apply_settings(&mut img, &s);

        let back = decode_settings(&img);
        assert_eq!(back["aprs-aprs-units-rain-inch"], Value::from("mm"));
        assert_eq!(back["aprs-aprs-units-temperature-f"], Value::from("F"));
        assert_eq!(back["aprs-aprs-units-altitude-ft"], Value::from("ft"));
        assert_eq!(back["aprs-aprs-units-distance-m"], Value::from("mile"));
    }

    /// A key the table does not know, or a value of the wrong type, is skipped.
    /// Profiles outlive schemas, and a stale one must not corrupt the image.
    #[test]
    fn unknown_keys_and_wrong_types_are_skipped() {
        let mut img = vec![0u8; 0x20000];
        let mut s = Map::new();
        s.insert("not-a-real-setting".into(), Value::from(1u32));
        s.insert("squelch-vfo-a".into(), Value::Bool(true)); // wrong shape
        assert_eq!(apply_settings(&mut img, &s), 0);
        assert!(img.iter().all(|&b| b == 0), "image untouched");
    }
}
