//! AnyTone AT-D890UV **non-channel settings** (the "radio profile") — read-only.
//!
//! The D890UV keeps its menu/global settings in a 0x200-byte "General Settings"
//! struct at `0x03500000`. This module decodes that struct into the same
//! profile-form shape (`RadioSettingsRead`) the UV-5R/TD-H3 settings-read path
//! produces, so "Download from radio" in the profile editor works uniformly
//! across radios.
//!
//! The field table (`ANYTONE_SETTINGS_FIELDS`) is GENERATED by
//! `scratchpad/gen_anytone_settings.py`, which walks the dmr-tools d890uv v1.05
//! `<element at="3500000h">` definition and computes each field's byte/bit
//! offset (handling 1/2/4-byte little-endian ints, MSB-first bit packing, nested
//! `repeat`/`element` groups, and reserved gaps). The whole struct sums to
//! exactly 0x200 bytes, matching a golden radio dump, and the seed schema JSON
//! (`radio_models.non_channel_settings_schema`) is generated from the SAME source
//! so the UI schema and this decoder cannot drift.
//!
//! WRITE-BACK (encoding settings and pushing them via the Program dialog's
//! Profile payload) is intentionally NOT in this module yet — it is brick-capable
//! and lands in a later pass with backup + fresh-session verify, like the channel
//! program flow.

use tauri::{AppHandle, Manager, State};

use crate::commands::anytone::read_windows_raw;
use crate::commands::program::RadioSettingsRead;
use crate::db::AppState;
use crate::error::MapErrString;
// Settings decode/encode + field table live in the driver (Chunk 3.5);
// re-exported so `commands::anytone_settings::*` keeps resolving for the RE
// examples and anytone_program.rs until 3.6.
pub use crate::radios::anytone_atd890uv::settings::*;

/// Read the AT-D890UV's General Settings from the radio and decode them into the
/// profile's shape. Mirrors `program::read_radio_settings` /
/// `tdh3::read_tdh3_settings_for_profile`: model-gated, saves a raw backup of the
/// captured region before returning. Read-only — no writes to the radio.
#[tauri::command]
pub async fn read_anytone_settings_for_profile(
    app: AppHandle,
    state: State<'_, AppState>,
    profile_id: i64,
    port: String,
) -> Result<RadioSettingsRead, String> {
    let row: Option<(String, String)> = sqlx::query_as(
        "SELECT rm.model, rp.display_name \
         FROM radio_profiles rp JOIN radio_models rm ON rm.id = rp.radio_model_id \
         WHERE rp.id = ?1",
    )
    .bind(profile_id)
    .fetch_optional(&state.pool)
    .await
    .estr()?;
    let (model, profile_name) = row.ok_or("radio profile not found")?;
    if model != "AT-D890UV" {
        return Err(format!(
            "Reading settings over the AnyTone cable supports the AT-D890UV only (this profile is a {model})."
        ));
    }

    let backup_dir = app.path().app_data_dir().estr()?.join("radio-backups");
    std::fs::create_dir_all(&backup_dir).estr()?;
    let stamp = chrono::Local::now().format("%Y%m%d-%H%M%S");
    let slug: String = profile_name
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '-' })
        .collect();
    let backup_path = backup_dir.join(format!("anytone-settings-{slug}-{stamp}.bin"));

    tauri::async_runtime::spawn_blocking(move || {
        let blocks = read_windows_raw(&port, SETTINGS_WINDOWS)?;
        if blocks.is_empty() {
            return Err("radio returned no settings data".into());
        }

        // Self-describing [addr:BE][len:BE][data] backup per window, matching the
        // dump/diff tooling so it round-trips through the same parsers.
        let mut dump = Vec::new();
        for (addr, data) in &blocks {
            dump.extend_from_slice(&addr.to_be_bytes());
            dump.extend_from_slice(&(data.len() as u32).to_be_bytes());
            dump.extend_from_slice(data);
        }
        std::fs::write(&backup_path, &dump)
            .map_err(|e| format!("could not write backup {}: {e}", backup_path.display()))?;

        let settings = decode_anytone_settings(&blocks);
        let count = settings.as_object().map(|o| o.len()).unwrap_or(0);
        Ok(RadioSettingsRead {
            settings,
            count,
            backup_path: backup_path.to_string_lossy().to_string(),
        })
    })
    .await
    .estr()?
}

