// GENERATED by scratchpad/kenwood_thd72/gen_thd72_settings.py from
// scratchpad/kenwood_thd72/MEASURED.md. Do not hand-edit; regenerate.
//
// `mu` is a 0-BASED INDEX into the 19 comma-separated parameters of an
// `MU` line -- not a byte offset. The TH-D72's settings are read and
// written as that one ASCII command, because it covers all 19 menu
// parameters where CHIRP's image struct names offsets for only 6. The
// two were cross-checked on a real radio and agree 6 of 6, three of
// them on values that differ from the factory image.
//
// ⚠ `MU` is HEX. The lamp timer, the battery saver and both restart
// timers reach 10, which the radio renders as `A`. A decimal parse
// would silently reject a radio set to 10 seconds.
//
// ⚠ Enum labels cover the WHOLE range, not just the ends. Ten TH-D75
// fields once shipped carrying only their two endpoints because a
// `First=0 ... Last=N` row parsed as a two-value enum.
//
// A menu number ending in `?` is UNCERTAIN: it came from the manual's
// two-column PDF, whose text extraction bleeds between sections. `None`
// means no menu number is known. Menu numbers are documentation -- a
// wrong one mislabels a form field, it does not write a wrong value.
//
// NOT the radio's complete settings set: CHIRP reads `lamp_control` out
// of the image at 0x339 and there is no `MU` parameter for it.
pub(crate) const THD72_SETTINGS_FIELDS: &[MF] = &[
    MF { key: "lamp-timer", label: "Illumination timer (seconds)", mu: 0, menu: Some("101"), kind: MK::Uint { min: 2, max: 10 } },  // MU p1; menu confirmed; values inferred
    MF { key: "battery-saver", label: "Battery saver", mu: 2, menu: Some("110"), kind: MK::Enum { labels: &[(0, "Off"), (1, "0.03s"), (2, "0.2s"), (3, "0.4s"), (4, "0.6s"), (5, "0.8s"), (6, "1.0s"), (7, "2.0s"), (8, "3.0s"), (9, "4.0s"), (10, "5.0s")] } },  // MU p3; menu confirmed; values inferred (two sources agree)
    MF { key: "apo", label: "Auto power off", mu: 3, menu: Some("111"), kind: MK::Enum { labels: &[(0, "Off"), (1, "15 minutes"), (2, "30 minutes"), (3, "60 minutes")] } },  // MU p4; menu confirmed on screen; values MEASURED
    MF { key: "key-beep", label: "Key beep", mu: 4, menu: Some("121"), kind: MK::Enum { labels: &[(0, "Off"), (1, "Radio & GPS"), (2, "Radio only"), (3, "GPS only")] } },  // MU p5; menu confirmed; values inferred (two sources agree)
    MF { key: "vhf-aip", label: "VHF AIP", mu: 5, menu: Some("132"), kind: MK::Bool },  // MU p6; menu confirmed; values inferred
    MF { key: "uhf-aip", label: "UHF AIP", mu: 6, menu: Some("133"), kind: MK::Bool },  // MU p7; menu confirmed; values inferred
    MF { key: "vox", label: "VOX", mu: 7, menu: Some("134"), kind: MK::Bool },  // MU p8; menu confirmed; values inferred
    MF { key: "vox-gain", label: "VOX gain", mu: 8, menu: None, kind: MK::Uint { min: 0, max: 9 } },  // MU p9; menu unknown; values inferred
    MF { key: "vox-delay", label: "VOX delay", mu: 9, menu: Some("136?"), kind: MK::Enum { labels: &[(0, "250 ms"), (1, "500 ms"), (2, "750 ms"), (3, "1000 ms"), (4, "1500 ms"), (5, "2000 ms"), (6, "3000 ms")] } },  // MU p10; menu uncertain; values inferred
    MF { key: "vox-on-busy", label: "VOX on busy", mu: 10, menu: Some("137"), kind: MK::Bool },  // MU p11; menu confirmed; values inferred
    MF { key: "beat-shift", label: "Beat shift", mu: 11, menu: Some("138"), kind: MK::Enum { labels: &[(0, "Type 1"), (1, "Type 2"), (2, "Type 3"), (3, "Type 4"), (4, "Type 5"), (5, "Type 6"), (6, "Type 7"), (7, "Type 8")] } },  // MU p12; menu confirmed; values inferred (manual states Type 1~8, default Type 1)
    MF { key: "tx-inhibit", label: "TX inhibit", mu: 12, menu: Some("139"), kind: MK::Bool },  // MU p13; menu confirmed; values inferred
    MF { key: "balance", label: "Volume balance (A/B)", mu: 13, menu: Some("120"), kind: MK::Enum { labels: &[(0, "A"), (1, "A 50%"), (2, "Center"), (3, "B 50%"), (4, "B")] } },  // MU p14; menu confirmed on screen; values MEASURED
    MF { key: "recall-method", label: "Memory recall method", mu: 14, menu: Some("143?"), kind: MK::Enum { labels: &[(0, "All band"), (1, "Current band")] } },  // MU p15; menu uncertain; values inferred
    MF { key: "scan-resume", label: "Scan resume", mu: 15, menu: None, kind: MK::Enum { labels: &[(0, "Time"), (1, "Carrier"), (2, "Seek")] } },  // MU p16; menu unknown; values inferred
    MF { key: "time-restart", label: "Scan time restart (seconds)", mu: 16, menu: None, kind: MK::Uint { min: 1, max: 10 } },  // MU p17; menu unknown; values inferred
    MF { key: "carrier-restart", label: "Scan carrier restart (seconds)", mu: 17, menu: None, kind: MK::Uint { min: 1, max: 10 } },  // MU p18; menu unknown; values inferred
    MF { key: "auto-offset", label: "Automatic repeater offset", mu: 18, menu: None, kind: MK::Bool },  // MU p19; menu unknown; values inferred
];
