//! ID-5100 non-channel settings: the field table, read out of a clone image
//! and written back into one.
//!
//! Settings live in the same image the cable clones, so there is no separate
//! settings transport: a read is a download, and a write rides out inside the
//! codeplug program's upload (`carries_profile_settings`), exactly like the
//! UV-5R. The byte rules are Icom's — big-endian integers, space-padded text,
//! off = 0 / on = 1 — and the encoder is the ID-52's own
//! ([`decode_settings_with`] / [`apply_settings_with`]); only the table is this
//! radio's.
//!
//! ## Where the table came from
//!
//! GENERATED by `scratchpad/id5100/vm/gen_table.py` from the measurement files
//! beside it. Every address was measured by driving Icom's CS-5100 inside a VM:
//! move one control, save, diff, one byte per control — first a sweep of every
//! row of every settings page for the address, then a cycle of every option of
//! every dropdown for the stored values, each step's label read off a
//! screenshot of the grid. CS-5100's untouched defaults match the radio's own
//! factory-reset image byte for byte across the whole settings block, which is
//! what makes it trustworthy as an instrument; values it could only show, not
//! prove, are spot-checked on the radio's screen before they ship.

use serde_json::{Map, Value};

use crate::radios::driver::{
    with_restore_hint, SettingsCapture, SettingsReader, SettingsWriteReport, SettingsWriter,
};
use crate::radios::icom_id52::settings::{apply_settings_with, decode_settings_with, SF, SK};

use super::protocol;

include!("id5100_settings_table.rs");

/// Every setting the table knows, decoded out of a clone image and shaped like
/// the profile form.
pub(crate) fn decode(image: &[u8]) -> Value {
    let mut v = decode_settings_with(ID5100_SETTINGS_FIELDS, image);
    if let Some(map) = v.as_object_mut() {
        for (key, at) in POSITIONS {
            let (lat, lon, alt) = read_position(image, *at);
            map.insert(format!("{key}-latitude"), Value::String(lat));
            map.insert(format!("{key}-longitude"), Value::String(lon));
            map.insert(format!("{key}-altitude-m"), Value::String(alt));
        }
    }
    v
}

/// The three position records — GPS Manual Position, D-PRS Object, D-PRS Item —
/// share one 12-byte layout, each measured by typing 39°45'30"N 105°05'15"W
/// 1234 m into CS-5100 and diffing (textpass, 2026-10-02):
///
/// | +0 | +1 | +3 | +4 | +5 | +7 | +8 |
/// |---|---|---|---|---|---|---|
/// | lat deg | lat minutes × 1000 (u16 BE) | `N`/`S` | lon deg | lon minutes × 1000 | `E`/`W` | altitude, i32 BE, 0.1 ft; `7FFFFFFF` = unset |
///
/// `27 B1BC 'N' 69 1482 'W' 00009E26` = 39°45.500'N 105°05.250'W 4048.6 ft.
/// The form carries decimal degrees (negative = S / W) and metres.
pub(crate) const POSITIONS: &[(&str, usize)] = &[
    ("gps-manual-position", 0x29D85),
    ("d-prs-object-position", 0x29ED3),
    ("d-prs-item-position", 0x29F21),
];

const ALT_UNSET: i32 = 0x7FFF_FFFF;

fn read_position(image: &[u8], at: usize) -> (String, String, String) {
    let coord = |o: usize, neg: u8| {
        let deg = f64::from(image[at + o]);
        let mm = f64::from(u16::from_be_bytes([image[at + o + 1], image[at + o + 2]]));
        let v = deg + mm / 60_000.0;
        // Zero carries a hemisphere letter on the radio (an unset position is
        // 0°W) but has no sign; show it unsigned rather than as "-0.000000".
        let v = if image[at + o + 3] == neg && v != 0.0 { -v } else { v };
        format!("{v:.6}")
    };
    let alt = i32::from_be_bytes(image[at + 8..at + 12].try_into().unwrap());
    let alt = if alt == ALT_UNSET { String::new() } else { format!("{:.1}", f64::from(alt) * 0.03048) };
    (coord(0, b'S'), coord(4, b'W'), alt)
}

/// Encode one coordinate: degrees byte, minutes × 1000, hemisphere letter.
fn encode_coord(v: f64, max: f64, pos: u8, neg: u8) -> Option<[u8; 4]> {
    if !v.is_finite() || v.abs() > max {
        return None;
    }
    let a = v.abs();
    let mut deg = a.trunc();
    let mut mm = ((a - deg) * 60_000.0).round();
    if mm >= 60_000.0 {
        deg += 1.0;
        mm = 0.0;
    }
    let mm = mm as u16;
    Some([deg as u8, (mm >> 8) as u8, mm as u8, if v < 0.0 { neg } else { pos }])
}

/// Apply the position keys present in `applicable`, removing them so the
/// table writer never sees them. Returns how many fields were applied.
fn apply_positions(image: &mut [u8], applicable: &mut Map<String, Value>, notes: &mut Vec<String>) -> usize {
    let mut n = 0;
    for (key, at) in POSITIONS {
        for (suffix, off, max, pos, neg) in [("latitude", 0usize, 90.0, b'N', b'S'), ("longitude", 4, 180.0, b'E', b'W')] {
            let k = format!("{key}-{suffix}");
            let Some(v) = applicable.remove(&k) else { continue };
            // Blank is "leave alone", never a value: a profile that never held
            // this field must not warn about it, or rewrite it.
            if v.as_str().is_some_and(|s| s.trim().is_empty()) {
                continue;
            }
            let parsed = v.as_str().and_then(|s| s.trim().parse::<f64>().ok()).or_else(|| v.as_f64());
            match parsed.and_then(|f| encode_coord(f, max, pos, neg)) {
                Some(mut bytes) => {
                    // Zero has no hemisphere of its own: keep the letter the radio
                    // already holds, or a profile that never touched this field
                    // would rewrite the factory 0°W as 0°E.
                    if bytes[..3] == [0, 0, 0] {
                        bytes[3] = image[at + off + 3];
                    }
                    if image[at + off..at + off + 4] != bytes {
                        image[at + off..at + off + 4].copy_from_slice(&bytes);
                    }
                    n += 1;
                }
                None => notes.push(format!("{k}: {v} is not a {suffix} the radio can store; left as it was")),
            }
        }
        let k = format!("{key}-altitude-m");
        if let Some(v) = applicable.remove(&k) {
            let text = v.as_str().map(str::trim).unwrap_or_default().to_string();
            // Blank leaves the radio's altitude alone — including one it holds
            // that the profile never knew about. (The radio's own "unset" reads
            // back as blank, so leaving it alone keeps it unset too.)
            if text.is_empty() {
                continue;
            }
            let raw = text
                .parse::<f64>()
                .ok()
                .filter(|m| m.is_finite() && m.abs() < 100_000.0)
                .map(|m| (m / 0.03048).round() as i32);
            match raw {
                Some(raw) => {
                    let bytes = raw.to_be_bytes();
                    if image[at + 8..at + 12] != bytes {
                        image[at + 8..at + 12].copy_from_slice(&bytes);
                    }
                    n += 1;
                }
                None => notes.push(format!("{k}: {text:?} is not an altitude in metres; left as it was")),
            }
        }
    }
    n
}

/// Apply a profile's settings to an image about to be uploaded. Returns how
/// many fields were applied, and a note for every key the profile carried that
/// this table cannot write — reported, not silently dropped.
pub(crate) fn apply(image: &mut [u8], settings: &Value) -> (usize, Vec<String>) {
    let Some(map) = settings.as_object() else {
        return (0, vec!["the profile's settings were not an object; none were written".into()]);
    };
    let position_keys: Vec<String> = POSITIONS
        .iter()
        .flat_map(|(k, _)| ["latitude", "longitude", "altitude-m"].map(|s| format!("{k}-{s}")))
        .collect();
    let mut known: std::collections::HashSet<&str> =
        ID5100_SETTINGS_FIELDS.iter().map(|f| f.key).collect();
    known.extend(position_keys.iter().map(String::as_str));
    let notes: Vec<String> = map
        .keys()
        .filter(|k| !known.contains(k.as_str()))
        .map(|k| format!("setting \"{k}\" is not one the ID-5100 driver can write; left as the radio had it"))
        .collect();
    let mut notes: Vec<String> = notes;
    let mut applicable: Map<String, Value> = map
        .iter()
        .filter(|(k, v)| known.contains(k.as_str()) && !v.is_null())
        .map(|(k, v)| (k.clone(), v.clone()))
        .collect();
    normalize_call_signs(&mut applicable);
    enforce_limits(image, &mut applicable, &mut notes);
    let positions = apply_positions(image, &mut applicable, &mut notes);
    (positions + apply_settings_with(ID5100_SETTINGS_FIELDS, image, &applicable), notes)
}

/// My Call Sign entries the way CS-5100 stores them (textpass, 2026-10-02):
/// uppercased; anything but A-Z, 0-9 and `/` becomes a space; and a one-
/// character suffix after `-` or a space goes in the 8th column — typing
/// `ab/c-1!` stored `AB/C   1`, the D-STAR call + module/ID layout the app
/// already uses for repeaters (`util::pack_dstar_call`). The 4-character note
/// is filtered the same way (`x.y?` stored `X Y `).
fn normalize_call_signs(applicable: &mut Map<String, Value>) {
    let clean = |s: &str| -> String {
        s.chars()
            .map(|c| c.to_ascii_uppercase())
            .map(|c| if c.is_ascii_alphanumeric() || c == '/' || c == '-' || c == ' ' { c } else { ' ' })
            .collect()
    };
    for (k, v) in applicable.iter_mut() {
        if !k.starts_with("my-station-my-call-sign-m") || k.ends_with("-in-use") {
            continue;
        }
        let Some(s) = v.as_str() else { continue };
        let out = if k.ends_with("-note") {
            clean(s).replace('-', " ")
        } else {
            let c = clean(s);
            let c = c.trim();
            match c.rsplit_once(['-', ' ']) {
                Some((call, sfx)) if sfx.chars().count() == 1 && !call.trim().is_empty() => {
                    format!("{:<7.7}{}", call.trim().replace('-', " "), sfx)
                }
                _ => c.replace('-', " "),
            }
        };
        *v = Value::String(out);
    }
}

/// Groups of checkboxes whose COMBINATION CS-5100 restricts: it greys out OK
/// on a fifth NMEA sentence and on an empty logger sentence list. A value the
/// radio would refuse is not a small error here — it rejects the whole clone
/// and factory-resets (FINDINGS, 2026-10-01) — so a profile that would end in
/// a refused combination leaves that whole group exactly as the radio has it.
const LIMITS: &[(&str, &[&str], usize, usize)] = &[
    (
        "GPS TX (NMEA) sentences",
        &[
            "gps-tx-nmea-sentence-rmc",
            "gps-tx-nmea-sentence-gga",
            "gps-tx-nmea-sentence-gll",
            "gps-tx-nmea-sentence-gsa",
            "gps-tx-nmea-sentence-vtg",
            "gps-tx-nmea-sentence-gsv",
        ],
        0,
        4,
    ),
    (
        "GPS Logger record sentences",
        &[
            "gps-logger-record-sentence-rmc",
            "gps-logger-record-sentence-gga",
            "gps-logger-record-sentence-vtg",
            "gps-logger-record-sentence-gsa",
        ],
        1,
        4,
    ),
];

fn enforce_limits(image: &[u8], applicable: &mut Map<String, Value>, notes: &mut Vec<String>) {
    let current = decode(image);
    for (name, keys, min, max) in LIMITS {
        if !keys.iter().any(|k| applicable.contains_key(*k)) {
            continue;
        }
        let ticked = keys
            .iter()
            .filter(|k| {
                applicable
                    .get(**k)
                    .or_else(|| current.get(**k))
                    .and_then(Value::as_bool)
                    .unwrap_or(false)
            })
            .count();
        if ticked < *min || ticked > *max {
            for k in *keys {
                applicable.remove(*k);
            }
            notes.push(format!(
                "{name}: the profile ticks {ticked}, and the ID-5100 allows {min}-{max}. \
                 Left as the radio has them — the radio rejects a clone carrying a \
                 combination it does not allow, and resets itself."
            ));
        }
    }
}

impl SettingsWriter for super::IcomId5100 {
    /// The profile's settings alone, channels untouched: the codeplug
    /// program's own steps with the channel build left out. Download and back
    /// up, apply the settings, clone the image back, then read back once the
    /// operator has pressed POWER (`after_write_instruction`) and count any
    /// written byte that did not stick. Nothing is cloned when no byte changed.
    fn write_settings(
        &self,
        port: &str,
        settings: &Value,
        _schema_json: &str,
        backup_dir: &std::path::Path,
    ) -> Result<SettingsWriteReport, String> {
        let stamp = chrono::Local::now().format("%Y%m%d-%H%M%S");
        let backup_path = backup_dir.join(format!("id5100-presettings-{stamp}.img"));
        let mut p = super::reopen(port)?;
        let base = protocol::download(&mut *p)?;
        std::fs::write(&backup_path, &base)
            .map_err(|e| format!("could not write backup {}: {e}", backup_path.display()))?;
        drop(p);

        let mut image = base.clone();
        let (fields_written, notes) = apply(&mut image, settings);
        let report = |verified, note: Option<String>| {
            let note = match (note, notes.is_empty()) {
                (n, true) => n,
                (None, false) => Some(notes.join("; ")),
                (Some(n), false) => Some(format!("{n} {}", notes.join("; "))),
            };
            SettingsWriteReport {
                fields_written,
                verified: Some(verified),
                note,
                backup_path: backup_path.to_string_lossy().to_string(),
                expected_path: None,
                windows_written: Vec::new(),
            }
        };
        if image == base {
            return Ok(report(
                true,
                Some("every setting already matched the radio — nothing was written".into()),
            ));
        }

        // The backstop every upload passes: one memory the radio cannot hold
        // makes it refuse the whole clone and factory-reset. These channels
        // came off the radio, so this passes by construction — it stays anyway.
        super::check_image(&image)?;

        let restore_hint = |e: String| {
            with_restore_hint(
                e,
                &backup_path,
                "Keep that file. Put it back with \"Restore backup…\" in the Program dialog.",
            )
        };
        let (verified, note) = super::clone_back_and_verify(port, &base, &image, restore_hint)?;
        Ok(report(verified, note))
    }
}

impl SettingsReader for super::IcomId5100 {
    /// One clone read: decoded for the form, and kept whole as the backup.
    fn read_settings(&self, port: &str, _schema_json: &str) -> Result<SettingsCapture, String> {
        // `reopen` waits out the radio's deaf seconds after a previous read.
        let mut p = super::reopen(port)?;
        let image = protocol::download(&mut *p)?;
        Ok(SettingsCapture {
            settings: decode(&image),
            backup: image,
            backup_ext: "img",
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// No two fields claim the same byte — a sweep that misread one row would
    /// show up here as a collision.
    #[test]
    fn no_two_settings_share_a_byte() {
        let mut seen = std::collections::HashMap::new();
        for f in ID5100_SETTINGS_FIELDS {
            let len = match &f.kind {
                SK::Text { len } | SK::TextFill { len, .. } => *len as usize,
                SK::Uint { width } | SK::Int { width } | SK::Enum { width, .. } | SK::IntEnum { width, .. } => *width as usize,
                SK::Bool => 1,
                SK::BoolBit { .. } => 0,
            };
            for b in f.byte as usize..f.byte as usize + len {
                if let Some(other) = seen.insert(b, f.key) {
                    panic!("{} and {} both claim {b:#x}", f.key, other);
                }
            }
        }
    }

    /// The profile form and the encoder are generated together; this holds them
    /// together. A form field with no table entry silently writes nothing, and
    /// a table entry with no form field is a setting nobody can reach.
    #[test]
    fn the_schema_and_the_table_agree_field_for_field() {
        let schema: Vec<Value> =
            serde_json::from_str(crate::seed::ID5100_SETTINGS_SCHEMA).expect("schema parses");
        let is_position = |k: &str| POSITIONS.iter().any(|(p, _)| k.starts_with(p));
        let form: Vec<&Value> = schema
            .iter()
            .filter(|f| f["type"] != "section" && !is_position(f["key"].as_str().unwrap()))
            .collect();
        assert_eq!(form.len(), ID5100_SETTINGS_FIELDS.len());
        // Every position key the codec handles has a form field, and no more.
        let pos_form: Vec<&str> = schema
            .iter()
            .map(|f| f["key"].as_str().unwrap())
            .filter(|k| is_position(k))
            .collect();
        assert_eq!(pos_form.len(), POSITIONS.len() * 3);
        for f in &form {
            let key = f["key"].as_str().unwrap();
            let t = ID5100_SETTINGS_FIELDS
                .iter()
                .find(|t| t.key == key)
                .unwrap_or_else(|| panic!("form field {key} has no table entry"));
            match (&t.kind, f["type"].as_str().unwrap()) {
                (SK::Bool | SK::BoolBit { .. }, "boolean") => {}
                (SK::Uint { width }, "integer") => {
                    let max = f["max"].as_u64().expect("an integer field has a max");
                    assert!(max < 1u64 << (8 * u32::from(*width)), "{key}: max {max} does not fit {width} byte(s)");
                }
                (SK::IntEnum { labels, .. }, "select") => {
                    let opts: Vec<&str> =
                        f["options"].as_array().unwrap().iter().map(|o| o.as_str().unwrap()).collect();
                    let table: Vec<&str> = labels.iter().map(|(_, l)| *l).collect();
                    assert_eq!(opts, table, "{key}: form options differ from the table's labels");
                }
                (SK::Text { len } | SK::TextFill { len, .. }, "text") => {
                    assert_eq!(f["max_length"].as_u64(), Some(u64::from(*len)), "{key}: max_length");
                }
                (SK::Enum { labels, .. }, "select") => {
                    let opts: Vec<&str> =
                        f["options"].as_array().unwrap().iter().map(|o| o.as_str().unwrap()).collect();
                    let table: Vec<&str> = labels.iter().map(|(_, l)| *l).collect();
                    assert_eq!(opts, table, "{key}: form options differ from the table's labels");
                }
                (_, ty) => panic!("{key}: table kind and form type {ty} do not pair"),
            }
        }
    }

    /// The measured input reproduces byte for byte in all three records, and
    /// reads back as what was typed.
    #[test]
    fn positions_encode_like_cs5100() {
        let mut image = vec![0u8; super::super::layout::IMAGE_LEN];
        let mut s = Map::new();
        for (k, _) in POSITIONS {
            s.insert(format!("{k}-latitude"), Value::from("39.758333"));
            s.insert(format!("{k}-longitude"), Value::from("-105.0875"));
            s.insert(format!("{k}-altitude-m"), Value::from("1234"));
        }
        let (n, notes) = apply(&mut image, &Value::Object(s));
        assert_eq!((n, notes.len()), (9, 0), "{notes:?}");
        for (k, at) in POSITIONS {
            assert_eq!(
                &image[*at..*at + 12],
                &[0x27, 0xB1, 0xBC, b'N', 0x69, 0x14, 0x82, b'W', 0x00, 0x00, 0x9E, 0x26],
                "{k}"
            );
            let d = decode(&image);
            assert_eq!(d[format!("{k}-latitude")], "39.758333");
            assert_eq!(d[format!("{k}-longitude")], "-105.087500");
        }
        // The radio's unset position — 0°N 0°W — reads back unsigned and
        // round-trips without its W being rewritten as E.
        let mut blank = vec![0u8; super::super::layout::IMAGE_LEN];
        blank[0x29D85..0x29D91].copy_from_slice(&[0, 0, 0, b'N', 0, 0, 0, b'W', 0x7F, 0xFF, 0xFF, 0xFF]);
        let d = decode(&blank);
        assert_eq!(d["gps-manual-position-longitude"], "0.000000");
        let before = blank.clone();
        apply(&mut blank, &d);
        assert_eq!(blank, before, "an untouched decode must write back nothing");
        // Blank means "leave alone" for all three, with no note: a real
        // altitude survives, and so does a coordinate.
        let mut s = Map::new();
        for f in ["latitude", "longitude", "altitude-m"] {
            s.insert(format!("d-prs-item-position-{f}"), Value::from(""));
        }
        let before = image.clone();
        let (n, notes) = apply(&mut image, &Value::Object(s));
        assert_eq!((n, notes.len()), (0, 0), "{notes:?}");
        assert_eq!(image, before);
    }

    /// The two measured CS-5100 inputs reproduce byte for byte.
    #[test]
    fn my_call_signs_are_stored_the_way_cs5100_stores_them() {
        let mut image = vec![b' '; super::super::layout::IMAGE_LEN];
        let mut s = Map::new();
        s.insert("my-station-my-call-sign-m02".into(), Value::from("ab/c-1!"));
        s.insert("my-station-my-call-sign-m02-note".into(), Value::from("x.y?"));
        s.insert("my-station-my-call-sign-m01".into(), Value::from("WW8L"));
        let (n, notes) = apply(&mut image, &Value::Object(s));
        assert_eq!((n, notes.len()), (3, 0));
        assert_eq!(&image[0x22168..0x22174], b"AB/C   1X Y ");
        assert_eq!(&image[0x2215C..0x22164], b"WW8L    ");
    }

    /// A fifth NMEA sentence is refused as a group; four is written.
    #[test]
    fn nmea_sentences_are_capped_at_four() {
        let mut image = vec![0u8; super::super::layout::IMAGE_LEN];
        image[0x29ACF] = 1; // GGA, the factory default
        let mut s = Map::new();
        for k in ["rmc", "gll", "gsa", "vtg"] {
            s.insert(format!("gps-tx-nmea-sentence-{k}"), Value::Bool(true));
        }
        let (_, notes) = apply(&mut image, &Value::Object(s.clone()));
        assert_eq!(notes.len(), 1, "{notes:?}");
        assert_eq!(&image[0x29ACE..0x29AD4], &[0, 1, 0, 0, 0, 0], "nothing written");
        s.insert("gps-tx-nmea-sentence-gga".into(), Value::Bool(false));
        let (_, notes) = apply(&mut image, &Value::Object(s));
        assert!(notes.is_empty(), "{notes:?}");
        assert_eq!(&image[0x29ACE..0x29AD4], &[1, 0, 1, 1, 1, 0]);
    }

    /// The logger needs at least one sentence.
    #[test]
    fn logger_needs_at_least_one_sentence() {
        let mut image = vec![0u8; super::super::layout::IMAGE_LEN];
        image[0x29AAD] = 0xF0;
        let mut s = Map::new();
        for k in ["rmc", "gga", "vtg", "gsa"] {
            s.insert(format!("gps-logger-record-sentence-{k}"), Value::Bool(false));
        }
        let (_, notes) = apply(&mut image, &Value::Object(s));
        assert_eq!(notes.len(), 1);
        assert_eq!(image[0x29AAD], 0xF0);
    }

    /// Object and item names pad with 0xFF, not spaces — what CS-5100 wrote
    /// when "AB" was typed over a 9-character name: 41 42 FF FF FF FF FF FF FF.
    #[test]
    fn object_names_pad_with_ff_like_the_radio() {
        let mut image = vec![0u8; super::super::layout::IMAGE_LEN];
        image[0x29E9C..0x29EA5].copy_from_slice(b"OBJABCDEF");
        let mut s = Map::new();
        s.insert("d-prs-object-object-name".into(), Value::from("AB"));
        let (n, notes) = apply(&mut image, &Value::Object(s));
        assert_eq!((n, notes.len()), (1, 0));
        assert_eq!(&image[0x29E9C..0x29EA5], &[0x41, 0x42, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF]);
        assert_eq!(decode(&image)["d-prs-object-object-name"], "AB");
    }

    /// Every schema entry, section headings included, has its own key — the
    /// form renders by key, and the Display/Sounds headings once collided.
    #[test]
    fn schema_keys_are_unique() {
        let schema: Vec<Value> = serde_json::from_str(crate::seed::ID5100_SETTINGS_SCHEMA).unwrap();
        let mut seen = std::collections::HashSet::new();
        for f in &schema {
            let k = f["key"].as_str().unwrap();
            assert!(seen.insert(k), "duplicate schema key {k}");
        }
    }

    /// Every field sits inside the image and clear of the memory area and its
    /// tables, which the codeplug build owns. (Not "above VOLATILE_BASE": My
    /// Call Sign lives at 0x2215C.)
    #[test]
    fn every_field_is_in_the_settings_area() {
        let memory_end = super::super::layout::BANK_NAMES
            + super::super::layout::BANK_COUNT * super::super::layout::BANK_NAME_LEN;
        for f in ID5100_SETTINGS_FIELDS {
            let at = f.byte as usize;
            assert!(at >= memory_end, "{} at {at:#x} is inside the memory area", f.key);
            assert!(at < super::super::layout::IMAGE_LEN, "{} at {at:#x}", f.key);
        }
    }
}
