//! AnyTone AT-D890UV non-channel settings ("radio profile"): the field table,
//! the General/Boot settings decode + encode, and the SettingsProgrammer device
//! I/O. Moved here from commands/anytone_settings.rs in Chunk 3.5. The Tauri
//! command layer (commands/anytone_settings.rs) keeps the DB + backup wrapper and
//! re-exports these items.
//!
//! The field table (ANYTONE_SETTINGS_FIELDS) is GENERATED by
//! scratchpad/gen_anytone_settings.py from the dmr-tools d890uv v1.05 General
//! Settings (0x03500000) + Boot Settings (0x03500900) definition; offsets are
//! validated against a golden radio dump and the seed schema JSON is generated
//! from the SAME source so the UI schema and this decoder cannot drift.

use serde_json::{Map, Value};

use super::RegionPatch;

/// Base of "Radio Id element 0" — the radio's own DMR ID + name. A `repeat` of
/// up to 250 records (stride 0x40) at `0x03680000`; each is a 4-byte big-endian
/// BCD DMR ID + a 16-char UTF-16LE name + padding. Every channel's "Radio ID
/// index" field defaults to 0, so element 0 is the ID the radio transmits with.
/// One ID is all a single-radio setup needs (matches RT Systems' one "Radio ID"
/// row), so we read/write only element 0.
pub const RADIO_ID_BASE: u32 = 0x0368_0000;
/// Base of the mirrored "Primary ID" record (same DMR ID + name, plus a "Used"
/// flag at +0x26). CPS writes both when you set a single radio ID; we do too.
pub const PRIMARY_ID_BASE: u32 = 0x0368_4000;

/// Settings regions read in one PC-mode session: General Settings, the small
/// firmware-confirmed Boot Settings block (boot text lines + boot password), and
/// the radio's own DMR-ID records (Radio Id element 0 + Primary ID). Adding the
/// ID records here folds them into the same read/decode + encode/write pipeline
/// as every other profile setting — no separate command needed.
/// `(absolute address, length)`.
pub const SETTINGS_WINDOWS: &[(u32, u32)] = &[
    (0x0350_0000, 0x200),
    (0x0350_0900, 0x60),
    (RADIO_ID_BASE, 0x40),
    (PRIMARY_ID_BASE, 0x40),
];

/// Profile-form key for the radio's own DMR ID (a plain integer).
pub const DMR_ID_KEY: &str = "dmr-id";
/// Profile-form key for the radio's own name/label (RT Systems' "Name" column).
pub const RADIO_NAME_KEY: &str = "radio-name";

/// Decode a big-endian packed-BCD integer (2 decimal digits/byte, most
/// significant byte first). Returns `None` if any nibble isn't a decimal digit
/// (e.g. a factory-blank 0xFF region), so an unset record reads as "no ID".
pub(crate) fn bcd_be_decode(b: &[u8]) -> Option<u32> {
    let mut val = 0u32;
    for &byte in b.iter().take(4) {
        let (hi, lo) = ((byte >> 4) as u32, (byte & 0x0F) as u32);
        if hi > 9 || lo > 9 {
            return None;
        }
        val = val * 100 + hi * 10 + lo;
    }
    Some(val)
}

/// Encode an integer as 4 bytes of big-endian packed BCD (8 decimal digits,
/// zero-padded). Values above 99,999,999 are truncated to their low 8 digits.
pub(crate) fn bcd_be_encode(mut v: u32) -> [u8; 4] {
    v %= 100_000_000;
    let mut digits = [0u8; 8];
    for d in digits.iter_mut().rev() {
        *d = (v % 10) as u8;
        v /= 10;
    }
    let mut out = [0u8; 4];
    for (i, chunk) in digits.chunks_exact(2).enumerate() {
        out[i] = (chunk[0] << 4) | chunk[1];
    }
    out
}

/// Decode up to 16 UTF-16LE code units into a String, stopping at the first NUL
/// or 0xFFFF (blank) unit.
pub(crate) fn radio_name_decode(b: &[u8]) -> String {
    let units: Vec<u16> = b
        .chunks_exact(2)
        .take(16)
        .map(|c| u16::from_le_bytes([c[0], c[1]]))
        .take_while(|&u| u != 0 && u != 0xFFFF)
        .collect();
    String::from_utf16_lossy(&units)
}

/// Encode a name as exactly 32 bytes of NUL-padded UTF-16LE (16 chars max).
pub(crate) fn radio_name_encode(s: &str) -> [u8; 32] {
    let mut out = [0u8; 32];
    for (i, u) in s.encode_utf16().take(16).enumerate() {
        out[i * 2..i * 2 + 2].copy_from_slice(&u.to_le_bytes());
    }
    out
}

/// One decodable setting: which region it lives in, where, and how to read it.
/// Values are shaped like the profile form — booleans, numbers, select labels,
/// or text.
pub(crate) struct SF {
    pub key: &'static str,
    /// Absolute base address of the region this field lives in (a
    /// `SETTINGS_WINDOWS` address).
    pub base: u32,
    /// Byte offset within that region.
    pub byte: u16,
    pub kind: SK,
}

pub(crate) enum SK {
    /// Unsigned little-endian integer of `width` bytes (1, 2, or 4).
    Uint { width: u8 },
    /// Whole 1-byte flag: any non-zero value is true.
    Bool,
    /// Single bit within a byte (MSB-first `lsb` index, 0 = LSB).
    BoolBit { lsb: u8 },
    /// `bits`-wide unsigned field starting at bit `lsb` within a byte. Not
    /// emitted for this block (its bitfields are all single-bit) but modeled so
    /// the generator can target other structs without a code change.
    #[allow(dead_code)]
    Bits { lsb: u8, bits: u8 },
    /// Enumerated 1-byte value mapped to a label; unknown raw values pass through
    /// as their decimal string.
    Enum {
        width: u8,
        labels: &'static [(u32, &'static str)],
    },
    /// Fixed-length ASCII text (`len` bytes), NUL-terminated.
    Text { len: u16 },
    /// Fixed-length UTF-16LE text (`chars` characters = 2×bytes), NUL-terminated.
    Utf16 { chars: u16 },
}

include!("anytone_settings_table.rs");

/// Read `width` little-endian bytes at `off` from the general-settings buffer.
pub(crate) fn read_le(buf: &[u8], off: usize, width: usize) -> u32 {
    let mut v = 0u32;
    for i in 0..width {
        if let Some(&b) = buf.get(off + i) {
            v |= (b as u32) << (8 * i);
        }
    }
    v
}

/// Decode the settings regions into a profile-form object keyed by the schema
/// keys. `windows` is the `(base_address, bytes)` list returned by
/// `read_windows_raw` for `SETTINGS_WINDOWS`; each field reads from the region
/// matching its `base`. Missing regions/bytes decode as empty/zero (defensive),
/// so a short or absent buffer never panics. `pub` so a CLI example can exercise
/// it on real hardware.
pub fn decode_anytone_settings(windows: &[(u32, Vec<u8>)]) -> Value {
    let region = |base: u32| -> &[u8] {
        windows
            .iter()
            .find(|(a, _)| *a == base)
            .map(|(_, d)| d.as_slice())
            .unwrap_or(&[])
    };
    let mut map = Map::new();
    for f in ANYTONE_SETTINGS_FIELDS {
        let buf = region(f.base);
        let off = f.byte as usize;
        let v = match &f.kind {
            SK::Uint { width } => Value::from(read_le(buf, off, *width as usize)),
            SK::Bool => Value::from(buf.get(off).copied().unwrap_or(0) != 0),
            SK::BoolBit { lsb } => {
                Value::from((buf.get(off).copied().unwrap_or(0) >> lsb) & 1 == 1)
            }
            SK::Bits { lsb, bits } => {
                let raw = (buf.get(off).copied().unwrap_or(0) >> lsb) & ((1u8 << bits) - 1);
                Value::from(raw)
            }
            SK::Enum { width, labels } => {
                let raw = read_le(buf, off, *width as usize);
                let label = labels
                    .iter()
                    .find(|(v, _)| *v == raw)
                    .map(|(_, l)| l.to_string())
                    .unwrap_or_else(|| raw.to_string());
                Value::from(label)
            }
            SK::Text { len } => {
                let end = (off + *len as usize).min(buf.len());
                let s: String = buf
                    .get(off..end)
                    .unwrap_or(&[])
                    .iter()
                    .take_while(|&&b| b != 0)
                    .map(|&b| b as char)
                    .collect();
                Value::from(s)
            }
            SK::Utf16 { chars } => {
                let end = (off + *chars as usize * 2).min(buf.len());
                let units: Vec<u16> = buf
                    .get(off..end)
                    .unwrap_or(&[])
                    .chunks_exact(2)
                    .map(|c| u16::from_le_bytes([c[0], c[1]]))
                    .take_while(|&u| u != 0)
                    .collect();
                Value::from(String::from_utf16_lossy(&units))
            }
        };
        map.insert(f.key.to_string(), v);
    }

    // The radio's own DMR ID + name live in a separate region (Radio Id element
    // 0) with a BCD-BE id and a UTF-16LE name, so they're decoded by hand rather
    // than via the generated field table. A blank/unset record reads as id 0.
    let rid = region(RADIO_ID_BASE);
    if rid.len() >= 0x24 {
        map.insert(
            DMR_ID_KEY.to_string(),
            Value::from(bcd_be_decode(&rid[0..4]).unwrap_or(0)),
        );
        map.insert(
            RADIO_NAME_KEY.to_string(),
            Value::from(radio_name_decode(&rid[4..0x24])),
        );
    }

    Value::Object(map)
}

/// Write `width` little-endian bytes of `v` at `off` into `buf` (bounds-safe).
pub(crate) fn write_le(buf: &mut [u8], off: usize, width: usize, v: u32) {
    for i in 0..width {
        if let Some(b) = buf.get_mut(off + i) {
            *b = (v >> (8 * i)) as u8;
        }
    }
}

/// Coerce a profile-form value into an unsigned int: numbers as-is, numeric
/// strings parsed, booleans as 0/1. `None` for anything unresolvable.
pub(crate) fn as_u32(v: &Value) -> Option<u32> {
    match v {
        Value::Number(n) => n.as_u64().map(|x| x as u32),
        Value::String(s) => s.trim().parse::<u32>().ok(),
        Value::Bool(b) => Some(*b as u32),
        _ => None,
    }
}

/// Coerce a profile-form value into a boolean: booleans as-is, numbers as
/// non-zero, "true"/"false"/numeric strings. `None` for anything unresolvable.
pub(crate) fn as_bool(v: &Value) -> Option<bool> {
    match v {
        Value::Bool(b) => Some(*b),
        Value::Number(n) => n.as_i64().map(|x| x != 0),
        Value::String(s) => match s.trim() {
            "true" => Some(true),
            "false" => Some(false),
            other => other.parse::<i64>().ok().map(|x| x != 0),
        },
        _ => None,
    }
}

/// Apply one field's value onto its byte(s) in `buf` (a mutable region copy).
/// Best-effort: an unresolvable value or an out-of-range offset leaves the bytes
/// untouched so a partial/odd profile can never corrupt the write. Bit and Bool
/// fields read-modify-write, preserving every unmodeled bit in the byte.
pub(crate) fn encode_field_into(buf: &mut [u8], off: usize, kind: &SK, v: &Value) {
    match kind {
        SK::Uint { width } => {
            if let Some(n) = as_u32(v) {
                write_le(buf, off, *width as usize, n);
            }
        }
        SK::Bool => {
            if let (Some(b), Some(byte)) = (as_bool(v), buf.get_mut(off)) {
                *byte = b as u8;
            }
        }
        SK::BoolBit { lsb } => {
            if let (Some(b), Some(byte)) = (as_bool(v), buf.get_mut(off)) {
                if b {
                    *byte |= 1 << lsb;
                } else {
                    *byte &= !(1 << lsb);
                }
            }
        }
        SK::Bits { lsb, bits } => {
            if let (Some(n), Some(byte)) = (as_u32(v), buf.get_mut(off)) {
                let mask = ((1u16 << bits) - 1) as u8;
                *byte = (*byte & !(mask << lsb)) | (((n as u8) & mask) << lsb);
            }
        }
        SK::Enum { width, labels } => {
            // Prefer the label→raw mapping; fall back to a decimal string (how
            // the decoder passes through raws with no label) or a numeric value.
            let raw = match v {
                Value::String(s) => labels
                    .iter()
                    .find(|(_, l)| *l == s)
                    .map(|(r, _)| *r)
                    .or_else(|| s.trim().parse::<u32>().ok()),
                _ => as_u32(v),
            };
            if let Some(raw) = raw {
                write_le(buf, off, *width as usize, raw);
            }
        }
        SK::Text { len } => {
            if let Some(s) = v.as_str() {
                let n = *len as usize;
                if off + n <= buf.len() {
                    let bytes = s.as_bytes();
                    for i in 0..n {
                        buf[off + i] = bytes.get(i).copied().filter(u8::is_ascii).unwrap_or(0);
                    }
                }
            }
        }
        SK::Utf16 { chars } => {
            if let Some(s) = v.as_str() {
                let n = *chars as usize;
                if off + n * 2 <= buf.len() {
                    buf[off..off + n * 2].fill(0);
                    for (i, u) in s.encode_utf16().take(n).enumerate() {
                        buf[off + i * 2..off + i * 2 + 2].copy_from_slice(&u.to_le_bytes());
                    }
                }
            }
        }
    }
}

/// Encode profile-form settings back into byte patches — the inverse of
/// [`decode_anytone_settings`], sharing the same `ANYTONE_SETTINGS_FIELDS` table
/// so the two cannot drift. `windows` is the CURRENT `(base, bytes)` state of the
/// settings regions (read fresh from the radio in the same PC-mode session as the
/// write); each modeled field is read-modify-written onto its region so every
/// unmodeled byte AND every unmodeled bit within a modeled byte is preserved.
/// Returns one [`RegionPatch`] per contiguous run of CHANGED bytes — fields whose
/// value already matches the radio produce no patch, so a no-op profile writes
/// nothing. Values absent from `values`, of the wrong type, or out of range are
/// skipped (never corrupting the image). `pub` so the program flow + a CLI
/// example can drive it against real hardware.
pub fn encode_anytone_settings(
    windows: &[(u32, Vec<u8>)],
    values: &Value,
) -> Result<Vec<RegionPatch>, String> {
    let obj = values
        .as_object()
        .ok_or("settings values is not a JSON object")?;

    // Mutable working copy of each region we were handed, plus the pristine
    // originals to diff against.
    let mut regions: std::collections::BTreeMap<u32, Vec<u8>> =
        windows.iter().map(|(b, d)| (*b, d.clone())).collect();
    let originals = regions.clone();

    for f in ANYTONE_SETTINGS_FIELDS {
        let Some(v) = obj.get(f.key) else { continue };
        let Some(buf) = regions.get_mut(&f.base) else {
            continue;
        };
        encode_field_into(buf, f.byte as usize, &f.kind, v);
    }

    // Radio's own DMR ID + name: a separate region (Radio Id element 0 + the
    // mirrored Primary ID) with a BCD-BE id + UTF-16LE name, so encoded by hand.
    // Only touched when the profile actually carries a non-zero dmr-id, so a
    // profile without one never disturbs whatever ID is already on the radio.
    if let Some(id) = obj.get(DMR_ID_KEY).and_then(as_u32).filter(|&id| id != 0) {
        let name = obj
            .get(RADIO_NAME_KEY)
            .and_then(Value::as_str)
            .unwrap_or_default();
        let bcd = bcd_be_encode(id);
        let name16 = radio_name_encode(name);
        if let Some(buf) = regions.get_mut(&RADIO_ID_BASE) {
            if buf.len() >= 0x24 {
                buf[0..4].copy_from_slice(&bcd);
                buf[4..0x24].copy_from_slice(&name16);
            }
        }
        if let Some(buf) = regions.get_mut(&PRIMARY_ID_BASE) {
            if buf.len() >= 0x27 {
                buf[0..4].copy_from_slice(&bcd);
                buf[4..0x24].copy_from_slice(&name16);
                buf[0x26] = 1; // Used flag
            }
        }
    }

    // Diff each region against its original into contiguous changed runs.
    let mut patches = Vec::new();
    for (base, buf) in &regions {
        let orig = &originals[base];
        let mut i = 0;
        while i < buf.len() {
            if buf[i] != orig[i] {
                let start = i;
                while i < buf.len() && buf[i] != orig[i] {
                    i += 1;
                }
                patches.push(RegionPatch {
                    addr: base + start as u32,
                    data: buf[start..i].to_vec(),
                });
            } else {
                i += 1;
            }
        }
    }
    Ok(patches)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Raw settings image captured from a golden radio (freshly RT-Systems-
    /// flashed): a contiguous 0x03500000 window covering both the General
    /// Settings (0x200) and Boot Settings (@0x900) regions — the ground truth
    /// the offset walk was validated against.
    const GOLDEN: &[u8] = include_bytes!("testdata/anytone_golden_settings.bin");

    /// Slice the golden image into the `(base, bytes)` window list the decoder
    /// expects (the same shape `read_windows_raw` returns from the radio).
    fn golden_windows() -> Vec<(u32, Vec<u8>)> {
        // The golden dump only covers the 0x03500000 region; the radio-id
        // windows (0x03680000+) aren't in it, so include only windows that fit.
        SETTINGS_WINDOWS
            .iter()
            .filter_map(|&(base, len)| {
                let start = base.checked_sub(0x0350_0000)? as usize;
                let end = start + len as usize;
                (end <= GOLDEN.len()).then(|| (base, GOLDEN[start..end].to_vec()))
            })
            .collect()
    }

    fn field(key: &str) -> &'static SF {
        ANYTONE_SETTINGS_FIELDS
            .iter()
            .find(|f| f.key == key)
            .unwrap_or_else(|| panic!("no field {key}"))
    }

    #[test]
    fn table_is_within_its_region_and_unique() {
        let mut seen = std::collections::HashSet::new();
        for f in ANYTONE_SETTINGS_FIELDS {
            assert!(seen.insert(f.key), "duplicate key {}", f.key);
            let region_len = SETTINGS_WINDOWS
                .iter()
                .find(|(a, _)| *a == f.base)
                .map(|(_, l)| *l as usize)
                .unwrap_or_else(|| panic!("field {} has unknown region 0x{:08X}", f.key, f.base));
            let w = match &f.kind {
                SK::Uint { width } | SK::Enum { width, .. } => *width as usize,
                SK::Text { len } => *len as usize,
                SK::Utf16 { chars } => *chars as usize * 2,
                _ => 1,
            };
            assert!(
                f.byte as usize + w <= region_len,
                "field {} runs past its region",
                f.key
            );
        }
    }

    #[test]
    fn decodes_known_golden_values() {
        let s = decode_anytone_settings(&golden_windows());
        let o = s.as_object().unwrap();
        // Enum labels resolve (validated against the radio / RT Systems).
        assert_eq!(o["boot-display"], Value::from("Custom Text")); // byte 0x06 = 1
        assert_eq!(o["frequency-step-size"], Value::from("5 kHz")); // byte 0x08 = 1
        assert_eq!(o["language"], Value::from("English")); // byte 0x05 = 0
        assert_eq!(o["pf1-short-press-function"], Value::from("Scan")); // 0x10 = 10
        // Integers, incl. a 4-byte little-endian frequency (400 MHz in 10 Hz).
        assert_eq!(o["boot-zone-a"], Value::from(3u32)); // byte 0x1F = 3
        assert_eq!(o["vfo-scan-uhf-min-frequency"], Value::from(40_000_000u32));
        // Bit-packed lock flags share byte 0x0BE (0x00 here → all false).
        assert_eq!(o["folk"], Value::from(false));
        assert_eq!(o["knlk"], Value::from(false));
        // A whole-byte boolean flag.
        assert_eq!(o["enable-gps"], Value::from(true)); // byte 0x28 = 1
        // Melody arrays decode as 2-byte LE (Call Permit first tone = 1000 Hz).
        assert_eq!(o["call-permit-melody-tones.frequency.0"], Value::from(1000u32));
        // Boot Settings region (0x03500900): UTF-16LE boot text lines.
        assert_eq!(o["boot-text-line-1"], Value::from("WW8L TIM"));
        assert_eq!(o["boot-text-line-2"], Value::from("555-000-0000"));
        assert_eq!(o["boot-password"], Value::from("")); // ASCII, empty here
    }

    /// Splice patches onto a copy of the window list (test mirror of the
    /// hardware `plans_from_pre_read` splice).
    fn apply_patches(windows: &mut [(u32, Vec<u8>)], patches: &[RegionPatch]) {
        for p in patches {
            for (base, buf) in windows.iter_mut() {
                if p.addr >= *base && (p.addr - *base) as usize + p.data.len() <= buf.len() {
                    let off = (p.addr - *base) as usize;
                    buf[off..off + p.data.len()].copy_from_slice(&p.data);
                }
            }
        }
    }

    #[test]
    fn encoding_freshly_decoded_values_is_a_no_op() {
        // Every field, re-encoded against the same bytes it decoded from, must
        // reproduce those bytes exactly — so a profile nobody edited writes
        // nothing. This is the strong inverse invariant over all 216 fields.
        let windows = golden_windows();
        let decoded = decode_anytone_settings(&windows);
        let patches = encode_anytone_settings(&windows, &decoded).unwrap();
        assert!(
            patches.is_empty(),
            "expected no patches, got {}: {:?}",
            patches.len(),
            patches
                .iter()
                .map(|p| format!("0x{:08X}+{}", p.addr, p.data.len()))
                .collect::<Vec<_>>()
        );
    }

    #[test]
    fn encode_then_decode_round_trips_edited_values() {
        let windows = golden_windows();
        let mut vals = decode_anytone_settings(&windows);
        // Touch one of every kind: bool byte, bitfield, enum label, uint, 4-byte
        // uint, ascii text, utf16 text.
        vals["enable-gps"] = Value::from(false);
        vals["folk"] = Value::from(true);
        vals["language"] = Value::from("Russian");
        vals["tot"] = Value::from(42u32);
        vals["vfo-scan-uhf-min-frequency"] = Value::from(43_000_000u32);
        vals["boot-password"] = Value::from("SECRET42");
        vals["boot-text-line-1"] = Value::from("HELLO");
        let patches = encode_anytone_settings(&windows, &vals).unwrap();

        let mut patched = windows.clone();
        apply_patches(&mut patched, &patches);
        let decoded = decode_anytone_settings(&patched);
        assert_eq!(decoded["enable-gps"], Value::from(false));
        assert_eq!(decoded["folk"], Value::from(true));
        assert_eq!(decoded["language"], Value::from("Russian"));
        assert_eq!(decoded["tot"], Value::from(42u32));
        assert_eq!(decoded["vfo-scan-uhf-min-frequency"], Value::from(43_000_000u32));
        assert_eq!(decoded["boot-password"], Value::from("SECRET42"));
        assert_eq!(decoded["boot-text-line-1"], Value::from("HELLO"));
        // Untouched neighbours survive.
        assert_eq!(decoded["boot-text-line-2"], Value::from("555-000-0000"));
        assert_eq!(decoded["knlk"], Value::from(false));
    }

    #[test]
    fn one_bit_change_patches_only_its_byte_and_preserves_neighbours() {
        let windows = golden_windows();
        let mut vals = decode_anytone_settings(&windows);
        // folk (bit 4 of 0x0BE) true; sklk/kblk/knlk in the same byte must stay.
        vals["folk"] = Value::from(true);
        let patches = encode_anytone_settings(&windows, &vals).unwrap();
        assert_eq!(patches.len(), 1);
        assert_eq!(patches[0].addr, 0x0350_0000 + 0x0BE);
        assert_eq!(patches[0].data, vec![0x10]); // only bit 4 set, others clear
    }

    #[test]
    fn bcd_be_round_trips_a_real_dmr_id() {
        // 3108176 -> 0x03 0x10 0x81 0x76 (big-endian packed BCD).
        assert_eq!(bcd_be_encode(3_108_176), [0x03, 0x10, 0x81, 0x76]);
        assert_eq!(bcd_be_decode(&[0x03, 0x10, 0x81, 0x76]), Some(3_108_176));
        // A factory-blank (0xFF) record decodes as "no ID".
        assert_eq!(bcd_be_decode(&[0xFF, 0xFF, 0xFF, 0xFF]), None);
    }

    #[test]
    fn radio_name_round_trips() {
        let enc = radio_name_encode("My Radio");
        assert_eq!(&enc[0..2], &[b'M', 0]);
        assert_eq!(radio_name_decode(&enc), "My Radio");
        // Blank (0xFF) reads as empty.
        assert_eq!(radio_name_decode(&[0xFF; 32]), "");
    }

    #[test]
    fn decode_reads_dmr_id_from_radio_id_region() {
        // Radio Id element 0: 3108176 named "My Radio".
        let mut rid = vec![0u8; 0x40];
        rid[0..4].copy_from_slice(&[0x03, 0x10, 0x81, 0x76]);
        rid[4..4 + 16].copy_from_slice(&radio_name_encode("My Radio")[..16]);
        let windows = vec![(RADIO_ID_BASE, rid)];
        let decoded = decode_anytone_settings(&windows);
        assert_eq!(decoded[DMR_ID_KEY], Value::from(3_108_176u32));
        assert_eq!(decoded[RADIO_NAME_KEY], Value::from("My Radio"));
    }

    #[test]
    fn encode_writes_both_id_records_and_used_flag() {
        // Start from blank (all-zero) radio-id regions.
        let windows = vec![
            (RADIO_ID_BASE, vec![0u8; 0x40]),
            (PRIMARY_ID_BASE, vec![0u8; 0x40]),
        ];
        let mut vals = Map::new();
        vals.insert(DMR_ID_KEY.into(), Value::from(3_108_176u32));
        vals.insert(RADIO_NAME_KEY.into(), Value::from("My Radio"));
        let patches = encode_anytone_settings(&windows, &Value::Object(vals)).unwrap();

        // Read the effective byte at an absolute address across all patches.
        let byte_at = |addr: u32| -> Option<u8> {
            patches.iter().find_map(|p| {
                let end = p.addr + p.data.len() as u32;
                (addr >= p.addr && addr < end).then(|| p.data[(addr - p.addr) as usize])
            })
        };
        // Element 0 DMR ID (BCD-BE).
        for (i, b) in [0x03, 0x10, 0x81, 0x76].iter().enumerate() {
            assert_eq!(byte_at(RADIO_ID_BASE + i as u32), Some(*b));
        }
        // Primary ID mirrors the DMR ID and sets its Used flag (region byte 0x26).
        for (i, b) in [0x03, 0x10, 0x81, 0x76].iter().enumerate() {
            assert_eq!(byte_at(PRIMARY_ID_BASE + i as u32), Some(*b));
        }
        assert_eq!(byte_at(PRIMARY_ID_BASE + 0x26), Some(1));
    }

    #[test]
    fn encode_leaves_id_region_untouched_when_no_dmr_id() {
        // A profile without a dmr-id must not disturb the radio's existing ID.
        let windows = vec![
            (RADIO_ID_BASE, vec![0xAAu8; 0x40]),
            (PRIMARY_ID_BASE, vec![0xAAu8; 0x40]),
        ];
        let vals = Value::Object(Map::new());
        let patches = encode_anytone_settings(&windows, &vals).unwrap();
        assert!(patches
            .iter()
            .all(|p| p.addr < RADIO_ID_BASE || p.addr >= PRIMARY_ID_BASE + 0x40));
        // A dmr-id of 0 (blank field) is likewise treated as "leave it alone".
        let mut z = Map::new();
        z.insert(DMR_ID_KEY.into(), Value::from(0u32));
        let patches = encode_anytone_settings(&windows, &Value::Object(z)).unwrap();
        assert!(patches.is_empty());
    }

    #[test]
    fn field_offsets_match_the_walk() {
        assert_eq!(field("enable-key-tone").byte, 0x000);
        assert_eq!(field("folk").byte, 0x0BE);
        assert_eq!(field("speaker-on-tx").byte, 0x15B);
        assert!(matches!(field("folk").kind, SK::BoolBit { lsb: 4 }));
        // Boot text lives in the Boot Settings region as UTF-16.
        assert_eq!(field("boot-text-line-2").base, 0x0350_0900);
        assert!(matches!(field("boot-text-line-2").kind, SK::Utf16 { chars: 14 }));
    }
}
