// GENERATED by scratchpad/kenwood_tmd710/gen_tmd710_aprs.py from
// scratchpad/kenwood_tmd710/APRS-MEASURED.md. Do not hand-edit; regenerate.
//
// `off` is a byte offset from the LIVE APRS block base (0x8100). These
// settings are not reachable by `MU` -- they live in the image behind
// `0M PROGRAM`, which is why this radio needs two transports for one
// settings form.
//
// ⚠ Only rows whose whole encoding is ANCHORED are here: every index is
// either measured on the radio, is the factory default confirmed against
// the A manual, or is the single remaining printed entry. This radio's
// manual has printed a short option list twice, so "the rest of the
// manual's list, in order" is not an anchor. The rest are listed under
// `## Owed` in the sheet, each with the check that would settle it.
pub(crate) const TMD710_APRS_FIELDS: &[AF] = &[
    AF { key: "aprs-data-band", label: "Data band", menu: "601", off: 0x00C, kind: AK::Enum { labels: &[(0, "A band"), (1, "B band"), (2, "TX A / RX B"), (3, "RX A / TX B")] } },  // measured 1,3; factory 0
    AF { key: "aprs-data-speed", label: "Packet data speed", menu: "601", off: 0x00D, kind: AK::Enum { labels: &[(0, "1200 bps"), (1, "9600 bps")] } },  // measured 0,1
    AF { key: "aprs-dcd-sense", label: "DCD sense", menu: "601", off: 0x00E, kind: AK::Enum { labels: &[(0, "D or RxD band"), (1, "Both band"), (2, "Ignore DCD")] } },  // measured 1,2; factory 0
    AF { key: "aprs-gps-baud", label: "GPS port baud rate", menu: "602", off: 0x011, kind: AK::Enum { labels: &[(0, "2400 bps"), (1, "4800 bps"), (2, "9600 bps")] } },  // measured 1,2; factory 1
    AF { key: "aprs-waypoint-name", label: "Waypoint name length", menu: "603", off: 0x016, kind: AK::Enum { labels: &[(6, "6-char"), (7, "7-char"), (8, "8-char"), (9, "9-char")] } },  // measured 6,9 — stores the literal
    AF { key: "aprs-speed-info", label: "Speed information", menu: "606", off: 0x083, kind: AK::Bool },  // measured 0,1
    AF { key: "aprs-altitude-info", label: "Altitude information", menu: "606", off: 0x084, kind: AK::Bool },  // measured 0,1
    AF { key: "aprs-position-ambiguity", label: "Position ambiguity", menu: "606", off: 0x085, kind: AK::Enum { labels: &[(0, "Off"), (1, "1 digit"), (2, "2 digits"), (3, "3 digits"), (4, "4 digits")] } },  // measured 2,4; factory 0 — index is the digit count
    AF { key: "aprs-position-comment", label: "Position comment", menu: "607", off: 0x087, kind: AK::Enum { labels: &[(0, "Off duty"), (1, "Enroute"), (2, "In service"), (3, "Returning"), (4, "Committed"), (5, "Special"), (6, "Priority"), (7, "Custom 0"), (8, "Custom 1"), (9, "Custom 2"), (10, "Custom 3"), (11, "Custom 4"), (12, "Custom 5"), (13, "Custom 6"), (14, "Emergency!")] } },  // measured 6,9; factory 0 — the APRS spec's own numbering
    AF { key: "aprs-filter-weather", label: "Packet filter: Weather", menu: "609", off: 0x167, kind: AK::Bit { bit: 5 } },  // mask measured with 0x01, 0x04, 0x2A
    AF { key: "aprs-filter-mobile", label: "Packet filter: Mobile", menu: "609", off: 0x167, kind: AK::Bit { bit: 4 } },  // mask measured with 0x01, 0x04, 0x2A
    AF { key: "aprs-filter-navitra", label: "Packet filter: Navitra", menu: "609", off: 0x167, kind: AK::Bit { bit: 3 } },  // mask measured with 0x01, 0x04, 0x2A
    AF { key: "aprs-filter-digi", label: "Packet filter: Digipeater", menu: "609", off: 0x167, kind: AK::Bit { bit: 2 } },  // mask measured with 0x01, 0x04, 0x2A
    AF { key: "aprs-filter-object", label: "Packet filter: Object", menu: "609", off: 0x167, kind: AK::Bit { bit: 1 } },  // mask measured with 0x01, 0x04, 0x2A
    AF { key: "aprs-filter-others", label: "Packet filter: Others", menu: "609", off: 0x167, kind: AK::Bit { bit: 0 } },  // mask measured with 0x01, 0x04, 0x2A
    AF { key: "aprs-beacon-method", label: "Beacon TX method", menu: "611", off: 0x16D, kind: AK::Enum { labels: &[(0, "Manual"), (1, "PTT"), (2, "Auto")] } },  // measured 2; factory 0
    AF { key: "aprs-decay-algorithm", label: "Decay algorithm", menu: "611", off: 0x16F, kind: AK::Bool },  // measured 0,1
    AF { key: "aprs-proportional-pathing", label: "Proportional pathing", menu: "611", off: 0x170, kind: AK::Bool },  // measured 0,1
    AF { key: "aprs-voice-alert", label: "Voice alert", menu: "614", off: 0x1DF, kind: AK::Bool },  // factory 0 = Off; live 1 read as On on the radio's screen
    AF { key: "aprs-voice-alert-ctcss", label: "Voice alert CTCSS frequency", menu: "614", off: 0x1E0, kind: AK::Ctcss },  // measured 8 = 88.5, 12 = 100.0 — 0-based into the driver's own 42-tone table
    AF { key: "aprs-ui-check-time", label: "UI check time (seconds)", menu: "617", off: 0x1E9, kind: AK::Uint { min: 0, max: 250 } },  // measured 28, 100 — the literal
    AF { key: "aprs-temperature-unit", label: "Temperature unit", menu: "626", off: 0x362, kind: AK::Enum { labels: &[(0, "Fahrenheit"), (1, "Celsius")] } },  // measured 0,1
];
