// GENERATED by scratchpad/kenwood_tmd710/gen_tmd710_settings.py from
// scratchpad/kenwood_tmd710/MEASURED.md. Do not hand-edit; regenerate.
//
// `mu` is a 0-BASED INDEX into the 42 comma-separated parameters of an
// `MU` line, not a byte offset -- the TM-D710 is a live-mode radio and
// has no image to hold settings in.
//
// ⚠ Every option list here has been checked against a range MEASURED on
// the radio: `d710_menu_bounds` swept each parameter and the first value
// the radio answered `?` to is the size of the enum. The generator
// refuses to emit a list whose length disagrees. That caught five errors
// in the published table, including two volume fields that are 7 levels
// and not 8 -- writing an 8th is refused, and display = stored + 1.
//
// 7 of 42 parameters are deliberately NOT emitted:
//   p25: **unknown**
//   p29: Panel PF1 key
//   p30: Panel PF2 key
//   p31: Mic PF1 key
//   p32: Mic PF2 key
//   p33: Mic PF3 key
//   p34: Mic PF4 key
// Their encoding is not determined, and guessing one is the failure
// mode that writes a wrong value to a real radio.
//
// A menu number ending in `?` is documentation only -- a wrong one
// mislabels a form field, it does not write a wrong value.
pub(crate) const TMD710_SETTINGS_FIELDS: &[TF] = &[
    TF { key: "key-beep", label: "Key beep", mu: 0, menu: Some("000"), kind: TK::Bool },  // MU p1; size MEASURED (2); measured (s120: turning it on moved p1 0→1)
    TF { key: "beep-volume", label: "Beep volume", mu: 1, menu: Some("001"), kind: TK::Enum { labels: &[(0, "1"), (1, "2"), (2, "3"), (3, "4"), (4, "5"), (5, "6"), (6, "7")] } },  // MU p2; size MEASURED (7); inferred (manual states levels 1-7; size measured)
    TF { key: "external-speaker-mode", label: "External speaker mode", mu: 2, menu: Some("002"), kind: TK::Enum { labels: &[(0, "Mode 1"), (1, "Mode 2")] } },  // MU p3; size MEASURED (2); inferred
    TF { key: "announce", label: "Announce", mu: 3, menu: Some("003"), kind: TK::Enum { labels: &[(0, "Off"), (1, "Auto"), (2, "Manual")] } },  // MU p4; size MEASURED (3); inferred
    TF { key: "language", label: "Language", mu: 4, menu: Some("004"), kind: TK::Enum { labels: &[(0, "English"), (1, "Japanese")] } },  // MU p5; size MEASURED (2); inferred
    TF { key: "voice-volume", label: "Voice volume", mu: 5, menu: Some("005"), kind: TK::Enum { labels: &[(0, "1"), (1, "2"), (2, "3"), (3, "4"), (4, "5"), (5, "6"), (6, "7")] } },  // MU p6; size MEASURED (7); inferred
    TF { key: "announce-speed", label: "Announce speed", mu: 6, menu: Some("006"), kind: TK::Uint { min: 0, max: 4 } },  // MU p7; size MEASURED (5); inferred
    TF { key: "playback-repeat", label: "Playback repeat", mu: 7, menu: Some("007"), kind: TK::Bool },  // MU p8; size MEASURED (2); inferred
    TF { key: "playback-repeat-interval", label: "Playback repeat interval", mu: 8, menu: Some("008"), kind: TK::Uint { min: 0, max: 60 } },  // MU p9; size MEASURED (61); inferred (value is the number)
    TF { key: "continuous-recording", label: "Continuous recording", mu: 9, menu: Some("009"), kind: TK::Bool },  // MU p10; size MEASURED (2); inferred
    TF { key: "vhf-aip", label: "VHF AIP", mu: 10, menu: Some("100"), kind: TK::Bool },  // MU p11; size MEASURED (2); inferred
    TF { key: "uhf-aip", label: "UHF AIP", mu: 11, menu: Some("101"), kind: TK::Bool },  // MU p12; size MEASURED (2); inferred
    TF { key: "squelch-hang-up-time", label: "Squelch hang-up time", mu: 12, menu: Some("106"), kind: TK::Enum { labels: &[(0, "Off"), (1, "125 ms"), (2, "250 ms"), (3, "500 ms")] } },  // MU p13; size MEASURED (4); inferred (manual, Menu 106, lists exactly these four)
    TF { key: "mute-hang-up-time", label: "Mute hang-up time", mu: 13, menu: Some("107"), kind: TK::Enum { labels: &[(0, "Off"), (1, "125 ms"), (2, "250 ms"), (3, "500 ms"), (4, "750 ms"), (5, "1000 ms")] } },  // MU p14; size MEASURED (6); inferred
    TF { key: "beat-shift", label: "Beat shift", mu: 14, menu: Some("108"), kind: TK::Bool },  // MU p15; size MEASURED (2); inferred
    TF { key: "time-out-timer", label: "Time-out timer", mu: 15, menu: Some("109"), kind: TK::Enum { labels: &[(0, "3 min"), (1, "5 min"), (2, "10 min")] } },  // MU p16; size MEASURED (3); inferred (as-found value 2 = 10 min)
    TF { key: "memory-recall-method", label: "Memory recall method", mu: 16, menu: Some("201"), kind: TK::Enum { labels: &[(0, "All bands"), (1, "Current band")] } },  // MU p17; size MEASURED (2); inferred
    TF { key: "echolink-speed", label: "EchoLink speed", mu: 17, menu: Some("205"), kind: TK::Enum { labels: &[(0, "Fast"), (1, "Slow")] } },  // MU p18; size MEASURED (2); inferred
    TF { key: "dtmf-hold", label: "DTMF hold", mu: 18, menu: Some("300"), kind: TK::Bool },  // MU p19; size MEASURED (2); inferred
    TF { key: "dtmf-speed", label: "DTMF speed", mu: 19, menu: Some("302"), kind: TK::Enum { labels: &[(0, "Fast"), (1, "Slow")] } },  // MU p20; size MEASURED (2); inferred
    TF { key: "dtmf-pause", label: "DTMF pause", mu: 20, menu: Some("303"), kind: TK::Enum { labels: &[(0, "100 ms"), (1, "250 ms"), (2, "500 ms"), (3, "750 ms"), (4, "1000 ms"), (5, "1500 ms"), (6, "2000 ms")] } },  // MU p21; size MEASURED (7); inferred — ★ the manual names Menu 303's seven values AND its 500 ms default, and the as-found value is 2, which is 500 ms under this order
    TF { key: "dtmf-key-lock", label: "DTMF key lock", mu: 21, menu: Some("304"), kind: TK::Bool },  // MU p22; size MEASURED (2); inferred
    TF { key: "automatic-repeater-offset", label: "Automatic repeater offset", mu: 22, menu: Some("401"), kind: TK::Bool },  // MU p23; size MEASURED (2); inferred
    TF { key: "1750-hz-tx-hold", label: "1750 Hz TX hold", mu: 23, menu: Some("402"), kind: TK::Bool },  // MU p24; size MEASURED (2); inferred
    TF { key: "display-brightness", label: "Display brightness", mu: 25, menu: Some("501"), kind: TK::Enum { labels: &[(0, "Off"), (1, "Level 1"), (2, "Level 2"), (3, "Level 3"), (4, "Level 4"), (5, "Level 5"), (6, "Level 6"), (7, "Level 7"), (8, "Level 8")] } },  // MU p26; size MEASURED (9); **measured** (s120 set LEVEL 3 and p26 alone moved 8→3, so index = level; size rules out Menu 504 CONTRAST, which has 16)
    TF { key: "automatic-brightness", label: "Automatic brightness", mu: 26, menu: Some("502"), kind: TK::Bool },  // MU p27; size MEASURED (2); inferred
    TF { key: "backlight-colour", label: "Backlight colour", mu: 27, menu: Some("503"), kind: TK::Enum { labels: &[(0, "Amber"), (1, "Green")] } },  // MU p28; size MEASURED (2); inferred
    TF { key: "microphone-key-lock", label: "Microphone key lock", mu: 34, menu: Some("513?"), kind: TK::Bool },  // MU p35; size MEASURED (2); inferred
    TF { key: "scan-resume-method", label: "Scan resume method", mu: 35, menu: Some("907?"), kind: TK::Enum { labels: &[(0, "Time-operated"), (1, "Carrier-operated"), (2, "Seek")] } },  // MU p36; size MEASURED (3); inferred (manual names the three modes, default Time-operated, and the as-found value is 0)
    TF { key: "auto-power-off", label: "Auto power off", mu: 36, menu: Some("917?"), kind: TK::Enum { labels: &[(0, "Off"), (1, "30 min"), (2, "60 min"), (3, "90 min"), (4, "120 min"), (5, "180 min")] } },  // MU p37; size MEASURED (6); inferred
    TF { key: "external-data-band", label: "External data band", mu: 37, menu: Some("918?"), kind: TK::Enum { labels: &[(0, "Band A"), (1, "Band B"), (2, "TX A-RX B"), (3, "TX B-RX A")] } },  // MU p38; size MEASURED (4); inferred
    TF { key: "external-data-speed", label: "External data speed", mu: 38, menu: Some("919?"), kind: TK::Enum { labels: &[(0, "1200 bps"), (1, "9600 bps")] } },  // MU p39; size MEASURED (2); inferred (manual, "set the data speed to 1200 or 9600 bps")
    TF { key: "sqc-output-source", label: "SQC output source", mu: 39, menu: Some("921?"), kind: TK::Enum { labels: &[(0, "Off"), (1, "Busy"), (2, "SQL"), (3, "TX"), (4, "Busy or TX"), (5, "SQL or TX")] } },  // MU p40; size MEASURED (6); inferred
    TF { key: "auto-pm-store", label: "Auto PM store", mu: 40, menu: Some("922?"), kind: TK::Bool },  // MU p41; size MEASURED (2); inferred
    TF { key: "display-partition-bar", label: "Display partition bar", mu: 41, menu: Some("928"), kind: TK::Bool },  // MU p42; size MEASURED (2); inferred (manual names Menu 928)
];
