// GENERATED by scratchpad/kenwood_tmd710/gen_tmd710_aprs.py from
// scratchpad/kenwood_tmd710/APRS-MEASURED.md. Do not hand-edit; regenerate.
//
// `off` is a byte offset from the LIVE APRS block base (0x8100). These
// settings are not reachable by `MU` -- they live in the image behind
// `0M PROGRAM`, which is why this radio needs two transports for one
// settings form.
//
// ⚠ Only rows whose whole encoding is ANCHORED are here: every index is
// either measured on the radio, is the factory default confirmed against
// the A manual, or is the single remaining printed entry. This radio's
// manual has printed a short option list twice, so "the rest of the
// manual's list, in order" is not an anchor. The rest are listed under
// `## Owed` in the sheet, each with the check that would settle it.
pub(crate) const TMD710_APRS_FIELDS: &[AF] = &[
    AF { key: "aprs-data-band", label: "Data band", menu: "601", off: 0x00C, kind: AK::Enum { labels: &[(0, "A band"), (1, "B band"), (2, "TX A / RX B"), (3, "RX A / TX B")] } },  // measured 1,3; factory 0
    AF { key: "aprs-data-speed", label: "Packet data speed", menu: "601", off: 0x00D, kind: AK::Enum { labels: &[(0, "1200 bps"), (1, "9600 bps")] } },  // measured 0,1
    AF { key: "aprs-dcd-sense", label: "DCD sense", menu: "601", off: 0x00E, kind: AK::Enum { labels: &[(0, "D or RxD band"), (1, "Both band"), (2, "Ignore DCD")] } },  // measured 1,2; factory 0
    AF { key: "aprs-gps-baud", label: "GPS port baud rate", menu: "602", off: 0x011, kind: AK::Enum { labels: &[(0, "2400 bps"), (1, "4800 bps"), (2, "9600 bps")] } },  // measured 1,2; factory 1
    AF { key: "aprs-waypoint-name", label: "Waypoint name length", menu: "603", off: 0x016, kind: AK::Enum { labels: &[(6, "6-char"), (7, "7-char"), (8, "8-char"), (9, "9-char")] } },  // measured 6,9 — stores the literal
    AF { key: "aprs-speed-info", label: "Speed information", menu: "606", off: 0x083, kind: AK::Bool },  // measured 0,1
    AF { key: "aprs-altitude-info", label: "Altitude information", menu: "606", off: 0x084, kind: AK::Bool },  // measured 0,1
    AF { key: "aprs-position-ambiguity", label: "Position ambiguity", menu: "606", off: 0x085, kind: AK::Enum { labels: &[(0, "Off"), (1, "1 digit"), (2, "2 digits"), (3, "3 digits"), (4, "4 digits")] } },  // measured 2,4; factory 0 — index is the digit count
    AF { key: "aprs-position-comment", label: "Position comment", menu: "607", off: 0x087, kind: AK::Enum { labels: &[(0, "Off duty"), (1, "Enroute"), (2, "In service"), (3, "Returning"), (4, "Committed"), (5, "Special"), (6, "Priority"), (7, "Custom 0"), (8, "Custom 1"), (9, "Custom 2"), (10, "Custom 3"), (11, "Custom 4"), (12, "Custom 5"), (13, "Custom 6"), (14, "Emergency!")] } },  // measured 6,9; factory 0 — the APRS spec's own numbering
    AF { key: "aprs-filter-weather", label: "Packet filter: Weather", menu: "609", off: 0x167, kind: AK::Bit { bit: 5 } },  // mask measured with 0x01, 0x04, 0x2A
    AF { key: "aprs-filter-mobile", label: "Packet filter: Mobile", menu: "609", off: 0x167, kind: AK::Bit { bit: 4 } },  // mask measured with 0x01, 0x04, 0x2A
    AF { key: "aprs-filter-navitra", label: "Packet filter: Navitra", menu: "609", off: 0x167, kind: AK::Bit { bit: 3 } },  // mask measured with 0x01, 0x04, 0x2A
    AF { key: "aprs-filter-digi", label: "Packet filter: Digipeater", menu: "609", off: 0x167, kind: AK::Bit { bit: 2 } },  // mask measured with 0x01, 0x04, 0x2A
    AF { key: "aprs-filter-object", label: "Packet filter: Object", menu: "609", off: 0x167, kind: AK::Bit { bit: 1 } },  // mask measured with 0x01, 0x04, 0x2A
    AF { key: "aprs-filter-others", label: "Packet filter: Others", menu: "609", off: 0x167, kind: AK::Bit { bit: 0 } },  // mask measured with 0x01, 0x04, 0x2A
    AF { key: "aprs-beacon-method", label: "Beacon TX method", menu: "611", off: 0x16D, kind: AK::Enum { labels: &[(0, "Manual"), (1, "PTT"), (2, "Auto")] } },  // measured 2; factory 0
    AF { key: "aprs-decay-algorithm", label: "Decay algorithm", menu: "611", off: 0x16F, kind: AK::Bool },  // measured 0,1
    AF { key: "aprs-proportional-pathing", label: "Proportional pathing", menu: "611", off: 0x170, kind: AK::Bool },  // measured 0,1
    AF { key: "aprs-voice-alert", label: "Voice alert", menu: "614", off: 0x1DF, kind: AK::Bool },  // factory 0 = Off; live 1 read as On on the radio's screen
    AF { key: "aprs-voice-alert-ctcss", label: "Voice alert CTCSS frequency", menu: "614", off: 0x1E0, kind: AK::Ctcss },  // measured 8 = 88.5, 12 = 100.0 — 0-based into the driver's own 42-tone table
    AF { key: "aprs-ui-check-time", label: "UI check time (seconds)", menu: "617", off: 0x1E9, kind: AK::Uint { min: 0, max: 250 } },  // measured 28, 100 — the literal
    AF { key: "aprs-temperature-unit", label: "Temperature unit", menu: "626", off: 0x362, kind: AK::Enum { labels: &[(0, "Fahrenheit"), (1, "Celsius")] } },  // measured 0,1
    AF { key: "aprs-beacon-type", label: "Beacon type", menu: "600", off: 0x00A, kind: AK::Enum { labels: &[(0, "APRS"), (1, "Navitra")] } },  // measured 1; factory 0; index 2 renders out-of-range text, so the list is two
    AF { key: "aprs-tx-delay", label: "TX delay", menu: "601", off: 0x00F, kind: AK::Enum { labels: &[(0, "100 ms"), (1, "150 ms"), (2, "200 ms"), (3, "300 ms"), (4, "400 ms"), (5, "500 ms"), (6, "750 ms"), (7, "1000 ms")] } },  // measured 0,2,3,5,7 each at its printed position; 1,4,6 bracketed between measured neighbours; 7 is the last printed entry so the list cannot be longer
    AF { key: "aprs-gps-input", label: "GPS data input", menu: "602", off: 0x012, kind: AK::Enum { labels: &[(0, "Off"), (1, "GPS"), (2, "Weather (PeetBros)"), (3, "Weather (Davis)")] } },  // all four measured — ⚠ 2 and 3 are the MANUAL'S ORDER REVERSED
    AF { key: "aprs-gps-output", label: "GPS data output", menu: "602", off: 0x013, kind: AK::Enum { labels: &[(0, "Off"), (1, "Waypoint"), (2, "DGPS")] } },  // measured 1,2; factory 0
    AF { key: "aprs-waypoint-format", label: "Waypoint format", menu: "603", off: 0x015, kind: AK::Enum { labels: &[(0, "NMEA"), (1, "Magellan"), (2, "Kenwood")] } },  // measured 1,2; factory 0
    AF { key: "aprs-waypoint-output", label: "Waypoint output", menu: "603", off: 0x017, kind: AK::Enum { labels: &[(0, "All"), (1, "Local"), (2, "Filtered")] } },  // measured 1,2; factory 0
    AF { key: "aprs-position-limit", label: "Position limit", menu: "609", off: 0x166, kind: AK::Enum { labels: &[(0, "Off"), (1, "10"), (2, "20"), (3, "30"), (4, "40"), (5, "50"), (6, "60"), (7, "70"), (8, "80"), (9, "90")] } },  // measured 1,3,9; factory 0 — a linear index x 10 confirmed at three points
    AF { key: "aprs-beacon-interval", label: "Beacon initial interval", menu: "611", off: 0x16E, kind: AK::Enum { labels: &[(0, "0.2 min"), (1, "0.5 min"), (2, "1 min"), (3, "2 min"), (4, "3 min"), (5, "5 min"), (6, "10 min"), (7, "20 min"), (8, "30 min"), (9, "60 min")] } },  // measured 3,4,5,9 — index 3 = 2 min is the entry the manual omits entirely
    AF { key: "aprs-interrupt-display-area", label: "Interrupt display area", menu: "625", off: 0x35C, kind: AK::Enum { labels: &[(0, "Off"), (1, "Half"), (2, "Entire"), (3, "Entire always")] } },  // ALL FOUR measured; index 4 renders garbage. ⚠ the manual prints three entries and calls the default ENTIRE; the radio has four and ships on the fourth
];
